feat: tabber component
devhatt/pet-dex-frontend pull request #101
Opened 2024-03-10 18:05 UTC by RafaelLimaC

Closes #28 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação do componente tabber, esse componente associa um botão a um conteudo, quando o botão é clicado todos os conteudos são escondidos e só o conteudo correpondente ao botão é exibido.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-03-12 16:44 UTC, Alecell commented on src/components/Tabber/index.js
> +    this.activateTab(0);
cria uma constante chamada `FIRST_TAB`

2024-03-13 16:00 UTC, Alecell requested changes
Alguns comentarios. Ta bom seu PR, mas vamos melhorar um pouco essa lógica!

2024-03-13 16:01 UTC, RafaelLimaC commented on src/components/Tabber/index.js
> +}
lá na parte de baixo n funciona, fala q está sendo usada antes de ser declarada

2024-03-13 16:36 UTC, RafaelLimaC commented on src/components/Tabber/index.js
> +  if (!iconURL) return;
sim!
recebo um erro de promise no console mas o componente funciona normalmente.

2024-03-13 17:11 UTC, RafaelLimaC commented on src/components/Tabber/index.js
> +  if (!iconURL) return;
Sim!
Recebo um erro de promise no console. mas o componente funciona normalmente

2024-03-13 18:33 UTC, RafaelLimaC commented on src/components/Tabber/index.js
> +function addIconToButton(tabButton, iconURL) {
Não entendi, tá falando desse early return caso a pessoa não passe path do svg?   if (!iconURL) return;

2024-03-13 18:34 UTC, RafaelLimaC commented on src/components/Tabber/index.js
> +    tabButtons.forEach((tab) => tab.classList.remove('tabber-button--active'));
Eu otimizei uma parte, mas para remover somente do q tinha a tag eu queria q rodar no minimo um querySelector ou deixar o index do anterior anotado em algum lugar, pensando q esse componente vai ser usado com no máx 3-4 tabs, acho que o modo atual já resolve bem

2024-03-13 18:40 UTC, Alecell commented on src/components/Tabber/index.js
> +function addIconToButton(tabButton, iconURL) {
Isso, o problema não é o early return em si, mas tipo essa função não retorna nada, mas usa do early return pra finalizar o processo e isso é ruim. Se ela retornasse algo seria ok usar o early return, no caso ela não retorna mas ta sendo usado o early return, nesse caso é ruim

2024-03-15 15:57 UTC, Alecell requested changes
Atualiza a branch

2024-03-15 15:57 UTC, Alecell commented on src/stories/Tabber.stories.js
Aqui precisamos de algo que permita alternar o formato de visualização (mobile/desktop) sem ter que mudar a resolução da tela.

2024-03-15 15:57 UTC, Alecell commented on src/components/Tabber/index.scss
> +@include breakpoints.from667 {
isso provavelmente funcione melhor com `@container` usando container query ao inves de média query.

2024-03-17 14:51 UTC, hxsggsz approved these changes

2024-03-17 14:51 UTC, hxsggsz commented on src/components/Tabber/index.js
> +
esse `FIRST_TAB` poderia ser dinâmico passando por parametro do componente porque talvez a gente precise salvar em qual tab o usuario ta pra salvar no localstorage

2024-03-17 16:59 UTC, hxsggsz approved these changes

2024-03-19 21:05 UTC, Alecell requested changes

2024-03-19 21:26 UTC, RafaelLimaC commented on src/components/Toggle/index.js
Foi o eslint q alterou sozinho quando salvei

2024-03-19 21:26 UTC, RafaelLimaC commented on src/components/Toggle/index.js
Foi só formatação

2024-03-19 23:05 UTC, Alecell approved these changes

2024-03-19 23:05 UTC, merged