feat: create page for pet register breed issue#93
devhatt/pet-dex-frontend pull request #111
Opened 2024-03-14 01:49 UTC by muritadb

Closes #93 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Pagina de cadastro de pets com opção de seleção, utilizando os componentes Petcard e Button

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

**CRIAÇÃO DO COMPONENTE**
Foi criado o componente PetRegisterPage em home/components, nele utiliza components de src/components(Button e PetCard) para composição da pagina.
Para renderiza-lo em tela tive que importar na home/index.js e comentando o component NoPetRegirestedPage para não sobrepor e/ou aumentar o container(pra não ter rolagem de tela) simulando um redirect para a pagina de cadastro.

**ESTILO DA PAGINA**
Aqui no index.scss tive que adaptar as classes '__button ' e '__pet-card':
- no button: ajustei o button para o tamanho do layout
- no __pet-card: ajustei o aspect-ratio para auto, pois a imagem  do pet não estava alinhada, também adicionei um cursor: pointer visto que se trata de um componente clicavel. 

**FAKE DATA**
Inicialmente tive dificuldades em renderizar mais de um pet-card, fui informado que seriam "buscados" do backend por meio de requisições, então utilizando de um array de objetos com os pets, consegui o layout desejado.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
   </summary>

![image](https://github.com/devhatt/pet-dex-frontend/assets/19556950/62f9788d-d368-408b-8e1a-9bdf9470799b)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [X] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Talvez será informado nas replies mas preciso de ajuda na responsividade, não consegui ajustar o layout para mobile.
</details>

2024-03-19 15:09 UTC, Alecell requested changes
Muito bom! Só faltou umas coisinhas

2024-03-19 15:09 UTC, Alecell commented on src/components/PetCard/index.scss
Adicionar EOF

2024-03-19 15:09 UTC, Alecell commented on src/home/components/PetRegisterPage/index.js
A página não está fazendo uma coisa que precisava ser feita, quando eu selecionar um pet e clicar em continuar é preciso que seja emitido um evento enviando a raça selecionada.

Também o botão de continuar deve ficar desabilitado até que a raça seja selecionada.

2024-03-19 15:09 UTC, Alecell commented on src/home/components/PetRegisterPage/index.scss
> +  min-height: 100%;
Não sei se precisamos dessa propriedade

2024-03-19 15:09 UTC, Alecell commented on src/home/components/PetRegisterPage/index.scss
> +    margin-top: 3.2rem;
GOD!!

2024-03-19 15:09 UTC, Alecell commented on src/home/components/PetRegisterPage/index.scss
> +  }
Esses dois estilos não deveriam ser necessários

2024-04-03 22:10 UTC, diogocaronte requested changes

2024-04-03 22:10 UTC, diogocaronte commented on src/home/index.js
> +// import mixedBreed from './components/PetRegisterPage/images/mixedBreed.svg';
não podemos deixar a home poluída
evite deixar comentários nos arquivos

2024-04-03 22:10 UTC, diogocaronte commented on src/home/index.js
> +// import PetRegisterPage from './components/PetRegisterPage';
não podemos deixar a home poluída
evite deixar comentários nos arquivos

2024-04-03 22:10 UTC, diogocaronte commented on src/home/index.js
> +
remover

2024-04-03 22:14 UTC, diogocaronte commented
seu arquivo .husky/prepare-commit-msg está com conflito com a main
atualize sua branch e resolva os conflitos

2024-04-05 11:52 UTC, Alecell requested changes
Coloque seu componente no storybook pra que possamos visualizar ele!

2024-04-12 14:07 UTC, Alecell approved these changes
Brabo! Só precisa atualizar a branch e achar outra pessoa pra revisar tbm!

2024-04-19 02:59 UTC, Alecell requested changes
Isso não pode acontecer em nenhuma resolução 
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/b9d0b7bd-79d7-4489-a3f8-75ff745852a2)

O espaçamento entre o botão e o grid de cachorros está errado 
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/2a848d87-1bc7-4c94-bc57-3be084f48c79)

O espaçamento entre os cards dos cachorros está errado 
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/f21b6baa-c800-49d1-befb-ee654d62b532)

Aproveita e colocar `cursor: pointer` nos petcards

Outra coisa que acabamos esquecendo de colocar na sua task mas é **crucial** é que vc precisa fazer com que o container de raças seja escrollavel quando a quantidade de itens for maior que o espaço disponível

2024-04-19 02:59 UTC, Alecell commented on src/home/components/PetRegisterPage/index.js
> +      .classList.toggle('pet-regirested-page__pet-container--active');
Não entendi, porque adicionamos essa classe `--active` aqui? Oque está ativo?

2024-04-19 02:59 UTC, Alecell commented on src/home/components/PetRegisterPage/index.js
> +    card.listen('desactive', () => {
marcou como resolved mas não foi resolvido, o nome do evento ta errado

2024-04-19 02:59 UTC, Alecell commented on src/home/components/PetRegisterPage/index.js
> +        .classList.contains('pet-container--active');
Não era melhor pegar o `this.activeCard`?

2024-04-19 02:59 UTC, Alecell commented on src/home/components/PetRegisterPage/index.js
> +      if (cardSelect) {
Essa condicional não faz muito sentido uma vez que eu nem posso clicar no botão se eu não tiver card ativo

2024-04-19 02:59 UTC, Alecell commented on src/home/components/PetRegisterPage/index.js
> +  });
To confuso, porque existem 2 eventos de `click` no `$button`? Um aqui e o outro na linha 49

2024-05-06 22:35 UTC, Alecell requested changes
Muito bom! Só mais alguns ajustes!

2024-05-06 22:35 UTC, Alecell commented on src/home/components/PetRegisterPage/index.spec.js
Cria a task de criar o teste dessa página por favor!

2024-05-06 22:35 UTC, Alecell commented on src/home/components/PetRegisterPage/index.js
> +      if (!this.activeCard) $button.disable();
precisa disso? Acho que esse `if` é desnecessário

2024-05-06 22:35 UTC, Alecell commented on src/home/components/PetRegisterPage/index.js
> +      this.breedSelect.push(card);
Pq isso é um array?

2024-05-06 22:35 UTC, Alecell commented on src/home/components/PetRegisterPage/index.js
> +      this.breedSelect.pop();
Ainda, porque isso é um array? Não era só usarmos a variavel de activeCard? Tipo, qual caso que teriamos uma `this,breedSelect`, mas não teriamos um `activeCard`?

2024-05-06 22:35 UTC, Alecell commented on src/home/components/PetRegisterPage/index.js
> +      if (this.breedSelect.length === 0) $button.disable();
Não era só usar o `activeCard` aqui?

Talvez faça sentido trocar o nome pra `selectedBreed`

2024-05-06 22:35 UTC, Alecell commented on src/home/components/PetRegisterPage/index.scss
> +  max-height: 50rem;
Nop, vc não pode fazer isso, sua página deve fluir de acordo com o conteúdo e de acordo com o espaço disponivel, não podemos definir larguras e/ou alturas fixas

Principalmente limites de alturas

2024-05-06 22:35 UTC, Alecell commented on src/home/components/PetRegisterPage/index.scss
> +  justify-content: center;
Isso aqui deveria ta junto né? Digo, sem espaços entre as propriedades, verifica se seu stylelint ta workando certinho

2024-05-06 22:35 UTC, Alecell commented on src/home/components/PetRegisterPage/index.scss
> +    width: 44rem;
Troca pra `max-width`, nesse caso queremos que nosso botão diminua quando a tela for menor, assim ele fluirá melhor se não definirmos uma largura chumbada

2024-05-15 00:16 UTC, Alecell approved these changes

2024-05-15 21:49 UTC, diogocaronte approved these changes

2024-05-15 21:49 UTC, diogocaronte commented on git
Por que esse arquivo existe?

2024-05-17 23:05 UTC, Alecell approved these changes

2024-05-17 23:05 UTC, merged