Issue 95
devhatt/pet-dex-frontend pull request #113
Opened 2024-03-19 20:15 UTC by JonySamarelli

Closes #95 #38 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Creates filter component and update colors file

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-frontend/assets/74078324/5c684d99-8ecb-4f4c-8923-07936603c684)
![image](https://github.com/devhatt/pet-dex-frontend/assets/74078324/ca2b56a3-8914-4854-8f59-ae422b76828a)
![image](https://github.com/devhatt/pet-dex-frontend/assets/74078324/ea5caf13-9cad-49da-889d-d698ba3f6ec6)
![image](https://github.com/devhatt/pet-dex-frontend/assets/74078324/6835cc1d-57e6-4da6-9650-cb652451fad2)
![image](https://github.com/devhatt/pet-dex-frontend/assets/74078324/ed36e5cb-7d14-43df-9db3-367318fe9d6f)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

Need help to improve testing

</details>

2024-03-20 15:07 UTC, Alecell commented
Manin vc fez mais doque a task, um pedaço doque vc fez era a task da página em si que já foi feita por outra pessoa então pra darmos seguimento preciso que vc apague o que ta fora do escopo da task.

No caso isso aqui precisa ser removido
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/011efff1-56b2-4c4d-b748-965138199282)


O escopo da task é apenas o botão de filtro
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/90c87bd3-18e0-4bd8-a785-5e5c2a63b063)

2024-03-21 19:51 UTC, JonySamarelli commented
Se fosse o contrário eu chorava pq esse botão me deu trabalho ;-;

2024-03-24 13:23 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.js
> +const events = ['selectNewOptions'];
Por que não apenas um evento de change ou select?

2024-03-24 14:35 UTC, diogocaronte requested changes

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +    overflow-y: auto;
Sobrescrita é realmente necessária?

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +    min-width: 200px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +    margin-bottom: 16px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +    border: 1px solid colors.$neutral200;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +    top: 62px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +    right: 0;
Isso não está bacana imagino que vai nos limitar para um futuro RTL mas, espere o @Alecell  revisar

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +    border-radius: 24px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +    background-color: colors.set-color-opacity(colors.$white, 0.8);
Isso de usar opacidade não me agrada, as cores devem ser padronizada. Oque significa 0.8?
mas espere o @Alecell revisar para decidir se muda

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +      margin-bottom: 8px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +      border: 1px solid colors.$neutral100;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +      &__element {
BEM está errado

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +      gap: 8px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +      margin-bottom: 24px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.scss
> +        gap: 4px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/Filter_DropDown/index.spec.js
> +  });
Esse tipo de teste aqui é necessário?

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.js
> +      <div class="filter__container__button" data-select="drop-down-button">
BEM está errado

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.js
> +  $dropDownButton.addEventListener('click', this.buttonHandler.bind(this));
Isso tem que estar dentro do mount

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.js
> +    $dropDownButton.removeEventListener('click', this.buttonHandler.bind(this));
Não precisa remover do componente, ele já foi desmontado

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.js
> +  $dropDownButton.addEventListener('click', this.buttonHandler.bind(this));
O bind retorna uma nova function! na hora de remover o listener imagino que não vai funcionar, pois será uma função diferente

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.js
> +    $dropDownButton.removeEventListener('click', this.buttonHandler.bind(this));
O bind retorna uma nova function! na hora de remover o listener imagino que não vai funcionar, pois será uma função diferente

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.js
> +  fetchOptions: function fetchOptions() {
Arrumar nomenclatura

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.js
> +      api(this.filterOptions.endpoint, 'GET').then((response) => {
Desacoplar a API

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.js
> +  buttonHandler: function buttonHandler() {
Arrumar nomenclatura.
Nossa interface do componente tem que ser independente da UI.

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.js
> +  },
Esse método não deve ser algo publico.

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.js
> +    $optionCounter.innerHTML =
```suggestion
    $optionCounter.innerText =
```

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.js
> +  selectNewOptionsHandler: function selectNewOptionsHandler(
Arrumar nomenclatura

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.scss
> +  &__container {
BEM está errado

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.scss
> +      height: 38px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.scss
> +      gap: 8px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.scss
> +      color: colors.set-color-opacity(colors.$neutral500, 0.9);
Isso de usar opacidade não me agrada, as cores devem ser padronizada. Oque significa 0.9?
mas espere o @Alecell revisar para decidir se muda

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.scss
> +      border: 1px solid colors.$neutral100;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.scss
> +      border-radius: 8px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.scss
> +          height: 20px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.scss
> +          border-radius: 100px;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.scss
> +        border: 1px solid colors.$secondary800;
Verique a necessidade do PX, provável que deva mudar para REM

2024-03-24 14:35 UTC, diogocaronte commented on src/components/Filter/index.spec.js
> +  });
Esse teste é necessário?

2024-04-05 01:48 UTC, closed without merging