feat: petvet page - cadastro de pet etapa 8
devhatt/pet-dex-frontend pull request #114
Opened 2024-03-19 20:39 UTC by juliaam

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Página de cadastro do petvet

</details>

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

- **Description**
  Página de petvet, equivalente a etapa 8 do cadastro

</details>

<details open> 
  <summary>
    <b>Visual evidences:
Tela desktop:
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/99eee114-846e-44fd-b004-d5d4668ff593)
Tela mobile:
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/6c22b46e-2203-42b6-9f85-d04dca5aafd3)

</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Observações:</b>
  </summary>
Aguardando componente de vacina e do input do checkbox, além disso, está faltando adicionar a fonte no projeto: 'Poppins', para que seja colocada em um texto
</details>

2024-03-21 20:11 UTC, juliaam commented
aguardando componente de input checkbox mergeado e componente de vacina

2024-05-22 12:24 UTC, DominMFD approved these changes

2024-05-22 13:19 UTC, Alecell requested changes
Preciso que ajuste o story pra que eu possa avaliar o `scss`

2024-05-22 13:19 UTC, Alecell commented on src/components/Vaccine/index.js
> +      <div class="vaccine__sections" data-select="group"> </div>
Identação

2024-05-22 13:19 UTC, Alecell commented on src/components/Vaccine/index.js
> +    <div class="vaccine__scroll">
Não acho que a classe precise mudar pq agora scrolla

2024-05-22 13:19 UTC, Alecell commented on src/components/Vaccine/index.js
> +  },
Pq tivemos criar essa função? O componente ja nao tava funcionando?

2024-05-22 13:19 UTC, Alecell commented on src/stories/PetVetPage.stories.js
O story precisa ter vacinas o suficiente pra triggar o scroll. O story precisa permitir que vejamos a funcionalidade por inteiro

2024-05-22 13:19 UTC, Alecell commented on src/home/components/PetVetPage/index.js
> +const events = ['value'];
Chama o evento de submit

2024-05-22 13:19 UTC, Alecell commented on src/home/components/PetVetPage/index.js
> +      </div>
Ta usando identação de 4 espaços, usar de 2

2024-05-22 13:19 UTC, Alecell commented on src/home/components/PetVetPage/index.js
> +    isRegistered: undefined,
`Registered`? Esse é campo e de `castrado` não `cadastrado` KKKKKKK

2024-05-22 13:19 UTC, Alecell commented on src/home/components/PetVetPage/index.js
> +  const registered = [
Renomeia tudo que deveria ser `neutered` e ta `registeres`

2024-05-22 13:19 UTC, Alecell commented on src/home/components/PetVetPage/index.js
> +    form.vaccines = this.vaccine.listVaccines();
Acho que entendi pq temos o `listVaccines`

2024-05-26 20:59 UTC, Alecell requested changes
Olha o video que mandei no discord, precisamos de um ajuste no comportamento!

2024-05-26 20:59 UTC, Alecell commented on src/components/Vaccine/index.scss
>    box-shadow: rgb(50, 50, 71);
Remover isso, nao existe

2024-05-26 20:59 UTC, Alecell commented on src/stories/PetVetPage.stories.js
> +    const $container = document.createElement('div');
Adiciona uma altura fix nessa div pra que no storybook possamos ver o scroll das vacinas

2024-06-06 20:14 UTC, merged