Issue 96
devhatt/pet-dex-frontend pull request #117
Opened 2024-03-26 20:56 UTC by ClaudioBioni

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-04-05 12:42 UTC, Alecell reviewed
Teve bastante alteração inexperada nesse PR. Essas alterações são coisas fora do escopo do seu componente e seria interessante não ter essas alterações nesse momento.

2024-04-05 12:42 UTC, Alecell commented on src/components/Button/index.scss
Alterações inexperadas

2024-04-05 12:42 UTC, Alecell commented on src/components/Tabber/index.js
Alterações inexperadas

2024-04-05 12:52 UTC, Alecell requested changes
Alguns ajustes!

A maioria é coisa que não deveria ter sido alterada nesse PR!

2024-04-05 12:52 UTC, Alecell commented on src/home/components/SideMenu/index.scss
Alterações inesperadas

2024-04-05 12:52 UTC, Alecell commented on src/home/index.js
Pet Register não fica aqui, precisamos remover.

2024-04-05 12:52 UTC, Alecell commented on src/home/index.scss
> +    // padding-block: 3.2rem;
Porque?

2024-04-05 12:52 UTC, Alecell commented on src/styles/base.scss
Alterações inesperadas

2024-04-05 12:52 UTC, Alecell commented on src/styles/base.scss
> +}
Não usamos border-box no projeto pra que o povo sofra com isso, usar especifico pra sua página ou tag tudo bem, mas não vamos colocar global

2024-04-05 12:52 UTC, Alecell commented on src/utils/swiper.js
Alterações inesperadas

2024-04-12 20:17 UTC, closed without merging

2024-04-12 20:52 UTC, ClaudioBioni commented on src/home/index.scss
> +    // padding-block: 3.2rem;
Removido.

2024-04-12 20:55 UTC, ClaudioBioni commented on src/home/components/PetRegister/index.scss
> +    border-radius: 14px;
Consertado.