Contunuação do PR = feat: Add RadioButton e Checkbox
devhatt/pet-dex-frontend pull request #121
Opened 2024-03-28 06:17 UTC by PiluVitu

Continuação do pr aberto pela @jeressy #90  

O novo pr foi aberto devido a não possibilidade de commit na main do fork da @jeressy, impossibilitando assim a continuação da task

_Closes #25_ 
<details open>
  <summary>
     <b> Feature </b>
  </summary>
Adiciona os componentes RadioButton e Checkbox. 
</details>
<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

- Checkbox: 

![Checkbox](https://github.com/devhatt/pet-dex-frontend/assets/100847406/8c7de3fb-9579-417f-be7f-e0f79e770e74)

- Radio Button: 

![radio_btn](https://github.com/devhatt/pet-dex-frontend/assets/100847406/237e49ae-4719-4b10-b023-146dad50a211)

- Componentes no storybook

https://github.com/devhatt/pet-dex-frontend/assets/69992923/51493c04-4119-414c-8ead-1ac48345401e

</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Ambos componentes foram documentados no storybook;
Checkbox possui suporte para ter opções desativadas, conforme na imagem acima. 
</details>

2024-03-28 06:17 UTC, PiluVitu commented
@jeressy

2024-03-28 13:52 UTC, diogocaronte requested changes

2024-03-28 13:52 UTC, diogocaronte commented on src/components/AvatarButton/index.scss
> +//TODO: Dar um confere aqui dps
Acho que não tem muito problema usar o @import mas, por que da necessidade da mudança?
Achei que seria padronizado usarmos o @use

https://vitejs.dev/guide/features#css

2024-03-28 13:52 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +  const $checkboxText = this.selected.get('checkbox-text');
Essa variável aqui parece não estar sendo utilizada nesse escopo

```suggestion
```

2024-03-28 13:52 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +export default function Checkbox({ isChecked = false, text = '', isDisabled = false, value = '' }) {
```suggestion
export default function Checkbox({ isChecked = false, text = '', isDisabled = false, value = '' } = {}) {
```

2024-03-28 13:52 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +
Precisamos lembrar de criar tanto o setter como o getter

```suggestion

  getText() {
    return this.selected.get('checkbox-text').textContent;
  },

```

2024-03-28 13:52 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +
Precisamos lembrar de criar tanto o setter como o getter
```suggestion

  isDisabled() {
    return this.selected.get('checkbox').disabled;
  },
  
```

2024-03-28 13:52 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +
Precisamos lembrar de criar tanto o setter como o getter
```suggestion

  getValue() {
    return this.selected.get('checkbox').value;
  },

```

2024-03-28 13:52 UTC, diogocaronte commented on src/components/Checkbox/index.js
Ficou faltando o name da checkbox para que seja possível agrupar as checkbox
Você pode usar como referencia o seu próprio componente de rádio

2024-03-28 13:52 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +  const $radioButtonText = this.selected.get('radio-button-text');
Essa variavel parece não está em uso no escopo
```suggestion
```

2024-03-28 13:52 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +
Precisamos lembrar de criar tanto o setter como o getter
```suggestion

  getText() {
    return this.selected.get('radio-button-text').textContent;
  },

```

2024-03-28 13:52 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +
Precisamos lembrar de criar tanto o setter como o getter
```suggestion

  getValue() {
    return this.selected.get('radio-button').value;
  },

```

2024-03-28 13:52 UTC, diogocaronte commented on src/components/RadioButton/images/Ellipse.svg
Esse nome em maiúsculo ta fora de padrão

2024-03-28 13:52 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +
Precisamos dos getter e setter para o desabilitado
```suggestion

  isDisabled() {
    return this.selected.get('radio-button').disabled;
  },

  setDisabled(isDisabled = false) {
    const $radioButton = this.selected.get('radio-button');
    $radioButton.disabled = isDisabled;
    this.emit('disable', isDisabled);
  },

```

2024-03-28 13:52 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +const events = ['change', 'value:change', 'text:change', 'name:change'];
Como vai precisar do método para desabilitar, então precisamos adicionar ele

```suggestion
const events = ['change', 'value:change', 'text:change', 'name:change', 'disable'];
```

2024-03-28 13:52 UTC, diogocaronte commented on src/stories/RadioButton.stories.js
> +};
```suggestion
};

export const Disabled = {
  args: {
    ...Default.args,
    isDisabled: true,
  },
};

```

2024-03-28 13:52 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +} = {}) {
Como vamos adicionar o método de desabilitar, precisamos da inicialização dele
```suggestion
export default function RadioButton({
  isChecked = false,
  text = '',
  value = '',
  name = '',
  isDisabled = false,
} = {}) {
```

2024-03-28 13:52 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +  this.setName(name);
Inicializar o estado de desabilitado

```suggestion
  this.setChecked(isChecked);
  this.setText(text);
  this.setValue(value);
  this.setName(name);
  this.setDisabled(isDisabled);
```

2024-04-04 23:21 UTC, diogocaronte approved these changes

2024-04-05 12:33 UTC, Alecell reviewed
Parece que esse PR tem muito mais arquivos doque realmente deveria ter. Verificar isso

2024-04-05 12:33 UTC, Alecell commented on src/styles/colors.scss
> +$gray500: rgba(172, 172, 181, 1);
usar `rgb`

2024-04-05 12:33 UTC, Alecell commented on src/styles/fonts.scss
Pq teve alteração nesse arquivo?

2024-04-05 12:33 UTC, Alecell commented on src/stories/readme/Readme.mdx
Pq teve alteração aqui?

2024-04-05 12:33 UTC, Alecell commented on src/components/Checkbox/index.js
> +    this.setChecked(isRealChecked);
Po coloca isso numa linha só 
```suggestion
    this.setChecked(e.target.checked);
```

2024-04-05 12:33 UTC, Alecell commented on src/components/Checkbox/index.js
> +  setChecked(isChecked = false) {
Renomeia isso pra `setCheck` e a propriedade pra `check`

2024-04-05 12:33 UTC, Alecell commented on src/components/Checkbox/index.js
> +  isDisabled() {
Da um enter entre os blocos

2024-04-05 12:33 UTC, Alecell commented on src/components/Checkbox/index.scss
> +  input[type='checkbox'] {
Não usar tag diretamente

2024-04-05 12:33 UTC, Alecell commented on src/components/Checkbox/index.scss
> +    appearance: none;
propriedade duplicada

2024-04-05 12:33 UTC, Alecell commented on src/components/Checkbox/index.scss
> +      background: $purple500 url('./images/check.svg') no-repeat center
Não usar shorthand

2024-04-05 12:33 UTC, Alecell commented on src/components/Checkbox/index.scss
> +  }
Usar fonte e configuração de fonte do arquivo de fontes

2024-04-05 12:33 UTC, Alecell commented on src/components/Checkbox/index.scss
> +    line-height: 2rem;
`line-height` sempre usar sem unidade

2024-04-05 12:33 UTC, Alecell commented on src/components/Checkbox/index.scss
> +    text-align: left;
Isso é necessário?

2024-04-05 12:33 UTC, Alecell commented on src/components/RadioButton/index.js
Mesmos callouts do checkbox se aplicam ao radio

2024-04-05 12:33 UTC, Alecell commented on src/components/RadioButton/index.scss
Mesmos callouts do checkbox se aplicam ao radio

2024-04-05 16:32 UTC, PiluVitu commented on src/components/Checkbox/index.js
> +  setChecked(isChecked = false) {
Porque mudar o isChecked ? Fica mais semântico o por ser um boolean

2024-04-05 16:44 UTC, PiluVitu commented on src/components/Checkbox/index.scss
> +    text-align: left;
Sim, pois estiliza o texto do checkbox, vou refatorar o nome para ficar mais condizente com o que ele é

2024-04-05 21:37 UTC, PiluVitu commented on src/home/index.html
Prettier

2024-04-05 21:38 UTC, PiluVitu commented on src/styles/fonts.scss
Era as configurações que tinham no pr dela

2024-04-05 21:38 UTC, PiluVitu commented on src/stories/readme/Readme.mdx
Deve ter sido o git não reconhecendo a mudança no rebase, nada foi alterado

2024-04-05 22:25 UTC, diogocaronte approved these changes

2024-04-09 20:55 UTC, Sherlockzen requested changes
Nos dois componentes o mouse fica pointer apenas na bolinha ou quadrado do check e radio, seria interessante que ele ficasse no botão todo.

2024-04-09 21:24 UTC, Sherlockzen approved these changes

2024-04-09 21:25 UTC, merged