Issue 97
devhatt/pet-dex-frontend pull request #123
Opened 2024-04-02 19:14 UTC by marceana

Closes #97 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação da tela de inserção de peso do pet

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![mobile](https://github.com/devhatt/pet-dex-frontend/assets/78447100/b0b36e4c-0714-47fa-b2c9-5aa49430bdee)
![tablet](https://github.com/devhatt/pet-dex-frontend/assets/78447100/d14bce59-d97e-4c83-94ce-36a522bb2724)
![pc](https://github.com/devhatt/pet-dex-frontend/assets/78447100/3b5ffb32-2059-41d0-83b9-1075728a767f)
</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Precisei mudar um pouco o css do RangeSlider e do UploadImage pra ficar mais parecido com o protótipo. No caso do RangeSlider o tamanho da fonte e da margem estavam parecendo meio diferentes. Já no UploadImage, como o tamanho mínimo estava settado como 186px eu não conseguia deixar ele menor, como no protótipo.
</details>

2024-04-05 15:40 UTC, Alecell requested changes

2024-04-05 15:40 UTC, Alecell commented on src/components/TextInput/index.js
> +    if (value !== '') {
Essa verificação é ruim, e se eu quiser limpar o input programaticamente?

Apenas remover o `if` é o suficiente

2024-04-05 15:40 UTC, Alecell commented on src/components/TextInput/index.js
> +  });
Não gosto muito desse `blur`, acredito que seria melhor um evento de `input`

Também não acho que precise desse `if` se o input ta disabled já não é possível selecionar ele, acho que essa função poderia ser:

```suggestion
  input.addEventListener('blur', () => this.emit('value:changed', input.value));
```

2024-04-05 15:40 UTC, Alecell commented on src/components/UploadImage/index.scss
> +    min-height: 100px;
usar `rem` ao inves de `px`

2024-04-05 15:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.js
> +        </div>
Só pra deixar o lembre-te que temos que substituir esses caras pelo componente de rádio no futuro

2024-04-05 15:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.js
> +    .classList.add('pet-weight-page__img');
Carai, gostei, parabens!!

Só talvez melhorar um pouco o nome, entre `pet-weight-page__img` e `pet-weight-page__image` tem muita margem pra confusão. O `pet-weight-page__image` poderia ser `pet-weight-page__image-container` e esse aqui `pet-weight-page__image`

2024-04-05 15:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.js
A página deve emitir os dados selecionados. No caso, quando clicarmos no botão, um evento de "submit"(não necessáriamente esse nome) deve ser enviado para que o componente pai tenha acesso ao que foi selecionado no filho.

2024-04-05 15:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.scss
> +    font-family: 'Montserrat', sans-serif;
Usar as fontes do arquivo de fontes

2024-04-05 15:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.scss
> +    width: 80vw;
Usar `%` pois vc quer sempre que o botão tenha `80%` to tamanho da página, não da tela

2024-04-05 15:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.scss
> +      max-width: 70vw;
Evitar esses usos de `vw`

Não é proibido, mas no caso não é o correto pois dentro de um container a gente quer a relatividade ao container, não a tela em si

2024-04-05 15:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.scss
> +      height: 3.5rem;
Evitar a todo custo largura e altura fixas!

2024-04-05 15:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.scss
> +      width: 41vw;
`%`

2024-04-05 15:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.scss
> +      max-width: 80vw;
`%`

2024-04-05 20:17 UTC, marceana commented on src/components/RangeSlider/index.scss
Modifiquei porque estava ficando um pouco diferente do protótipo mas olhando agora eu acho que precisava só diminuir um pouco a margem mesmo.  Como tava antes fica assim:

![image](https://github.com/devhatt/pet-dex-frontend/assets/78447100/2d3dcabe-b039-4c49-af3b-59be9b7de22a)

O protótipo: 

![image](https://github.com/devhatt/pet-dex-frontend/assets/78447100/4a316dde-fa0e-4457-be22-94be407eb1e8)

O tamanho da letra fica 80px mesmo com 8rem.

2024-04-05 20:21 UTC, marceana commented on src/components/TextInput/index.js
> +  }
Isso era um teste que eu estava fazendo e esqueci de tirar, sorry.

2024-04-05 20:26 UTC, marceana commented on src/components/TextInput/index.js
> +  });
Eu tentei fazer com o input antes mas aí o input fica com um comportamente estranho que não consegui entender o porque. Ele só deixa digitar um número e depois não consigo nem apagar o input mais. Por exemplo: se eu digitar 4, ele fica 4.0 e eu não consigo digitar e nem apagar mais.

2024-04-05 20:28 UTC, marceana commented on src/components/TextInput/index.js
> +    if (value !== '') {
Beleza, já ajustei.

2024-04-05 21:28 UTC, marceana commented on src/home/components/PetWeightPage/index.js
Faço que nem nos outros componentes?

```javascript
 const events = [ 'weight:submit' ]

// Resto do código

PetWeightPage.prototype = Object.assign(PetWeightPage.prototype, Component.prototype, {
     submitWeight( ) {
          // Implemento aqui
     }
}
```

2024-04-05 21:33 UTC, marceana commented on src/home/components/PetWeightPage/index.js
> +    .classList.add('pet-weight-page__img');
Que bom que ficou bom kkkkk
E vc tem razão, ajustei os nomes aqui.

2024-04-05 21:36 UTC, marceana commented on src/home/components/PetWeightPage/index.scss
> +    font-family: 'Montserrat', sans-serif;
Boa, não tinha me ligado.

2024-04-05 21:39 UTC, marceana commented on src/home/components/PetWeightPage/index.scss
> +      max-width: 70vw;
Beleza, vou ajustar.

2024-04-05 22:07 UTC, marceana commented on src/home/components/PetWeightPage/index.scss
> +      height: 3.5rem;
A altura por algum motivo só funciona em rem aqui.

2024-04-05 22:14 UTC, marceana commented on src/home/components/PetWeightPage/index.scss
> +      height: 3.5rem;
Sem a altura ele fica assim:

![image](https://github.com/devhatt/pet-dex-frontend/assets/78447100/9315fa66-2e4a-4256-8c04-0b138fae506f)

2024-04-18 22:47 UTC, diogocaronte requested changes

2024-04-25 22:56 UTC, marceana commented on src/home/components/PetWeightPage/index.js
> +  this.button.selected.get('button').classList.add('pet-weight-page__button');
Verdade, boa ideia!

2024-04-25 23:46 UTC, marceana commented on src/home/components/PetWeightPage/index.js
> +      if (!numericValue.isNaN && this.weight !== numericValue) {
Ops 🅰️

2024-05-01 14:11 UTC, Alecell requested changes
To com uma certa dificuldade de revisar apropriadamente porque não temos o storybook da página, mas tambem esta faltando os testes!

Não cheguei a revisar ainda apropriadamente, mas vamos criar o **testes** e o **story** para avançarmos aqui!

2024-05-07 00:40 UTC, Alecell requested changes
Cara ta muuuuito bom seu PR, tem só alguns ajustes e bala!!

Sei que fiz alguns comentários que não são exatamente sobre sua task, mas se der pra resolver é muito bom ;-;

2024-05-07 00:40 UTC, Alecell commented on src/components/RadioButton/index.scss
> +    appearance: none;
Propriedade duplicada

2024-05-07 00:40 UTC, Alecell commented on src/components/Checkbox/index.scss
> +  margin: 1rem;
Remover essa `margin`, quem decide o espaçamento do componente é quem chamar o componente, ele em si não pode ter um mínimo de espaço!

2024-05-07 00:40 UTC, Alecell commented on src/components/Checkbox/index.scss
> +    letter-spacing: 0;
Não rpecisamos dessa propriedade! Cuidado com propriedade que não está tendo efeito aplicado!

2024-05-07 00:40 UTC, Alecell commented on src/components/Checkbox/index.scss
> +    text-align: left;
Não precisamos desse `text-align` tambem! O padrão é alinhar a esquerda!

2024-05-07 00:40 UTC, Alecell commented on src/components/Checkbox/index.scss
> +    line-height: 2;
Esse `line-height` tambem não é necessário! Tomar cuidado com propriedades desnecessárias!

O figma ajuda e é um bom guia, mas ele tem muitas coisas que não necessariamente se aplicam no nosso CSS!

2024-05-07 00:40 UTC, Alecell commented on src/components/RadioButton/index.scss
> +  margin: 1rem;
Essa margin aqui, vamos remover, mesmo motivo da outra!

2024-05-07 00:40 UTC, Alecell commented on src/components/RadioButton/index.scss
> +    letter-spacing: 0;
Remover `text-align`, `font-weight`, `line-height` e `letter-spacing`

2024-05-07 00:40 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +    // console.log(new PetWeightPage(propsMock));
Remover o comentário

2024-05-07 00:40 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
Vale dizer, nào precisamos mais fazer os testes na mesma task! Só vou te pedir pra criar uma task de teste da sua página separada!

2024-05-07 00:40 UTC, Alecell commented on src/stories/PetWeightPage.stories.js
ow ta muito bom isso, papo10

2024-05-07 00:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.js
> +}
MUITO BOM

2024-05-07 00:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.js
> +        'pet-weight-page__image',
porque não apenas `this.image.selected.get('image-preview').classList.add('pet-weight-page__image')`? Entendo o problema que tentou resolver, mas acho que deu meio que na mesma, ainda estamos escrevendo bastante, acredito que não precisamos dessa função e pode colocar uma declaração em baixo da outra sem nada muito fancy

2024-05-07 00:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.js
> +      // Add classes to components
Pode remover o comentário e, no caso, acho que chamar a função de `applyCssClasses` seria muito bom tambem!

Evita a necessidade do comentário e explica melhor oq a função faz!

2024-05-07 00:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.js
> +      // Mount components
Não precisamos desse comentário, pode só apagar!

2024-05-07 00:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.js
Cara gostei MUUUUITO da sua organização nesse arquivo, acredito que pode virar um padrão pra paginas, de verdade!

2024-05-07 00:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.js
> +      }
Essa função precisa ser declarada em outro escopo, talvez ela receba parâmetros e faça oque ela já faz, a questão é que ela não é um `eventListener`, mas foi declarada aqui onde aplicamos os event listeners e isso é uma inconsistência semântica do código

2024-05-07 00:40 UTC, Alecell commented on src/home/components/PetWeightPage/index.scss
MUITO BOM

2024-05-09 00:14 UTC, marceana commented on src/stories/PetWeightPage.stories.js
tá bonitão né kkkkk

2024-05-09 00:34 UTC, marceana commented on src/home/components/PetWeightPage/index.js
> +      // Add classes to components
Beleza, faz sentido

2024-05-09 00:38 UTC, marceana commented on src/home/components/PetWeightPage/index.js
Que bom que gostou Ale, seria uma honra se isso acontecesse <3

2024-05-09 12:58 UTC, Alecell requested changes

2024-05-09 12:58 UTC, Alecell commented on src/home/index.scss
Pq tivemos alterações aqui?

2024-05-10 21:35 UTC, Alecell approved these changes

2024-05-10 22:09 UTC, diogocaronte approved these changes

2024-05-11 01:53 UTC, Alecell approved these changes

2024-05-11 01:55 UTC, merged