Criação do arquivo de cores
devhatt/pet-dex-frontend pull request #195
Opened 2024-04-19 13:06 UTC by JonasGz

Closes #38 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação do arquivo de cores

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![paleta-de-cores](https://github.com/devhatt/pet-dex-frontend/assets/13170219/46db9d62-3ebd-4d75-aa23-f6d98cb5a577)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ x ] Issue linked
- [ x ] Build working correctly
- [ x ] Tests created
</details>

<details open> 
  <summary>
    <b>Additional info</b>
  </summary>

**1. Encontrar a cor**
a. Vá ao figma desktop e clique no seu componente que no lado esquerdo aparecerá o código rgba da cor(se baseie no código e não na variável que aparecerá também, pois, algumas nomenclaturas foram alteradas com o passar do tempo e podem variar).
b. Vá ao arquivo **colors.scss** e encontre a variável correspondente ao código da cor encontrada no figma.
c. Siga o tutorial de utilização abaixo:

**2. Tutorial de utilização:**
a. Importar o arquivo colors.scss no seu componente
```@use '~styles/colors.scss' as colors;```
b. Na definição da cor do seu elemento, inclua ```colors.XXXX```, onde XXXX é a variável da cor escolhida, conforme exemplo abaixo:

```
.home {
   background-color: colors.$primary100;
}
```

Obs: novas cores podem surgir no andamento do projeto, caso precise adicionar uma cor que não esteja no rol, pergunte ao designer em qual categoria ela se encaixaria e adicione no arquivo.

</details>

2024-04-22 15:00 UTC, Alecell requested changes

2024-04-22 15:00 UTC, Alecell commented on src/styles/colors.scss
> +//shades
Só pela chatisse mesmo, coloca um tab em cada comentário

tipo 

```scss
//  cor do lance
$cor: rgba(bonita)
```

2024-04-22 21:27 UTC, PiluVitu requested changes
Mudar as cores de rbaa para rgb

2024-04-23 22:24 UTC, JonasGz commented on src/styles/colors.scss
> +//shades
Corrigido.

2024-04-24 12:33 UTC, PiluVitu approved these changes

2024-04-24 21:40 UTC, Alecell approved these changes

2024-04-24 21:40 UTC, merged