Add build and code-style CI
devhatt/pet-dex-frontend pull request #198
Opened 2024-04-22 15:40 UTC by PiluVitu

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-04-22 21:32 UTC, aalmeida00 approved these changes

2024-04-22 21:32 UTC, aalmeida00 commented on .npmrc
> +engine-strict=true
eof em 2024

2024-04-22 21:32 UTC, aalmeida00 commented on .github/workflows/build.yml
> +
```suggestion
```

2024-04-22 21:32 UTC, aalmeida00 commented on .github/workflows/build.yml
A identacao dese arquivo está correta? E para que serve ele no final, só separar o build? Se sim o nome deveria ser Node.js CI?

2024-04-22 22:02 UTC, PiluVitu commented on .github/workflows/build.yml
O arquivo apenas builda o projeto, alterei o nome como foi pedido

2024-04-23 00:01 UTC, aalmeida00 approved these changes

2024-04-24 02:40 UTC, Alecell requested changes
Pq tem teste no seu role?

Não era só docker?

2024-04-24 02:43 UTC, PiluVitu commented
> Pq tem teste no seu role?
> 
> Não era só docker?

Docker é a do petdex back, essa é criação da CI de build e stylecode
Responsáveis por verificar se o código está corretamente identado e buildado

2024-04-24 21:41 UTC, Alecell approved these changes

2024-04-24 21:42 UTC, merged