Issue 189
devhatt/pet-dex-frontend pull request #203
Opened 2024-04-26 21:19 UTC by nicolasfreitas-dev

Closes #189 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

  Correção do espaçamento do padding, posicionamento do input e criação de storie do componente.
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![Text Input](https://github.com/devhatt/pet-dex-frontend/assets/145572554/b38e8029-4969-4d64-a560-bac9d6cec0d5)
![image](https://github.com/devhatt/pet-dex-frontend/assets/145572554/2c76e15b-f4b3-4de3-8452-c0b1fb323836)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [X] Issue linked
- [X] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

Acredito que os parâmetros, "assetUrl" e "assetPosition", passados para a função TextInput estão com algum problema. Porém, eu não consegui encontrar uma maneira de consertar isso. Creio que esses parâmetros sejam referentes a esses dois ícones presentes no protótipo do Figma, dependendo da classe ("prefix" ou "suffix"), mas posso estar enganado.

![image](https://github.com/devhatt/pet-dex-frontend/assets/145572554/bd6a30ec-58e0-4e34-bdc1-b4a89d428cec)
![image](https://github.com/devhatt/pet-dex-frontend/assets/145572554/947aebf8-7c49-4dd9-b0d9-6ddd79779491)

</details>

</details>

2024-04-27 04:22 UTC, aalmeida00 approved these changes

2024-05-01 14:21 UTC, diogocaronte approved these changes

2024-05-01 18:17 UTC, Alecell requested changes
Os paddings do input não estão de acordo com o layout, por exemplo aqui é 16 horizontal e 18 vertical 
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/6fef9576-f87f-4a81-b801-ccc3ed966b66)

Se eu digito o texto deve ser no formato especificado no layout, perceba que ele possui um peso maior que o convencional: 
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/4a938727-dacf-4ef0-beca-ff7062312ffc)

2024-05-01 18:17 UTC, Alecell commented on src/components/TextInput/index.scss
> +      border: 1px solid colors.$gray200;
Propriedade duplicada

2024-05-01 18:17 UTC, Alecell commented on src/components/TextInput/index.scss
> +      border-bottom: 1px solid colors.$gray200;
propriedade duplicada

2024-05-07 00:07 UTC, Alecell requested changes
Só algumas alterações!

2024-05-07 00:07 UTC, Alecell commented on src/components/TextInput/index.scss
> +        border-radius: 14px;
pq o prefix em `border-radius` e o suffix não?

2024-05-07 00:07 UTC, Alecell commented on src/components/TextInput/index.scss
>        &.suffix {
Acredito que o `.suffix` e o `.prefix` devem ter a mesma propriedade de `padding` sempre, nesse caso pode ser algo assim:

```css
&.prefix, &.suffix {
  padding: 1.8rem 1.6rem
} 

&.prefix {
  //  Aqui os estilos especificos do prefix
}
```

2024-05-08 01:07 UTC, Alecell requested changes

2024-05-08 01:07 UTC, Alecell commented on src/home/index.js
Ta esquisita essa alteração, acredito que basta descomentar a importação e remover a importação com `/index`.

Se ta testando seu componente na página, da pra usar o storybook!!

Da uma olhadinha ou pergunta pra gente que mostramos!

2024-05-09 12:26 UTC, Alecell approved these changes

2024-05-09 21:32 UTC, Alecell approved these changes

2024-05-09 21:33 UTC, merged