Serviço de Rotas
devhatt/pet-dex-frontend pull request #207
Opened 2024-05-01 22:54 UTC by JonasGz

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-05-17 20:14 UTC, Alecell requested changes

2024-05-20 12:41 UTC, zoldyzdk requested changes
Eu vi alguns detalhes e também tem uma questão, vi muitos logs nos arquivos, eles são realmente necessários pra o roteamento? Alguns eu pontuei mas quando vi que era muito repetitivo parei, se não forem necessários pode tirar todos, e tem uns pathalias pra aplicar também.

2024-05-20 12:41 UTC, zoldyzdk commented on src/router/main-router.js
> +import meusPets from './routes/meus-pets/meus-pets';
É bom colocar tudo em inglês pra seguir o padrão do mercado.

2024-05-20 12:41 UTC, zoldyzdk commented on src/router/main-router.js
> +import rotasPrincipais from './routes/rotas-principais/rotas-principais';
Aqui também, inglês.

2024-05-20 12:41 UTC, zoldyzdk commented on src/router/routes/cadastro-pet/cadastro-pet.js
> +  petvet,
Aqui também, passar tudo pra inglês

2024-05-20 12:41 UTC, zoldyzdk commented on src/router/routes/cadastro-pet/etapas/aniversario.js
> +import NoPetRegirestedPage from '../../../../home/components/NoPetRegirestedPage';
É bom usar pathalias aqui.

2024-05-20 12:41 UTC, zoldyzdk commented on src/router/routes/cadastro-pet/etapas/aniversario.js
> +    console.log('Aniversario', routeLocation());
É necessário esse console log?

2024-05-20 12:41 UTC, zoldyzdk commented on src/router/routes/cadastro-pet/etapas/aniversario.js
> +      console.log('Bye AniversarioPet Page');
É necessário esse console log?

2024-05-20 12:41 UTC, zoldyzdk commented on src/router/routes/cadastro-pet/etapas/nome.js
> +import NoPetRegirestedPage from '../../../../home/components/NoPetRegirestedPage';
Pathalias aqui

2024-05-20 12:41 UTC, zoldyzdk commented on src/router/routes/cadastro-pet/etapas/nome.js
> +    console.log('Nome', routeLocation());
Se puder tirar, ranca fora

2024-05-20 12:41 UTC, zoldyzdk commented on src/router/routes/cadastro-pet/etapas/nome.js
> +      console.log('Bye NomePet Page');
Pode tirar os logs?

2024-05-20 12:41 UTC, zoldyzdk commented on src/router/routes/cadastro-pet/etapas/peso.js
> +import NoPetRegirestedPage from '../../../../home/components/NoPetRegirestedPage';
Pathalias

2024-05-21 16:22 UTC, JonasGz commented
> Eu vi alguns detalhes e também tem uma questão, vi muitos logs nos arquivos, eles são realmente necessários pra o roteamento? Alguns eu pontuei mas quando vi que era muito repetitivo parei, se não forem necessários pode tirar todos, e tem uns pathalias pra aplicar também.

não são, coloquei apenas como exemplo de utilização do método, ai o exemplo era emitindo um log, talvez a pessoa que criar a página precise emitir algum evento, ai deixei como exemplo, mas posso deletar

2024-05-21 23:01 UTC, JonasGz commented on vite.config.js
blz, não entendi 100%, mas vou te perguntar na daily

2024-05-21 23:03 UTC, JonasGz commented on src/router/routes/rotas-principais/rotas/conta.js
corrigido.

2024-05-21 23:03 UTC, JonasGz commented on src/router/main-router.js
> +import rotasPrincipais from './routes/rotas-principais/rotas-principais';
corrigido.

2024-05-21 23:03 UTC, JonasGz commented on src/router/routes/cadastro-pet/cadastro-pet.js
> +  petvet,
corrigido.

2024-05-21 23:04 UTC, JonasGz commented on src/router/routes/cadastro-pet/etapas/aniversario.js
> +import NoPetRegirestedPage from '../../../../home/components/NoPetRegirestedPage';
decidido manter sem o pathalias.

2024-05-21 23:04 UTC, JonasGz commented on src/router/routes/cadastro-pet/etapas/aniversario.js
> +    console.log('Aniversario', routeLocation());
não é necessário, foi usado apenas para exemplificar a utilização do routeLocation() que informa a rota atual, mas retirei.

2024-05-21 23:05 UTC, JonasGz commented on src/router/routes/cadastro-pet/etapas/aniversario.js
> +      console.log('Bye AniversarioPet Page');
não é necessário, foi usado apenas para exemplificar a utilização do método dispose() que emite um evento ao sair da rota, nesse caso fiz dar um log, mas foi retirado também.

2024-05-21 23:05 UTC, JonasGz commented on src/router/routes/cadastro-pet/etapas/nome.js
> +import NoPetRegirestedPage from '../../../../home/components/NoPetRegirestedPage';
decidido manter sem pathalias

2024-05-21 23:06 UTC, JonasGz commented on src/router/routes/cadastro-pet/etapas/nome.js
> +    console.log('Nome', routeLocation());
ranquei

2024-05-21 23:06 UTC, JonasGz commented on src/router/routes/cadastro-pet/etapas/nome.js
> +      console.log('Bye NomePet Page');
sim, foram retirados

2024-05-21 23:06 UTC, JonasGz commented on src/router/routes/cadastro-pet/etapas/peso.js
> +import NoPetRegirestedPage from '../../../../home/components/NoPetRegirestedPage';
decidido manter sem pathalias

2024-05-22 00:46 UTC, zoldyzdk approved these changes

2024-05-26 21:13 UTC, Alecell requested changes
Deveria estar funcionando os links laterais?

Tentei aqui e não funcionou

2024-05-26 21:13 UTC, Alecell commented on package.json
EOF

2024-05-28 19:42 UTC, JonasGz commented
> Deveria estar funcionando os links laterais?
> 
> Tentei aqui e não funcionou

pra funcionar é só incluir o atributo data-vanilla-route-link = "spa" e informar a rota no href do link 
eu n coloquei pq tínhamos acertado que iriamos deixar pra quem for usar o serviço
uma sugestão seria: o cara q criar a página setaria a rota no link ou botao correspondente 
ou uma task separada só pra linkar

2024-05-30 14:04 UTC, Alecell approved these changes
Sobre aquilo que falamos sobre o router parameter não é um blocker para sua task! Só precisamos conhecer isso melhor!

É importante vc deixar as rotas como exemplo aqui pra que as pessoas tenham como pegar os exemplos e fazer as rotas com mais falidade!!

Ta muito bom, parabens!

2024-05-30 18:35 UTC, JonasGz commented
> Sobre aquilo que falamos sobre o router parameter não é um blocker para sua task! Só precisamos conhecer isso melhor!
> 
> É importante vc deixar as rotas como exemplo aqui pra que as pessoas tenham como pegar os exemplos e fazer as rotas com mais falidade!!
> 
> Ta muito bom, parabens!

blz, vou dar uma estudada nos routes params tbm pra conseguir auxiliar a galera a utilizar.

2024-05-30 18:53 UTC, merged