feat: sliding component create
devhatt/pet-dex-frontend pull request #209
Opened 2024-05-03 20:32 UTC by DominMFD

Closes #94 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Componente de Sliding criado com algumas funcionalidades.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-frontend/assets/134434652/a13fc8a9-6413-4145-a47a-2d7d25ec0f9b)

https://github.com/devhatt/pet-dex-frontend/assets/134434652/afe1c65c-ce58-473c-b382-545806a121db

https://github.com/devhatt/pet-dex-frontend/assets/134434652/7bf976ce-fd17-4190-88c7-9a9a932df984

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

## Componente de Sliding

O componente de sliding permite que o usuário navegue por entre diferentes conteúdos por meio de botões clicáveis ou por meio de swipping.

### Propriedades

O componente recebe um array de itens que são os elementos que vão fazer parte do slide, também recebe mais duas propriedades: 

-  `loopMode:` recebe uma string que define se o loop do sliding vai ser `normal`, ou seja parar na extremidades, ou vai ser `infinite`.
- `controls:` recebe um boolean que define se vai ter os botões clicáveis ou não.

### Funcionalidades programáticas

O sliding tem algumas funções para seu uso de forma programática: 

- `addItem():` Adiciona o item passado por parâmetro ao componente;
- `removeItem():` Remove do componente o item passado por parâmetro;
- `setSlide():` Seleciona um item de forma programática;
- `next():` Passa para o próximo item; 
- `prev():` Volta para o item anterior;
- `setControls():` Muda a definição dos controles;
- `setLoopMode():` Muda o loopMode;
- `clearItems():` Limpa os itens do componente;
</details>

2024-05-07 01:31 UTC, hxsggsz requested changes

2024-05-07 01:31 UTC, hxsggsz commented on src/components/Sliding/index.js
> +    this.items.forEach((i) => {
essas variaveis de uma letra é meio paia, nao fica muito claro o que é
```suggestion
    this.items.forEach((item) => {

```

2024-05-07 01:31 UTC, hxsggsz commented on src/components/Sliding/index.js
> +      throw new Error('There are no next items');
nao sei se é legal jogar um erro se nao tiver o proximo item no slider por que isso vai quebrar a aplicação, talvez só um return vazio seja melhor

```suggestion
      return
```

2024-05-07 01:31 UTC, hxsggsz commented on src/components/Sliding/index.js
> +      throw new Error('There are no prev items');
mesma coisa do next

2024-05-07 01:33 UTC, hxsggsz commented
tem que ver o ci ai de eslint que ta quebrado tambem

2024-05-07 13:14 UTC, Alecell requested changes
Vamos conversar!!

2024-05-07 13:14 UTC, Alecell commented on src/components/Sliding/index.js
> +  this.controls = controls;
Oq essa opção `controls` faz?

2024-05-07 13:14 UTC, Alecell commented on src/components/Sliding/index.js
> +
Remover espaço em branco

2024-05-07 13:14 UTC, Alecell commented on src/components/Sliding/index.js
> +
Remover espaço em branco

2024-05-07 13:14 UTC, Alecell commented on src/components/Sliding/index.js
Seu componente não deveria possuir botões embutidos, seu componente deve funcionar independente dos controllers que adicionarmos a ele

2024-05-07 13:14 UTC, Alecell commented on src/components/Sliding/index.js
> +import './index.scss';
Move isso uma linha pra baixo

2024-05-07 13:14 UTC, Alecell commented on src/components/Sliding/index.scss
> +  width: max-content;
Noooo, isso aqui não é legal

Seu slider deve fluir de acordo com como quem usa o slider quer, essa forma limita o uso do slider ou exige sobrescrição de CSS, precisamos repensar isso!

2024-05-07 13:14 UTC, Alecell commented on src/components/Sliding/index.scss
> +    transition: background-color 0.4s ease-in-out;
Seu componente não deve ter controles padrão!

2024-05-07 13:14 UTC, Alecell commented on src/components/Sliding/index.scss
> +}
Esse modo que vc fez a troca de item precisa ser repensado acredito eu, funciona, sei disso, mas é uma forma limitante de fazer o slider. O componente que temos hoje faz uma simulação de um slider ao inves de slidar de fato

Oque acha de tentarmos fazer o slider usando scroll ao inves de usar transition?

2024-05-07 13:14 UTC, Alecell commented on src/components/Sliding/index.spec.js
Com a alteração que sugeri os testes vão ter uma grande alteração, então por enquanto não irei revisar até decidirmos se vamos ou não alterar o componente!

2024-05-07 13:14 UTC, Alecell commented on src/stories/Sliding.stories.js
Seu storybook não ta funcionando, parece que ta usando uma cor que não existe mais!

2024-05-09 23:45 UTC, Alecell requested changes
Tenho alguns comentarios e perguntas, mas no geral ta muito bom, eficiente e sucinto, tudo que um componente precisa ser, parabens!

O storybook precisa ter alguns controles pra podermos manusear o slider

Vc ta lidando demais com a width do slider, porque isso é tao necessario? Queria entender a lógica que vc usou pra esse slider, nao to falando que ta errada, só que eu preciso entender mesmo

2024-05-09 23:45 UTC, Alecell commented on src/components/Sliding/index.js
> +  };
Pq precisamos de um updateWidth?

2024-05-09 23:45 UTC, Alecell commented on src/components/Sliding/index.js
> +    this.updateWidth();
Pq precisa desse updateWidth?

2024-05-09 23:45 UTC, Alecell commented on src/components/Sliding/index.js
> +    if (!slideExist) throw new Error('Slide not exist');
De novo, se ta tentando remover algo que nao ta ali, nao precisa emitir erro

2024-05-09 23:45 UTC, Alecell commented on src/components/Sliding/index.js
> +    this.updateWidth();
WHYYYYYY

2024-05-10 00:41 UTC, DominMFD commented on src/components/Sliding/index.js
> +    if (!slideExist) throw new Error('Slide not exist');
Aqui eu viajei mesmo, desculpa

2024-05-15 00:49 UTC, Alecell requested changes

2024-05-15 00:49 UTC, Alecell commented on src/components/Sliding/index.js
> +      this.selected.get('sliding-content').clientWidth / this.slides.length;
Talvez eu esteja sendo muito chato, mas o `slideWidth` não é exatamente o `slide.lenght/slidesQty`?

2024-05-15 00:49 UTC, Alecell commented on src/components/Sliding/index.js
> +      this.selected.get('sliding-content').clientWidth / this.slides.length;
Aqui a mesma coisa

2024-05-15 00:49 UTC, Alecell commented on src/components/Sliding/index.js
> +
Remover espaço em branco

2024-05-15 00:49 UTC, Alecell commented on src/components/Sliding/index.js
> +
Remover espaço em branco

2024-05-17 12:31 UTC, Alecell requested changes

2024-05-17 12:31 UTC, Alecell commented on src/components/Sliding/index.js
> +
remover espaço em branco

2024-05-17 12:31 UTC, Alecell commented on src/components/Sliding/index.js
> +
remover espaço em branco

2024-05-17 12:31 UTC, Alecell commented on src/components/Sliding/index.js
> +
remover espaço em branco

2024-05-17 12:31 UTC, Alecell commented on src/components/Sliding/index.spec.js
seus slides tem que possuir conteudo e vc deve queryar esse conteúdo. No caso, buscar por um texto dentro do slide. Nào faça da forma que vc está fazendo. Vc deve testar input e output, não fazer como esta fazendo.

2024-05-17 12:31 UTC, Alecell commented on src/components/Sliding/index.spec.js
> +      sliding.selected.get('sliding-content').style.transform;
Isso aqui é irrelevante pro seu teste. Vc precisa verificar de outra forma. Essa forma de verificar é basiacmente nada.

2024-05-17 12:31 UTC, Alecell commented on src/components/Sliding/index.spec.js
> +    expect(sliding.selected.get('sliding-content').children).not.toContain(
Vc deve usar o `screen` para pegar os elementos e não ficar usando o `sliding`

2024-05-22 12:22 UTC, Alecell requested changes

2024-05-22 12:22 UTC, Alecell commented on src/components/Sliding/index.spec.js
> +  describe('when mount', () => {
`on mount`

2024-05-22 12:22 UTC, Alecell commented on src/components/Sliding/index.spec.js
> +describe('Sliding', () => {
`Slide`

2024-05-22 12:22 UTC, Alecell commented on src/components/Sliding/index.spec.js
> +    it('render with 3 itens', async () => {
`renders with items passed by props`

2024-05-22 12:22 UTC, Alecell commented on src/components/Sliding/index.spec.js
> +  describe('when call functions', () => {
poderia ser `method`, mas eu acho que não gosto desse `describe` aqui nao. Vc precisa ser capaz de ler os describes até o it de uma forma linear, por exemplo
`Slide method add item programmatically`, no caso eu não sei bem oq adicionar nesse describe aqui em cima, mas é valido ver oq pode adicionar.

2024-05-22 12:22 UTC, Alecell commented on src/components/Sliding/index.spec.js
> +    });
Esses testes são ruins, testar classe não significa muita coisa, a classe pode estar lá, mas não estar fazendo aquilo que vc espera.

Pra esses 2 testes seria melhor testar justamente o evento de `slide:next` e `slide:prev`

2024-05-26 21:07 UTC, Alecell requested changes

2024-05-26 21:07 UTC, Alecell commented on src/components/Sliding/index.spec.js
> +  });
Nesses dois eventos o ideal seria appendar um listen no nosso sliding tipo

```js
const sliding = makeSut(propsMock)

const callback = vi.fn()
sliding.listen('slide:next', callback)

expect(callback).toBeCalledWith($slide3)
```

Assim testamos não oq o metodo executa, mas oq ele faz! O valor do emit não é a emissão em si, mas a chamada de outra função cuja deve receber o slide atual como parametro!

2024-05-26 21:07 UTC, Alecell commented on src/components/Sliding/index.spec.js
> +    expect(slidingSpy).toHaveBeenCalledWith('slides:clear');
Mesma coisa aqui sobre o spy, usar um metodo callback que escuta o evento. Pra todos os eventos o melhor é fazer do modo que falei, se for possivel.

2024-05-29 22:12 UTC, Alecell approved these changes

2024-05-30 00:52 UTC, diogocaronte approved these changes

2024-06-03 14:48 UTC, merged