window.matchmedia mock and Drawer tests
devhatt/pet-dex-frontend pull request #216
Opened 2024-05-07 23:29 UTC by RafaelLimaC

Closes #215 #210 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-05-10 15:50 UTC, Frompaje commented on src/components/Button/button.spec.js
> +      const text = screen.getByText('content');
Seria maneiro pegar a semantica do Give, when, then, igual como você fez na linha 16 pra 22

2024-05-12 17:52 UTC, zoldyzdk requested changes

2024-05-12 17:52 UTC, zoldyzdk commented on src/components/Drawer/index.spec.js
> +      const mountSpy = vi.spyOn(drawer, 'mount')
Fiquei em dúvida se o teste se refere a montagem do conteúdo do drawer ou na verdade ele testa a montagem toda do drawer?
Ai eu vi que tem um teste pra ver se ele renderiza o title, talvez esteja faltando um pra testar especificamente o conteúdo não acha?

2024-05-12 17:52 UTC, zoldyzdk commented on src/components/Drawer/index.spec.js
> +      'drawer--open',
Uma vez me disseram que verificar se classe X estava no componente é um teste ruim, até por algum motivo mudarem o nome da classe lá no componente o teste quebra. Será que não tem outra forma de verificar se o drawer fechou sem usar classe?

2024-05-12 18:34 UTC, RafaelLimaC commented on src/components/Drawer/index.spec.js
> +      const mountSpy = vi.spyOn(drawer, 'mount')
montagem do conteudo do drawer, o drawer sempre recebe um componente como conteudo, e esse componente tem que ser montado

2024-05-13 21:08 UTC, zoldyzdk approved these changes

2024-05-14 13:50 UTC, Alecell requested changes

2024-05-14 13:50 UTC, Alecell commented on src/__tests__/setup.js
EOF

2024-05-14 13:50 UTC, Alecell commented on vite.config.js
Pq teve alteração nesse arquivo?

2024-05-14 13:50 UTC, Alecell commented on src/components/Drawer/index.spec.js
> +    })
Isso pode ser um teste só, a renderização do conteúdo e titulo é uma coisa só e é valido que ambas sejam checadas no mesmo teste

2024-05-14 13:50 UTC, Alecell commented on src/components/Drawer/index.spec.js
> +    })
Esse segundo teste não está testando nada praticamente, pra testar isso coloca dentro do drawer um conteúdo com um texto escrito alguma coisa e verifica se vc consegue encontrar esse texto dentro do drawer, ai sim temos um teste de valor, no caso vc ta testando o mount, se por qualquer motivo o mount chamar, mas nao colocar oq é preciso dentro do container vamos ter um falso positivo.

Sempre teste input e output, em geral usar o `toBeCalled` e `toBeCalled` with é um sinal que estamos testando implementação e não comportamento. Queremos sempre testar comportamento independente de implementação

2024-05-15 13:35 UTC, Alecell requested changes

2024-05-15 14:26 UTC, Alecell approved these changes

2024-05-15 14:27 UTC, merged