Issue 227
devhatt/pet-dex-frontend pull request #247
Opened 2024-05-18 20:35 UTC by klebsonmateus

Closes #227 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação do RadioButton sem borda.

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  - Ajuste na lista de eventos do componente Checkbox.
  - Ajuste na chamada da função SetCheck() no componente Checkbox.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>
![2024-05-18 17_33_35](https://github.com/devhatt/pet-dex-frontend/assets/8119855/47bbd6a8-554c-42d8-b042-98b939d102b9)
![2024-05-18 17_33_50](https://github.com/devhatt/pet-dex-frontend/assets/8119855/20abf44b-1fb0-442d-bb53-e856df48454f)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

2024-05-20 12:09 UTC, zoldyzdk approved these changes

2024-05-20 13:35 UTC, Alecell requested changes

2024-05-20 13:35 UTC, Alecell commented on src/components/Checkbox/index.js
> +  'name:change',
Pq temos esse novo evento?

2024-05-20 13:35 UTC, Alecell commented on src/components/RadioButton/index.scss
Acredito que não basta remover a borda, precisa de provaavelmente mais alguns ajustes no componente pra que ele nao fique gigante em termos de altura

2024-05-21 12:31 UTC, zoldyzdk approved these changes

2024-05-22 12:24 UTC, Alecell approved these changes

2024-05-22 12:25 UTC, merged