Issue 220 - Teste da página de peso do pet
devhatt/pet-dex-frontend pull request #252
Opened 2024-05-26 19:26 UTC by marceana

Closes #220

2024-05-30 00:41 UTC, DominMFD requested changes

2024-05-30 00:41 UTC, DominMFD commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +  });
beforeEach() não é uma boa prática em testes, ainda mais que só ta inicializando o componente, você pode fazer isso no começo de cada It, fica mais legível.

2024-05-30 00:41 UTC, DominMFD commented on src/home/components/PetWeightPage/petWeightPage.spec.js
>    });
não precisa desse teste, é padrão do DiogoJs ser uma função, você não precisar testar isso.

2024-05-30 00:41 UTC, DominMFD commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +  });
mesma coisa que o de cima, não precisa testar isso pois é padrão do DiogoJs

2024-05-30 14:29 UTC, Alecell requested changes
Esse teste que o @DominMFD fez pode ajudar a entender oq quero dizer com tudo que disse, o objeto screen acessa a nossa screen e permite que manipulemos a página igual o usuário manipularia, sem acesso a intrinsecidades do componente, mas sim, apenas interagindo com a pagina!

https://github.com/devhatt/pet-dex-frontend/blob/4fa4790c9741c04fdaef3b82cc778c6202956c27/src/components/Sliding/index.spec.js

2024-05-30 14:29 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +}));
Acho que não precisamos mockar todos esses componentes, lembre-se que quanto mais mocks um teste tem, menos fiel a realidade ele pode ser, nesse caso mockar todos esses componentes pode acontecer do teste passar mesmo com o componente sendo alterado!

Nesses casos queremos usar o componente em si, em sua maior instancia!

Vamos usar mocks pra coisas que não conseguimos/devemos usar no ambiente de teste como por exemplo request http, file system e coisas assim!

2024-05-30 14:29 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +  });
Esse teste não é um teste em si!

Recentemente fiz a famigerada talk de testes que falo sobre isso!!

Vamos sempre testar comportamento, nunca detalhes de implementação, no caso testar se certos elementos estão na pagina não tem muito valor, o valor mesmo está em testar se eles funcionam!

No caso se quisermos um smoke testing podemos testar se o container da página em si está lá e já seria o suficiente

2024-05-30 14:29 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +    expect(UploadImage).toHaveBeenCalledWith();
Evitar testes com `toHaveBeenCalled` e `toHaveBeenCalledWith`, queremos sempre garantir comportamento, não coisas internas do código

No caso, queremos que, apos adicionar uma foto e colocar o peso, queremos que no evento de submit recebemos a nova foto e o peso selecionado e é isso que queremos testar. To be called with é um teste de implementação, oque nos queremos é teste de comportamento, do modo como o componente é usado em si!

2024-05-30 14:29 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +    );
Mesma coisa aqui, queremos testar se os valores são retornados, não se os metodos foram chamados. Ainda mais, se os metodos foram chamados corretamente, os valores finais retornados estarão corretos no fim, logo nunca teremos um falso positivo, mas testar se algo dentro do componente é ou se foi chamado já não garante isso, tudo pode ser e ter sido chamado, mas no fim os valores retornados no fim estarem errados, ironicamente eu cai num erro assim ontem. Os testes do componente passavam, mas o componente não retornava o valor como deveria pq foi testado implementação e não comportamento

2024-05-30 14:29 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +    const mockWeight = 5.0;
Não é interessante colocar o peso diretamente dentro da instancia assim tambem, devemos testar nosso componente da forma como ele é usado, no caso precisamos editar o input ou mesmo, se possivel, alterar o valor do slider "slidando". Mas colocar dessa forma é indicio de falso positivo.

2024-05-30 14:29 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +    instance.radioKG.getValue = () => 'kg';
mesma coisa aqui. Lembre-se de usar os métodos do `screen` do Testing Library

2024-05-30 14:29 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +    expect(emitSpy).toHaveBeenCalledWith('weight', mockWeight, 'kg');
Esse este do emit não é muito eficiente, novamente estamos testando implementação e não uso, precisamos garantir que o uso esta da forma que queremos, nesse caso o melhor seria algo assim

```js
const callback = vi.fn()
instance.listen('weight:change', callback);
const weightInput = screen.getByAltText('my-text')
userEvent.input(weightInput, '1.5')
expect(callback).toHaveBeenCalledWith({  data expected  })
```

perceba que aqui, mesmo usando `toHaveBeenCalled` não estamos usando isso com implementações internas do componente, mas sim como esperamos que o nosso componente retorne dado um input especifico.

Estamos testando como o componente se comunica com quem o usa, não como ele funciona internamente!

2024-05-30 14:29 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
>    });
Falei bastante sobre isso na talk de testes, esse teste na verdade não testa nada. Isso nào tem valor em nivel de testes pra gente pois é uma informação de nada pra nada. Tipo, se eu apagar todo o arquivo CSS esse teste ainda vai passar, assim esse teste verifica apenas se certas propriedades foram adicionadas, mas não temos como garantir que essas propriedades estão de fato causando o efeito esperado.

No caso testar coisas que tem integração com CSS são, no fim, testes de integração! Entào não devemos nunca testar nada que envolva CSS/SCSS em testes unitários uma vez que ele não permite que nos possamos testar se de fato os estilos estão _funcionando_, que é oq realmente importa, não a classe, mas sim os estilos!

Pode remover todo esse bloco! Na talk que dei explico melhor!

2024-05-30 14:29 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +  });
Esse teste a mesma coisa, precisa trocar os valores como o componente é usado, não adicionando manualmente as propriedades!

2024-06-30 20:01 UTC, marceana commented
Obs.: Sobre o teste que eu queria fazer, eu acho que não é possível, pelo que pesquisei:

![image](https://github.com/devhatt/pet-dex-frontend/assets/78447100/4c6ee074-0957-496c-8e6a-6dfcd4c8059a)

Eu tentei de várias formas mas não consegui, se souberem de uma maneira que dê pra fazer eu posso tentar aparecer no plantão de dúvidas pra entender como seria.

2024-07-08 12:23 UTC, Alecell requested changes
Precisamos fazer testes mais significativos que de fato testem o comportamento

2024-07-08 12:23 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +describe.only('Pet Weight page', () => {
Remover o `.only`

2024-07-08 12:23 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
Não precisamos testar se cada coisa individualmente renderizou na página, apenas 1 teste de render verificando se 1 dos elementos renderizou é o suficiente, testar renderização de cada elemento é um teste de baixo valor.

O teste de se a imagem está funcionando é valido.

Os testes que realmente precisam ser feitos aqui são:
- Quando eu clico nos `radio` buttons, eles selecionam? 
- Seleciono apenas 1 por vez e nunca posso selecionar 2 ao mesmo tempo
- Consigo digitar no campo de input
- Quando altero o campo de input o valor do weight slider emitido é o valor que mandei
- Enquanto não tenho um peso selecionado e uma unidade de medida selecionada o botao `continuar` não é clicavel
- Quando clico em continuar com o botao ativo os dados do slider são emitidos

2024-07-23 15:39 UTC, Alecell requested changes

2024-07-23 15:39 UTC, Alecell commented on src/home/components/PetWeightPage/petWeightPage.spec.js
> +describe.only('Pet Weight page', () => {
Precisamos remover o `.only`!

2024-07-26 21:48 UTC, DominMFD approved these changes

2024-08-06 15:10 UTC, PiluVitu approved these changes

2024-08-11 21:47 UTC, DominMFD approved these changes

2024-08-11 21:47 UTC, merged