Issue-236 - Creation of mock API for the frontend
devhatt/pet-dex-frontend pull request #254
Opened 2024-05-30 00:23 UTC by nicolasfreitas-dev

Closes #236 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação de mock da API para simular a comunicação dos componentes com os serviços do frontend, enquanto a API do backend não está pronta para uso.

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>

O mock da API foi criado utilizando Json-Server que é uma biblioteca Node.JS usada para simular API REST a partir de um arquivo JSON. E para realizar os testes dos endpoints da API foi utilizado o Postman.

Esse mock utiliza os métodos GET, POST, PUT, DELETE do protocolo HTTP para realizar as requisições das informações. Abaixo estão documentados os endpoints necessários para cada requisição:

**[GET] Pega todos os usuários**
URL: `/users/`

**[GET] Pega usuário específico pelo ID**
URL: `/users/id`

**[POST] Adiciona novo usuário**
URL: `/users/`

**[PUT] Atualiza um usuário pelo ID**
URL: `/users/id`

**[DELETE] Deleta um usuário específico pelo ID**

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![code](https://github.com/devhatt/pet-dex-frontend/assets/145572554/0af1e0d1-b690-4200-89ce-817d674c6667)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ X ] Issue linked
- [ X ] Build working correctly
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

O arquivo apresenta um erro interno de rota que impossibilita a obtenção da requisição de pets do usuário e retornando Error 404.
Ex: .../users/1/pets

Esse problema provavelmente se deve a biblioteca usada não fornecer suporte para essa rota customizada e será criada uma nova issue para corrigir esse problema utilizando outros meios em breve.

</details>

2024-05-30 00:47 UTC, DominMFD reviewed
Ta faltando a Api de Pets

2024-05-30 13:06 UTC, nicolasfreitas-dev commented
> Ta faltando a Api de Pets

A API de Pets ficou incluída dentro da API de Users. Eu tinha feito separado, mas o Alê recomendou que ela ficasse dentro mesmo

2024-06-03 19:30 UTC, Alecell requested changes

2024-06-03 19:30 UTC, Alecell commented on db.json
EOF

2024-06-05 13:08 UTC, DominMFD approved these changes

2024-06-05 21:34 UTC, Alecell approved these changes

2024-06-05 22:45 UTC, merged