Issue 251
devhatt/pet-dex-frontend pull request #256
Opened 2024-05-30 19:14 UTC by muritadb

Closes #251

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Estruturação do Projeto para ser uma SPA

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/devhatt/pet-dex-frontend/assets/19556950/9fdd9fe7-07a4-403b-985f-b5b8194b806f)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Alterei a Home para Pages e dentro Components para layouts.
</details>

2024-06-03 15:08 UTC, diogocaronte approved these changes

2024-06-04 11:54 UTC, Alecell requested changes
Ficou ao contrário acho, não deveria ser um `layout` que possui `pages`? Um layout seria um formato de página, um formato de página tem várias paginas.

No fim podemos ter vários layouts diferentes, cada um com várias possibilidades de páginas.

Pensa que o layout é uma estrutura da página em si e a página e o conteúdo que será exibido na estrutura

2024-06-04 11:54 UTC, Alecell commented on src/pages/index.html
Vamos ficar com os 2 `index.html`? Não me parece correto

2024-06-04 11:54 UTC, Alecell commented on src/pages/index.js
>  import initializeScrollable from './utils/scrollable-sidemenu';
Prefira deixar o import do `scss` sempre no fim das importações

2024-06-04 11:54 UTC, Alecell commented on src/pages/utils/scrollable-sidemenu.js
Esse cara faz parte do `utils` do layout que o usa, no caso teriamos algo como

**layouts** folder -> **PetDexApp** folder -> utils -> scrollable-sidemenu

Justamente pq esse módulo do scrollable-menu se aplica apenas a esse layout

2024-06-04 12:05 UTC, Alecell requested changes
Dentro de cada `layout` vamos ter uma pasta chamada `components`, esses `components` definem componentes especificos do layout, dentro de `layout` tambem há uma pasta chamada `pages`

`SideMenu` e `Navigation` são componentes do layout `PetDexApp`
`NoPetRegisteredPage` é uma página

Valendo dizer, vamos padronizar essa nomenclatura. A partir de agora tudo que for página não terá mais o suffixo `Page`, saberemos oque é página ou não decorrente de estar dentro da pasta `pages`!

![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/8924c077-ee37-4a8c-8e3e-63037858fada)

2024-06-04 12:05 UTC, Alecell commented on src/pages/images/pet-dex.svg
Essas imagens filhas direta de `pages` que no caso precisa ser alterada para `layouts` precisa ser repensada um pouco.

Aqui nesse nível devemos ter apenas pastas que representem layouts e coisas que lidam de forma generica com layouts, no fim vamos acabar tendo em sua maioria apenas pastas que representem possibilidades de layouts!

Sobre a pasta `images`, se essas sao imagens que podem ser usadas em qualquer `layout` entao essa pasta `images` deve estar um nivel a cima, filha de `src`, se essas imagens se aplicam apenas ao layout `PetDexApp` entao dela deve esta um nivel a dentro, dentro da pasta que ainda nao existe `PetDexApp`

2024-06-10 22:21 UTC, muritadb commented on src/pages/index.html
removido index.html da Home

2024-06-10 22:38 UTC, muritadb commented on src/pages/images/pet-dex.svg
a pasta images ficou no diretorio SRC

2024-06-10 22:44 UTC, muritadb commented on src/pages/index.js
>  import initializeScrollable from './utils/scrollable-sidemenu';
import order fixed

2024-06-10 22:45 UTC, muritadb commented on src/pages/utils/scrollable-sidemenu.js
adjust structure

2024-06-10 22:49 UTC, muritadb commented
![image](https://github.com/devhatt/pet-dex-frontend/assets/19556950/bf959e6d-e6c8-41d3-af1c-894c22c70f0d)

Bom a estrutura ficou dessa forma:
Layouts - para cada layout do projeto
PetDexApp - layout existente
PetDexApp -> Components - componentes utilizados nesse layout
PetDexApp -> pages - variações dessa pagina 
Utils - componentes uteis do layout

2024-06-11 21:49 UTC, Alecell approved these changes

2024-06-11 22:46 UTC, merged