feat: create pet avatar component
devhatt/pet-dex-frontend pull request #261
Opened 2024-06-10 00:13 UTC by nathalia-84

Closes #231 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>
Create Pet Avatar component and display it in Home.
<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
   [feat: create pet avatar component](https://github.com/devhatt/pet-dex-frontend/commit/3c0d4fbf66993a9fbfe9e96bf557fb436c15fe2b)
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ x ] Issue linked
- [ x ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-06-10 12:10 UTC, PiluVitu requested changes

2024-06-10 12:10 UTC, PiluVitu commented on src/home/components/SideMenu/index.js
> +  ];
Isso é realmente para estar assim ?

2024-06-10 21:46 UTC, nathalia-84 commented on src/home/components/SideMenu/index.js
> +  ];
vou usar o mock da api, quando eu estava desenvolvendo não estava pronto ainda

2024-06-11 21:48 UTC, nathalia-84 commented on src/home/components/SideMenu/index.js
> +  ];
Pilu, eu vou ter que deixar assim por porque o serviço para usar o mock da API ainda não foi feito.

2024-06-12 12:01 UTC, DominMFD requested changes

2024-06-14 12:08 UTC, Alecell requested changes
Os avatares ainda estào com o underline! Precisamos tirar

Ta faltando resolver o caso de mais de 3 pets também, ele precisa ficar um em baixo do outro conforme conversamos e por enquanto simplesmente stackar as linhas

2024-06-14 12:08 UTC, Alecell commented on src/stories/PetAvatar.stories.js
> +    const $container = document.createElement('div');
Coloca um limite na largura dessa `div` inline mesmo pra limitar o tamanho do card no storybook

2024-06-14 12:08 UTC, Alecell commented on src/components/PetAvatar/index.scss
> +    font-weight: fonts.$regular;
Da uma revisadinha nessa parte, tem bastante propriedade que não precisa tipo o `height`, `min-height` e etc, da uma olhadinha, sempre vamos evitar propriedades que nao tem efeito!

2024-06-14 12:16 UTC, DominMFD commented on src/components/PetAvatar/index.js
> +  },
Então ta bom, ta certinho

2024-06-16 19:24 UTC, nathalia-84 commented
Comentários resolvidos!

2024-06-17 13:47 UTC, DominMFD approved these changes

2024-06-17 14:00 UTC, DominMFD commented
Seria legal vc ver com o Eliabe um hover para o seu componente, mas ele ta bom, pra mim ta aprovado, parabéns!!!

2024-06-17 14:23 UTC, PiluVitu approved these changes

2024-06-19 16:41 UTC, nathalia-84 commented
> Seria legal vc ver com o Eliabe um hover para o seu componente, mas é so uma sugestão, ele ta bom, pra mim ta aprovado, parabéns!!!

Hover adicionado!

2024-07-08 11:14 UTC, nathalia-84 commented
Comentários resolvidos!

2024-07-11 12:26 UTC, DominMFD approved these changes

2024-07-12 14:35 UTC, Alecell requested changes
Só to achando o component no storybook meio estranho ainda x.x

2024-07-17 23:07 UTC, nathalia-84 commented
@Alecell, corrigi aquilo que conversamos ainda a pouco, a correção não quebrou o componente

2024-07-24 12:12 UTC, Alecell approved these changes

2024-07-24 13:24 UTC, merged