feat: petvetpage tests
devhatt/pet-dex-frontend pull request #264
Opened 2024-06-11 20:03 UTC by juliaam

Closes #260 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Testes feito para a página ded petvet

</details>

<details open> 
  <summary>
    <b>Visual evidences
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/a0e51e21-bfad-49b3-834e-8547d83dd595)

</b>
  </summary>

</details>

- [ x ] Issue linked
- [ x ] Build working correctly
- [ x ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Foi necessário alterar o vaccine e vaccinegroup, pq apesar de estar funcionando na tela normalmente, o teste não aceitava o modo como estava sendo feito pois não era a ideal
</details>

2024-06-12 10:48 UTC, Alecell requested changes

2024-06-12 10:48 UTC, Alecell commented on src/home/components/PetVetPage/petVetPage.spec.js
> +    expect(callBackEmit).toHaveReturnedWith(formExpected);
Usar aqui um `toHaveBeenCalledWith`, nesse caso vc ta verificando apenas se a sua função foi chamada com o argumento esperado e é isso que vc espera de comportamento do `listen`, ai vc valida se ele foi chamado com os argumentos esperados e perfeito, é isso que queremos

Tanto que esse seu teste tem até um falso positivo nele, no caso, vc ta usando o `formExpected` como retorno da função callback, mas oq queremos é que o `formExpected` venha como argumento da função callback para que seja possivel pegar os dados do form atravez do evento, caso o contrario teriamos um problema

2024-06-12 10:48 UTC, Alecell commented on src/home/components/PetVetPage/petVetPage.spec.js
> +    expect(button.innerHTML === 'Concluir').toBeTruthy();
Não precisa verificar o texto nele, no maximo verifica se existe algum texto, mas o texto em si não precisamos verificar, acaba sendo um teste sem muito valor

2024-06-12 10:48 UTC, Alecell commented on src/home/components/PetVetPage/petVetPage.spec.js
Teste de renderização pode ser apenas 1 teste que vc verifica se os cards, textos, botão foram renderizados corretamente

Os testes de vacinas podem ser um novo describe e lá faz todos os testes de vacina, se renderizou enviando vacinas, se renderizou com nenhuma vacina

Faltou os testes de emissão com dados validos nos campos de radio e validar se tão sendo enviados certinho, isso pode ser outro describe com algumas validações, inclusive bobear vacilamos no componente antes, ele não deveria poder emitir sem a pessoa preencher o vacinado e o cuidado especial, é valido colocar uma validação nele

2024-06-16 03:52 UTC, Alecell requested changes
Precisamos conversar sobre os testes!

2024-06-16 03:52 UTC, Alecell commented on src/home/components/PetVetPage/index.js
> +    .setAttribute('data-testid', `${name}-${text.toLowerCase()}`);
Vamos sempre evitar usar testid, tente pegar o elemento atravez de outro meio

2024-06-16 03:52 UTC, Alecell commented on src/home/components/PetVetPage/index.js
> +      form.isNeutered = text === 'Sim' ? value : !value;
Precisa que seus `radio` sejam controlados pelo seu `value` e não pelo texto. O `value` pode ser o mesmo valor do texto, mas no caso talvez um `true`/`false` seja o mais adequado

2024-06-16 03:52 UTC, Alecell commented on src/home/components/PetVetPage/index.js
> +    }
Lembre-se que `undefined`, `null`, `false`, `''` e `0` são todos _falsy_ values, então podemos simplificar esse `if`

```suggestion
    if (!form.isSpecialCare || form.isNeutered) return;
```

2024-06-16 03:52 UTC, Alecell commented on src/home/components/PetVetPage/petVetPage.spec.js
> +    expect(button.innerHTML).toBeTruthy();
To sentindo que basta a gente verificar se existe algum elemento renderizado na página e isso seria o suficiente, não sei se faz sentido testar se cada coisa ta na página, até pq isso deixaria as coisas um pouco ruins de escalar no futuro, consegue fazer uma verificação mais simples? Do tipo se o container principal foi renderizado?

2024-06-23 16:56 UTC, Alecell requested changes
Só coisa de teste

2024-06-23 16:56 UTC, Alecell commented on src/layouts/app/pages/PetVet/index.spec.js
> +    it('confirms if the neutering selection is correct', async () => {
Oq correto é?

Correto é uma palavra abstrata, seu teste esta verificando se o neutering foi clicado no not neutered e é isso que a descrição do seu teste deve dizer!

Inclusiva não precisa checar se o true não ta selecionado, acredito que esse possa ser um outro teste de não permitir que 2 itens estejam selecionados ao mesmo tempo

2024-06-23 16:56 UTC, Alecell commented on src/layouts/app/pages/PetVet/index.spec.js
> +    it('confirms if the special care selection is correct', async () => {
Aqui novamente, `correct` não significa nada, precisamos que a descriçào do teste esteja especifica, no caso com o falso marcado quando for clicado

2024-06-23 16:56 UTC, Alecell commented on src/layouts/app/pages/PetVet/index.spec.js
> +    it('renders without vaccines passed', () => {
Aqui acredito que da pra melhorar, algo como `renders without vaccines list` ou algo assim, passed geralmente não tem a conotação que vc quer dar, é geralmente de quando algo passou, seja por um processo ou coisa assim, mas vc ta usando no sentido de repasse e ai o passed é estranho, não sei nem se ta certo hm

2024-06-23 16:56 UTC, Alecell commented on src/layouts/app/pages/PetVet/index.spec.js
> +    it('renders with vaccines passed', () => {
Aqui a mesma coisa do de cima

2024-06-23 16:56 UTC, Alecell commented on src/layouts/app/pages/PetVet/index.spec.js
> +      it('emits the form data when every field is passed', async () => {
`... every field is validated`

2024-06-23 16:56 UTC, Alecell commented on src/layouts/app/pages/PetVet/index.spec.js
> +      it('does not emit the form data when radios are not check', async () => {
Aqui era valido ter 2 ou 3 testes diferentes, validar se quando apenas neutered ou quando special care não estao marcados e por fim, validar se quando ambos estao desmarcados ele ainda nao passa

2024-06-26 13:18 UTC, DominMFD approved these changes
Seus testes ta mo bem estruturado, muito bom, parabéns

2024-07-03 13:08 UTC, Alecell approved these changes

2024-07-03 13:10 UTC, merged