Issue 263 - Atualizar componente TextInput
devhatt/pet-dex-frontend pull request #266
Opened 2024-06-14 16:34 UTC by jessicasantosb

Closes #263

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Add functionality to toggle the visibility of the TextInput field and implement this feature in the LoginForm

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![Captura de tela 2024-06-14 125909](https://github.com/devhatt/pet-dex-frontend/assets/125924091/7bfd071b-0048-485a-afeb-d97d678910df)
![Captura de tela 2024-06-14 125824](https://github.com/devhatt/pet-dex-frontend/assets/125924091/4b0b6ca4-c460-4ecc-9fbb-027aa68a1b85)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-06-17 11:52 UTC, Alecell requested changes
O icone precisa ocupar um espaço "real" no input se não vai acontecer de o texto e o icone ficarem sobrepujados. Talvez a melhor solução pra isso é ter um container em volta do input cujo tem a bordinha e talz, ai dentro tem o input e o possivel icone
**O problema**
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/cd23f77f-f412-409d-88cc-404cd29e5666)

**Possivel solução**
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/468e4291-3f9f-4683-b078-40d70dc83ff0)

Pode me pingar se tiver dúvida!

2024-06-17 11:52 UTC, Alecell commented on src/components/TextInput/index.js
>    // eslint-disable-next-line no-undef
Consegue remover esse lint ignore?

2024-06-17 11:52 UTC, Alecell commented on src/components/TextInput/index.js
> +  },
Não sei se entendi essa função ela chama `getType`, mas está setando o type, era pra ser `setType`?

2024-06-17 11:52 UTC, Alecell commented on src/components/TextInput/index.js
> +  this.getType(placeholder);
Porque o `placeholder` ta sendo enviado nessa função, pelo que a função faz isso não me parece certo, consegue me explicar?

2024-06-17 11:52 UTC, Alecell commented on src/components/TextInput/index.js
> +    <button type="button" class="input-text-container__icon hidden" data-select="show-text">
A gente ta usando `BEM`, ai nossas classes precisam seguir um certo padrão, no caso do `hidden` ele precisa ser `input-text-container_icon--hidden` pq o `--` é um modificador de classe

Pode ler mais sobre aqui: https://getbem.com/

2024-06-17 11:52 UTC, Alecell commented on src/components/TextInput/index.scss
> +  }
Vc ta usando o `stylelint`? A gente usa um linter de css tambem pra aplicar algumas regras dos nossos estilos!

Acredito que não ta usando pq os estilos estão todos juntinhos ali na primeira classe e isso geralmente o stylelint pega

Se ja tiver instalado precisa configurar ele, falamos na daily sobre isso, é deboas!

2024-06-17 11:52 UTC, Alecell commented on src/components/TextInput/index.scss
> +    right: 10px;
Em geral eu digo pra nunca usar `px`, mas nesse caso em especifico é bem deboas usar por ser um icone dentro de um input, só mantem isso em mente, `px` em geral (não nesse caso) é má pratica!

2024-06-17 11:52 UTC, Alecell commented on src/components/TextInput/index.scss
> +    cursor: pointer;
Acredito que esses estilos vão mudar pra não ter mais o problema de um ficar por cima do outro!

2024-06-17 11:52 UTC, Alecell commented on src/components/TextInput/index.scss
> +    &.hidden {
Como faleu lá em cima, essa classe não ta seguindo o `BEM`, no caso ela precisaria estar assim

```suggestion
    &--hidden {
```

2024-06-17 12:23 UTC, DominMFD requested changes
Falta mudar o componente no Storybook também.

2024-06-17 16:08 UTC, diogocaronte requested changes

2024-06-17 16:08 UTC, diogocaronte commented on src/components/TextInput/index.js
> +  },
lembrar de emitir evento de troca de "tipo" também

2024-06-18 13:50 UTC, DominMFD requested changes

2024-06-18 13:50 UTC, DominMFD commented on src/components/TextInput/index.js
> +  },
só emitir o evento aqui da troca do type

2024-06-18 17:04 UTC, jessicasantosb commented on src/components/TextInput/index.js
> +  },
Seria inserir 'password' no método emit?

2024-06-19 12:29 UTC, DominMFD commented on src/components/TextInput/index.js
> +  },
Quase isso, não é necessariamente o `password`, seria a mudança do type. Na nossa aplicação precisamos emitir um evento quando mudamos o estado de um componente.

No seu caso vc pode colocar logo depois que vc faz a mudança do type um
```
this.emit('type:changed', type);
 ```
E dai vc tem que adicionar ele no arrai `events` la no começo do arquivo.

Qualquer dúvida pode me pingar no discord.

2024-06-19 13:20 UTC, DominMFD approved these changes
Pra mim ta bom, parabéns!!!

2024-06-19 15:23 UTC, diogocaronte approved these changes

2024-06-19 17:51 UTC, Alecell requested changes

2024-06-19 17:51 UTC, Alecell commented on src/components/TextInput/index.js
> +  'type:changed',
usar evento no imperativo `type:change`

2024-06-19 17:51 UTC, Alecell commented on src/components/TextInput/index.scss
Essa solução da sobreposição gera um outro problema, quando chegamos no fim do input não conseguimos ver os outros caracteres, vamos parear!

A solução é simples, mas exige um certo refactor!

2024-06-24 11:18 UTC, Alecell approved these changes

2024-06-24 11:19 UTC, merged