Issue 245
devhatt/pet-dex-frontend pull request #274
Opened 2024-06-22 16:06 UTC by Clerijr

Closes #245 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Adiciona o componente de alteração de senha

</details>

<details open> 
  <summary>
    <b>Visual evidences ![image](https://github.com/devhatt/pet-dex-frontend/assets/67716586/e0d375d7-37fc-4942-9fba-b7d37c8832c4)</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Está pendendo o botão de visualizar senha
</details>

2024-06-24 11:44 UTC, DominMFD requested changes

2024-06-24 11:44 UTC, DominMFD commented on src/components/ChangePassword/index.js
> +  });
O componente de TextInput foi mergeado, atualize a branch e use ele do jeito atualizado.

2024-06-24 11:44 UTC, DominMFD commented on src/components/ChangePassword/images/eye-slash.svg
Depois que começar a usar o TextInput atualizado, não vai precisar desse icon, ai pode excluir

2024-06-24 11:44 UTC, DominMFD commented on src/components/ChangePassword/index.js
> +  });
Tem muita coisa acontecendo aqui, acho que você pode transformar algumas coisas em funções para melhorar a leitura do código

2024-06-24 11:44 UTC, DominMFD commented on src/components/ChangePassword/index.js
> +      confirmPasswordInput.inputError();
Aqui por exemplo, poderia ser facilmente ser uma função

2024-06-24 11:45 UTC, Alecell requested changes
Só precisamos dar uma revisada boa no BEM usado no CSS

Aumenta um pouco o `z-index` do componente no storybook pq ta aparecendo isso aqui 
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/00e8fd03-e353-48a5-924d-542c4bf4cc99)

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.js
> +      $passwordErrorMessage.innerText = 'Senha inválida';
O texto `Senha inválida` pode ser colocado direto no `span` no html, não precisa colocar o conteúdo apenas quando ele for aparecer! Ai basta esconder com CSS e exibir quando aplicar a classe show-error, ela teria a unica responsabilidade de dar um `display: block`

Isso vale pra todos os erros!

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.js
> +        'As senhas informadas não coincidem';
Acredito que isso aqui possa ser outro campo de erro, já com esse texto, em baixo do campo de repetir a senha e exibe ele quando necessário! Tambem não é interessante colocar 2 erros com a mesma mensagem em baixo de cada 1, podemos simplificar!

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.js
> +      $confirmPasswordErrorMessage.classList.remove('show-error');
A remoção do erro idealmente deveria acontecer no ato de digitar, no caso, se a pessoa alterar algum dos campos com erro ja remover os erros, remover apenas quando poder enviar da uma impressão  de que a pessoa teria que clicar no botao de enviar mesmo com os campos exibindo erro, talvez isso não seja ideal

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.js
> +    let validConfirmPassword = true;
Pelo menos por enquanto podemos ter só uma variavel tipo "allValid" ou coisa assim ai podemos ter apenas 1 variavel que determina se podemos ou não passar, por enquanto não precisamos dessas 3 verificações

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.js
> +    }
evitar `if`/`else`, prefira ternário

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.js
> +      confirmPasswordInput.selected.get('input-text').value;
Talvez não seja ideal validar os 3 campos juntos, acredito que essa função poderia receber um `data-select` como parametro, ai pegar apenas aquele campo e entao valida-lo

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.js
> +    },
Essa camada do componente são funções feitas para serem usadas por quem usa o componente, no caso essas funções `comparePasswords` e `validatePasswords` são funções utilitarias, assim é melhorar declararmos elas entre o html e a inicialização do componente pra não expor métodos desnecessários para o usuário do componente

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.scss
> +    justify-content: start;
Não precisamos dessa propriedade

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.scss
> +    }
Atualizar o componente de input com a versão da @jessicasantosb

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.scss
> +  }
Aqui parece que o BEM morreu, precisamos manter o BEM!

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.scss
> +    padding-inline-start: 2rem;
Vamos evitar o uso de propriedades lógicas!

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.scss
> +      border: unset;
Prefira usar `0` ou `none`

2024-06-24 11:45 UTC, Alecell commented on src/components/ChangePassword/index.scss
O `font-size` dos inputs devem ser `16px` na base

2024-07-11 12:41 UTC, DominMFD requested changes

2024-07-11 12:41 UTC, DominMFD commented on src/components/ChangePassword/index.js
> +const events = ['change-password'];
Aqui nos eventos a gente ta usando um padrão no projeto de `item:ação`, no seu caso ficaria `password:change`

2024-07-11 12:41 UTC, DominMFD commented on src/components/ChangePassword/index.js
> +      this.emit('change-password');
ai muda aqui também

2024-07-11 12:41 UTC, DominMFD commented on src/components/ChangePassword/index.scss
> +  background-color: rgb(255, 255, 255);
usa nosso arquivo de cores, se não tiver essa cor pode adicionar, mas é branco, acho que tem branco né possível

2024-07-23 12:37 UTC, DominMFD requested changes

2024-07-23 12:37 UTC, DominMFD commented on src/components/ChangePassword/index.js
> +  };
essa função é uma função utilitária, da pra colocar ela fora do escopo do componente(entre o html e o componente) ou ate numa pasta utils dentro da pasta do componente

2024-07-23 12:37 UTC, DominMFD commented on src/components/ChangePassword/index.scss
> +  line-height: fonts.$lg;
o line-height deve ser um número pq dai ele pega baseado no font-size e não acontece isso ó 
![image](https://github.com/user-attachments/assets/e781b6be-5f91-4758-bcb2-4dd0af6e11a6)
Nessa parte o line-height é menor mas no seu ta a mesma coisa dos títulos, que deveria ser maior, entendeu?

2024-07-23 12:40 UTC, DominMFD commented
Olha eu não sei se você conversou com alguém sobre isso mas seu componente ta diferente do do Figma

seu componente: 
![image](https://github.com/user-attachments/assets/7369f746-3035-4aaf-857c-1731aa5f005e)

Figma:
![image](https://github.com/user-attachments/assets/bdd9a49d-27a2-4fef-b3fd-a7312943ae63)

particularmente eu gostei mais do seu com as informações em baixo, mas não sei, só vi que ta diferente mesmo e o botão no figma ta lá em baixão.

2024-07-23 12:43 UTC, DominMFD commented
Outra coisa, a ultima eu prometo, quando eu passo o mouse em cima do botão ele fica maior que o componente e cria um scroll no seu componente por causa do efeito de hover que ele tem, aqui ó
![image](https://github.com/user-attachments/assets/e021b231-0538-4742-8c44-910bdd9c1714)

É só vc colocar um padzinho no componente que arruma isso.

2024-07-23 15:35 UTC, Alecell requested changes

2024-07-23 15:35 UTC, Alecell commented on src/components/ChangePassword/index.js
> +          </form>
Não de esse tab todo aqui, apenas 1 nível a frente para html e vai avançando com os blocos

2024-07-25 10:07 UTC, DominMFD requested changes

2024-07-25 10:07 UTC, DominMFD commented on src/components/ChangePassword/index.scss
> +  line-height: 20px;
Acho que vc n entendeu aqui, o `line-height` é bom ser um número, tipo sem unidade de medida, um numero mesmo, pq dai ele é baseado no `font-size` do elemento, é até bom por questões de acessibilidade. No seu caso o valor seria 1.4, mas você pode colocar 1.5 que é o mínimo que a W3 recomenda pra acessibilidade. Isso é bom para pessoa que tem alguma dificuldade com leitura, tipo dislexia, e também ele performa melhor em questões de zoom na página/elemento. 

https://www.w3.org/WAI/WCAG21/Understanding/text-spacing.html

2024-07-25 10:07 UTC, DominMFD commented on src/components/ChangePassword/index.scss
> +  padding: 0 5px;
aqui poderia ser `rem` em vez de pixel

2024-07-25 12:01 UTC, Alecell approved these changes
Só arrumar as paradas do @DominMFD e GG!

2024-07-25 13:58 UTC, DominMFD approved these changes

2024-07-25 14:01 UTC, merged