feat: add text area component
devhatt/pet-dex-frontend pull request #276
Opened 2024-06-24 18:31 UTC by Mathh19

Closes #250 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Desenvolver um componente textarea que se expande de acordo com o conteúdo de texto inserido, ele será usado nas páginas da aplicação.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

 ![image](https://github.com/devhatt/pet-dex-frontend/assets/67031321/7a0fde2b-7f94-4d3c-a5f7-be84709c4026)

 ![image](https://github.com/devhatt/pet-dex-frontend/assets/67031321/0a6add36-002f-49aa-a885-a598f39c1caa)

</details>

2024-06-25 12:33 UTC, DominMFD requested changes

2024-06-25 12:33 UTC, DominMFD commented on src/components/TextArea/index.scss
> +      color: rgb(255, 255, 255);
Usa o arquivo de cor, se não tiver essa cor la pode criar.

2024-06-25 12:44 UTC, DominMFD commented
Edita seu PR, na frente do Closes coloca #da sua task por favor, pra poder linkar

2024-06-26 12:53 UTC, DominMFD approved these changes
Pra mim ta bom, amassou

2024-06-26 22:05 UTC, diogocaronte requested changes

2024-06-26 22:05 UTC, diogocaronte commented on src/components/TextArea/index.js
> +  autoResize() {
Não acho que esse tipo de método deva ser publico.
Se for deixar público renomeie para onResize() que é o padrão para callback que estamos usando

2024-06-26 22:05 UTC, diogocaronte commented on src/components/TextArea/index.scss
precisa arrumar as classes de acordo com oque pedi

remover o "container" que é redundante
e arrumar o BEM

2024-06-26 22:05 UTC, diogocaronte commented on src/components/TextArea/index.scss
> +    font-family: 'Poppins', sans-serif;
adicione a font family no arquivo de fonts e use a variavel

2024-06-26 22:05 UTC, diogocaronte commented on src/stories/TextArea.stories.js
> +  },
```suggestion
  argTypes: {
    name: { control: 'text', default: '' },
    placeholder: { control: 'text', default: '' },
    maxLength: { control: 'number', default: 524288 },
    required: { control: 'boolean', default: false },
  },

```

2024-07-02 17:07 UTC, Alecell commented on src/components/TextArea/index.js
> +  setMaxLength(maxLength = 524288) {
Porque o max default é esse numero? Não seria melhor ser `infinity`?

2024-07-02 17:07 UTC, Alecell commented on src/components/TextArea/index.js
> +    }
Acho que não precisamos desse `if`

2024-07-02 17:08 UTC, Alecell commented on src/components/TextArea/index.js
> +  setRequired(required = false) {
Acredito que o padrão deveria ser `true` e não `false`

2024-07-08 12:39 UTC, Alecell requested changes

2024-07-08 12:39 UTC, Alecell commented on src/components/TextArea/index.js
> +  },
Não tinhamos conversado que usar o infinity aqui seria ruim?

Acredito que pra não ter limite teriamos que não especificar o máximo. Oq podemos fazer é o seguinte:

```js
if (!maxLength) {
  this.selected.get('textarea').removeAttribute("max-length");
}

this.selected.get('textarea').maxLength = maxLength;
this.emit('maxLength:change', maxLength);
```

Assim se não especificarmos ele trata como "infinite", caso o contrario podemos especificar o tamanho

2024-07-08 15:07 UTC, Mathh19 commented on src/components/TextArea/index.js
> +  },
Sim, mas acho que o código pode ficar ainda mais simples, acredito que o tamanho máximo só deve ser adicionado se especificado.
Atualmente o código ta assim pois tínhamos decidido do maxLength ser por padrão undefined, o código atual tem essa validação na linha 32 se não me engano.
```if (maxLength) this.setMaxLength(maxLength);```
acho que poderia remover essa verificação e adicionar no método de adicionar o tamanho máximo.
Minha sugestão seria essa 
```
setMaxLength(maxLength) {
    if (maxLength) {
      this.selected.get('textarea').maxLength = maxLength;
      this.emit('maxLength:change', maxLength);
    }
  }
  ```
 Assim só é adicionado tamanho máximo se especificado.

2024-07-08 15:23 UTC, Alecell commented on src/components/TextArea/index.js
> +  },
Isso impede o componente de alterar por qualquer motivo que seja o limite de caracteres, tipo eu não tenho nenhum meio de especificar que não tem limite, eu sempre sou obrigado a colocar um limite

O problema disso é que, suponhamos que um tamanho foi especificado e agora, por qualquer motivo que seja, queremos deixa-lo sem limite. Isso não é mais possivel de alterar pq não existe nenhum valor que permite mudar de um valor finito para infinito

2024-07-08 15:47 UTC, Mathh19 commented on src/components/TextArea/index.js
> +  },
Tem razão, não tinha pensado nesse caso.

2024-07-09 13:41 UTC, Alecell requested changes

2024-07-09 13:41 UTC, Alecell commented on src/components/TextArea/index.js
> +    this.emit('maxLength:change', maxLength);
Isso ta funcionando?

Tipo, do jeito q ta, se eu nao especificar um limite o atributo é removido e, logo em seguida, colocado de novo com um `maxLength` como `undefined` e então eu emito o `undefined`

Acredito que isso deva ser assim 

```js
const $textArea = this.selected.get('textarea');

if (maxLength) $textArea.maxLength = maxLength 
else $textArea.removeAttribute('maxlength');

this.emit('maxLength:change', maxLength ?? Infinity);
```

2024-07-09 15:43 UTC, Mathh19 commented on src/components/TextArea/index.js
> +    this.emit('maxLength:change', maxLength);
Verifiquei porque a solução estava funcionando, e é pela verificação que contém na linha 32.
```
if (maxLength) this.setMaxLength(maxLength);
```
testei removendo ela e realmente faz com que o valor do limite chegue como undefined caso não seja especificado.

2024-07-09 18:19 UTC, Alecell approved these changes

2024-07-09 18:27 UTC, merged