feat: petregister tests
devhatt/pet-dex-frontend pull request #280
Opened 2024-07-10 17:51 UTC by juliaam

Closes #225 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação de testes para a página de PetRegister

</details>

<details open> 
  <summary>
    <b>Visual evidences:
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/7463ec82-ca47-4a7e-93bb-c82faaddbf96)

</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ x ] Issue linked
- [ x ] Build working correctly
- [ x ] Tests created
</details>

2024-07-11 18:28 UTC, Alecell requested changes

2024-07-11 18:28 UTC, Alecell commented on src/layouts/app/pages/PetRegister/index.spec.js
> +    it('does not emit the form data when does not have card select', async () => {
`does not happen when theres no card selected`

2024-07-11 18:28 UTC, Alecell commented on src/layouts/app/pages/PetRegister/index.spec.js
> +    it('emits the form data when every field is validated', async () => {
`form data when every field is validated`

2024-07-15 15:18 UTC, DominMFD approved these changes
Ta amassando nos testes

2024-07-16 12:08 UTC, Alecell requested changes

2024-07-16 12:08 UTC, Alecell commented on src/layouts/app/pages/PetRegister/index.spec.js
> +    it('does not happen when theres no card selected when theres no card selected', async () => {
Ta escrito `when theres no card selected` duas vezes

2024-07-16 14:48 UTC, juliaam commented on src/layouts/app/pages/PetRegister/index.spec.js
> +    it('does not happen when theres no card selected when theres no card selected', async () => {
DOUBLE CLICK

2024-07-16 21:34 UTC, Alecell approved these changes

2024-07-16 21:34 UTC, merged