feat: inserido textarea na PetVetPage
devhatt/pet-dex-frontend pull request #281
Opened 2024-07-11 21:04 UTC by gustavogularte

Closes #272 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Inserido textarea para cuidados especiais na página petvet

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![textarea](https://github.com/devhatt/pet-dex-frontend/assets/98916022/a2667c55-4ea4-4ca5-b916-d6ee73bf585d)

![340405653-e45d6dc8-a3e0-4e76-b196-b2e448d21a0d](https://github.com/devhatt/pet-dex-frontend/assets/98916022/e4b0e0ba-d1a4-4483-90e7-48dfc8b2d5eb)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

2024-07-12 12:16 UTC, DominMFD requested changes
![image](https://github.com/user-attachments/assets/6cc970de-2039-49c4-806a-71493014d508)

O imput ta muito colado com o componente de cima, se vc for aqui no [Figma](https://www.figma.com/design/ZQ5mPH1j2snuiVpkp68EI5/PetDex?node-id=107-5&t=dYIR7LWvqCvpzkVq-0) vai perceber que tem um espaçamento entre eles, ajusta isso

2024-07-15 13:49 UTC, DominMFD approved these changes

2024-07-15 13:50 UTC, DominMFD commented
Atualiza a branch

2024-07-15 22:09 UTC, diogocaronte approved these changes

2024-07-16 13:36 UTC, merged