Issue 120 - serviço de raças
devhatt/pet-dex-frontend pull request #282
Opened 2024-07-12 21:57 UTC by juliaam

Closes #120 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Função de pegar todas as raças através da função de GetBreeds

</details>

<details open> 
  <summary>
    <b>Visual evidences:
![image](https://github.com/user-attachments/assets/a749f3db-5b46-4879-a2cf-854343cf07e4)

</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ x] Issue linked
- [x ] Build working correctly
- [ ] Tests created
</details>

2024-07-15 13:22 UTC, DominMFD requested changes

2024-07-15 13:22 UTC, DominMFD commented on src/services/breeds.js
> +const url = 'http://localhost:3000';
Seria interessante colocar essa url em um arquivo a parte para que todos os services usem ela.

2024-07-15 13:22 UTC, DominMFD commented on src/services/breeds.js
> +      }
Erros em inglês

2024-07-15 13:22 UTC, DominMFD commented on src/services/breeds.js
> +      return error;
Aqui também, erros em inglês

2024-07-15 13:22 UTC, DominMFD commented on src/services/breeds.js
> +        throw new Error('Ocorreu um erro na requisição');
`Ocorreu um erro na requisição` é muito vago, precisamos de mais informações, por exemplo, qual o erro. Dito isso o response tem 2 propriedades que você pode usar nessa informação, o `response.status` que retorna o status code da chamada e o `response.statusText` que retorna a mensagem referente ao status code. Eu particularmente usaria o `response.status` pois acho o status code uma informação relevante.

Se quiser saber mais sobre o response: https://developer.mozilla.org/pt-BR/docs/Web/API/Response

2024-07-15 21:50 UTC, Alecell requested changes

2024-07-15 21:50 UTC, Alecell commented on package.json
Remover o dependency mock-api e mover o json-server para devDependency. Downgrade do vite??

2024-07-15 21:50 UTC, Alecell commented on src/services/breeds.js
> +/* eslint-disable no-console */
Desabilitar a regra de no-console para todos os arquivos dentro da pasta sevices

2024-07-15 21:50 UTC, Alecell commented on src/services/breeds.js
> +        });
Criar uma task para definir e documentar formato de erro de serviço

2024-07-15 21:50 UTC, Alecell commented on src/services/breeds.js
> +      return await response.json();
Pode remover o await

2024-07-15 21:50 UTC, Alecell commented on src/services/breeds.js
> +  getBreeds: async () => {
BreedService // getBreeds()

getAll
list

2024-07-15 21:50 UTC, Alecell commented on src/services/api.js
Atualiza no do shot tambem

2024-07-16 12:08 UTC, DominMFD approved these changes

2024-07-18 12:20 UTC, Alecell approved these changes

2024-07-18 12:20 UTC, merged