feat: login service
devhatt/pet-dex-frontend pull request #284
Opened 2024-07-18 03:22 UTC by gustavogularte

Closes #241

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criado o serviço de login do usuário

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

</details>

2024-07-18 14:21 UTC, juliaam requested changes

2024-07-18 14:21 UTC, juliaam commented on src/services/login/loginService.js
coloque esse arquivo direto no /services, ficando src/services/loginService.js.

2024-07-18 14:21 UTC, juliaam commented on src/services/login/loginService.js
> +  const url = 'http://localhost:3000/login';
importe essa url do arquivo api.js lá em cima

`import {url} from './api'` (esse caminho após alterar o diretório dele)

2024-07-18 14:21 UTC, juliaam commented on src/services/login/loginService.js
> +      return errorResponse(error);
mesma coisa aqui, por que nao retornar o objeto direto? ao invés de chamar uma func?
```suggestion
return {
  success: true,
  token: data.token,
};
```

2024-07-18 14:21 UTC, juliaam commented on src/services/login/loginService.js
> +  return successResponse(data);
por que nao retornar o objeto direto? ao invés de chamar uma func?
```suggestion
 return {
    success: false,
    message: error.message,
  };
```

2024-07-19 10:53 UTC, DominMFD requested changes
Se eu não estou enganado, você teria que adicionar o login no mock da api tbm ne? se for ta faltando.

2024-07-19 10:53 UTC, DominMFD commented on src/services/loginService.js
> +      if (!response.ok) throw new Error('Erro ao fazer o login');
Erros em inglês

2024-07-19 10:53 UTC, DominMFD commented on src/services/loginService.js
> +        token: data.token,
aqui não precisaria desse await, ou como ta retornando só o token vc pode fazer uma desestruturação, seria algo do tipo 
```suggestion
      const { token } = await response.json();
      return {
        success: true,
        token: token,
```

ai precisaria do await

2024-07-22 12:46 UTC, Alecell requested changes

2024-07-24 23:02 UTC, DominMFD approved these changes

2024-07-24 23:02 UTC, merged