feat: routes fix
devhatt/pet-dex-frontend pull request #286
Opened 2024-07-18 20:02 UTC by RafaelLimaC

Closes #285 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-07-18 20:49 UTC, juliaam requested changes

2024-07-18 20:49 UTC, juliaam commented on src/layouts/app/components/SideMenu/index.js
> +          <li><a data-vanilla-route-link="spa" class="side-menu-content__menuitens" href="/settings"><img src="${configuracoes}" alt="configuracoes">Configurações</a></li>
tem que ajustar a formatação

2024-07-18 20:55 UTC, juliaam approved these changes

2024-07-18 20:55 UTC, juliaam commented on src/layouts/app/components/SideMenu/index.js
> +          <li><a data-vanilla-route-link="spa" class="side-menu-content__menuitens" href="/settings"><img src="${configuracoes}" alt="configuracoes">Configurações</a></li>
só ajustaria a formatação

2024-07-18 20:55 UTC, juliaam commented on src/layouts/app/components/SideMenu/index.js
> +          <li><a data-vanilla-route-link="spa" class="side-menu-content__menuitens" href="/settings"><img src="${configuracoes}" alt="configuracoes">Configurações</a></li>
```
<li>
  <a data-vanilla-route-link="spa" class="side-menu-content__menuitens" href="/">
    <img src="${meusPets}" alt="Meus Pets">Meus Pets
  </a>
</li>
```

2024-07-19 10:37 UTC, DominMFD approved these changes

2024-07-22 02:05 UTC, diogocaronte approved these changes

2024-07-24 12:27 UTC, Alecell requested changes
Só deixa pronto um exemplo do create accont pf!

2024-08-27 05:29 UTC, Luiginicoletti approved these changes
Po so ta faltando uma descricao do PR pra saber o que foi feito hahahah

2024-09-05 12:24 UTC, closed without merging