#issue 267 - implementação da listagem de dados pet via service no componente PetAvatar #issue-267
devhatt/pet-dex-frontend pull request #290
Opened 2024-08-02 21:16 UTC by EdiltonOliveira

Closes
#267 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

feat: implementação da listagem de dados pet via service no componente PetAvatar #issue-267

* Criação do arquivo dbSimulatorAPI.json para mock API json-server

* Downgrade json-server 1.0.0 para 0.17.4 para personalização de rota API

* Criação de arquivo routes.json para personalização da rota via json-server

* Implementação do userService.json para consumo da API mockada via json-server

* Alteração da URL de userService.js para atender a rota definida pelo BackEnd

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

![petdex_front2](https://github.com/user-attachments/assets/bd11ee26-c52f-4fe9-bbbf-e8cc3050db22)
![petdex_front1](https://github.com/user-attachments/assets/4bfd08ac-8ca3-46ff-8cff-d5bb50941285)

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
 Para a criação de um servidor API com personalização de rota equivalente ao backend, foi necessário usar uma versão anterior do pacote json-server, visto que a versão 1.0.0 não oferecia o recurso necessário para que ao acessar a rota http://localhost:3000/api/user/1/my-pets
</details>

2024-08-05 10:35 UTC, DominMFD reviewed
Bom dia, eu to com uma dúvida, a gente já tem um mock da API, pq criar outro? é só uma dúvida mesmo até pq a implementação ta certa, mas eu to confuso

2024-08-05 15:02 UTC, EdiltonOliveira commented
Bom dia, @DominMFD . Como o mock usados para renderizar o componente PetAvatar eram diferentes dos dados db.json, optei por preservar a estrutura original de db.json e criar uma mock que melhor estivesse alinhado a tabela pet_img. Essa é o primeiro pull request, então estou aguardando feedback para ver se a decisão foi boa ou não.    

Abaixo a tabela que melhor se alinha ao mock que estava sendo usado

![Captura de tela de 2024-08-05 11-49-36](https://github.com/user-attachments/assets/a64c7fb7-483a-4d5d-b6c6-c9eb8779f279)

O mock consumido no componente PetAvatar

![Captura de tela de 2024-08-05 11-56-55](https://github.com/user-attachments/assets/4d67277c-5779-41f1-a6dc-853424d6c5fa)

Também tomei a decisão levando em conta que a API do back será disponibilizado em breve, logo criei o `dbSimulatorAPI.json` junto com a versão json-server 0.17 para conseguir simulador a rota e o mock fazendo o mínimo de alterações possíveis . Caso seja necessário tabela única, é provável que o json-server não consiga simular um roteamento complexo que se encaixe em db.json
![Captura de tela de 2024-08-05 12-01-12](https://github.com/user-attachments/assets/9f596a7e-34dc-4aa6-88c1-f91f87196200)

2024-08-05 20:11 UTC, DominMFD commented
É, foi isso que eu pensei mesmo, vamos ver na daily hj com o Ale

2024-08-07 16:29 UTC, PiluVitu approved these changes
LGTM

2024-08-08 11:01 UTC, DominMFD requested changes

2024-08-08 11:01 UTC, DominMFD commented on src/services/userService.js
>          throw new Error('Ocorreu um erro na requisição');
Coloca só os erros em inglês e um console.log no catch, igual no método de login por favor

2024-08-08 15:37 UTC, EdiltonOliveira commented on src/services/userService.js
>          throw new Error('Ocorreu um erro na requisição');
As solicitação foram atendidas. Aguardando revisão.

2024-08-08 21:42 UTC, diogocaronte approved these changes

2024-08-09 11:41 UTC, DominMFD approved these changes

2024-08-09 11:44 UTC, merged