feat: add functionality to configure lateral spacing
devhatt/pet-dex-frontend pull request #292
Opened 2024-08-12 19:41 UTC by Mathh19

Closes #232

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Adicionar espaçamento lateral de forma configurável para visualização dos slides adjacentes.

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/user-attachments/assets/e42efac8-f848-452b-af99-ad4f27cf875f)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-08-13 11:22 UTC, DominMFD requested changes

2024-08-13 11:22 UTC, DominMFD commented on src/components/Sliding/index.js
> +  'padding',
No setSidePadding vc altera o padding do elemento ne? aqui poderia ser então padding:change

2024-08-13 11:22 UTC, DominMFD commented on src/components/Sliding/index.js
> +};
coloca essa função e a de cima em uma pasta utils dentro da pasta do componente, acho que fica melhor

2024-08-13 11:22 UTC, DominMFD commented on src/components/Sliding/index.js
> +    this.emit('padding', sidePadding);
ai aqui ficaria padding:change

2024-08-13 11:22 UTC, DominMFD commented on src/stories/Sliding.stories.js
Adiciona o outro modo do sliding aqui no stories, o sem o shuffleMode, para ter os dois

2024-08-13 21:37 UTC, Alecell requested changes

2024-08-13 22:40 UTC, Mathh19 commented on src/components/Sliding/index.js
> +  'padding',
> Acho inclusive que esse padding não deveria nem ser um evento, @Mathh19 pq é?

Faz sentido não ser, eu acabei me confundido, mas já alterei e aproveitei pra olhar novamente a doc do projeto pra evitar essa minha confusão do que deve ser evento, mals.

2024-08-15 00:35 UTC, Alecell requested changes

2024-08-15 00:35 UTC, Alecell commented on src/components/Sliding/index.js
> +  'padding',
Mas o `padding` ainda ta aqui como evento ;-;

2024-08-15 00:35 UTC, Alecell commented on src/components/Sliding/index.js
> +  sidePadding = 0,
Posso ta falando abobrinha, mas e se a gente não tivesse essa propriedade sidePadding e isso fosse feito por estilo?

2024-08-15 00:35 UTC, Alecell commented on src/components/Sliding/index.js
Acho que métodos específicos de modos especificos poderiam ficar em um arquivo especifico do modo, entao tipo o, setPadding, activeSlideShuffle, setShuffleMode e etc deveriam estar lá, se não pra cada modo que adicioanr o slide vai virando um monstrinho

2024-08-15 00:35 UTC, Alecell commented on src/components/Sliding/index.js
> +    } else {
Pq precisamos mudar o modo como o slider troca de slide decorrente do modo? Isso não deveria ser constante independente do modo?

2024-08-15 00:35 UTC, Alecell commented on src/components/Sliding/index.js
> +      this.emit('slide:previous', slides[this.slideIndex]);
Pq precisamos mudar o modo como o slider troca de slide decorrente do modo? Isso não deveria ser constante independente do modo?

2024-08-15 00:35 UTC, Alecell commented on src/components/Sliding/index.js
> +  },
Mover para outro arquivo

2024-08-15 00:35 UTC, Alecell commented on src/components/Sliding/index.scss
> +      width: 62%;
Porque 62%?

2024-08-15 00:35 UTC, Alecell commented on src/components/Sliding/index.scss
> +      left: 0;
Pq absolute? O.O

Isso não me cheira muito bem...

2024-09-09 10:52 UTC, DominMFD approved these changes

2024-09-09 10:52 UTC, DominMFD commented
Atualiza a branch

2024-09-09 11:38 UTC, Frompaje commented on src/components/Sliding/index.js
>      <div class="sliding__content" data-select="sliding-content">
melhor, não?
```js
<div class="slide" data-select="slide">
```

2024-09-09 15:02 UTC, Luiginicoletti approved these changes
Opa eai Mathzão, fiquei só com uma dúvida ali mas não é impeditivo pra mim, mandou muito! abraço!

2024-09-09 22:15 UTC, Mathh19 commented on src/components/Sliding/utils/activeSlideShuffle.js
> +    );
Opa Nico, é que o slides vem como uma HTMLCollection, então não consigo fazer o forEach aí resolvei com o Array.from(), não sei se seria um problema

2024-09-11 14:27 UTC, merged