feat: add user registration service
devhatt/pet-dex-frontend pull request #293
Opened 2024-08-13 20:16 UTC by JpBurgarelli

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Tinha que criar o serviço de registro para novos usuários utilizando os dados coletados pelo formulário do componente de registro. Esse serviço deve validar os dados fornecidos, realizar o cadastro do usuário e fornecer uma resposta sobre o sucesso ou fracasso.

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
  Preciso me informar a respeito do correto endpoint e se preciso criar testes.
</details>

2024-08-15 01:42 UTC, Alecell requested changes

2024-08-15 01:42 UTC, Alecell commented on src/services/registerService.js
> +    const response = await fetch(`${url}/naoSeiARota`, {
Arrota

2024-08-15 11:54 UTC, DominMFD requested changes

2024-08-15 11:54 UTC, DominMFD commented on src/services/registerService.js
A gente ta usando um padrão de POO para o services, no caso é só colocar esse seu método registerUser no UserService que tem na pasta services, pois o register é um serviço do usuário.

2024-08-16 12:07 UTC, DominMFD approved these changes

2024-08-20 01:02 UTC, Alecell approved these changes

2024-08-20 01:02 UTC, merged