feat: create general size page
devhatt/pet-dex-frontend pull request #295
Opened 2024-08-15 19:45 UTC by JonasGz

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-08-16 12:06 UTC, DominMFD approved these changes

2024-08-19 12:28 UTC, Alecell requested changes
Só uns ajustes

2024-09-04 21:28 UTC, JonasGz commented on src/layouts/app/pages/PetSize/index.scss
> +  min-height: 100%;
eu utilizei pra centralizar a página no meio, vc quis dizer q nao é responsabilidade da página centralizar mas sim do content que vem antes?
![image](https://github.com/user-attachments/assets/a0f142bf-9070-41af-a49a-cfe675ed87f3)

2024-09-06 13:41 UTC, JonasGz commented on src/layouts/app/pages/PetSize/index.scss
> +  min-height: 100%;
eu vejo como responsabilidade da página centralizar, pq cada página vai ter um button fixo no footer, fica bem simples toda página setar um display grid: '1fr auto', '1fr' pro conteudo da página e 'auto' pro button

2024-09-08 16:46 UTC, JonasGz commented on src/layouts/app/pages/PetSize/index.scss
> +    min-height: 28rem;
eu coloquei pq o componente tem um efeito de zoom quando clicado em cada card, ai meio q o componente fica reduzindo e aumentando e gera interferência nos elementos em cima e em baixo desse componente, há alguma forma de resolver isso sem setar um height fixa?

2024-09-10 03:14 UTC, Luiginicoletti approved these changes
Brabo!

![Uploading happy-girl-gif-by-salon-line.gif…]()

2024-09-10 22:00 UTC, Alecell approved these changes

2024-09-10 22:36 UTC, merged