Adiciona roteamento ao clicar no botão "Cadastrar pet"
devhatt/pet-dex-frontend pull request #298
Opened 2024-08-28 13:09 UTC by wendesongomes

Closes #230 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Ao clicar no botão "Cadastrar pet" é redirecionado para "/app/addpets"

</details>

2024-08-28 13:42 UTC, DominMFD approved these changes

2024-08-29 21:47 UTC, diogocaronte requested changes

2024-08-29 21:47 UTC, diogocaronte commented on src/layouts/app/pages/NoPetRegirested/index.js
> +  });
por que nao usar o evento do component?
```suggestion
  this.button.listen('click', () => {
    Router.go('/app/addpets');
  });
```

2024-08-29 21:52 UTC, diogocaronte approved these changes

2024-08-29 21:53 UTC, merged