feat: testes de renderização
devhatt/pet-dex-frontend pull request #300
Opened 2024-09-04 20:24 UTC by gustavogularte

Closes #218

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criado testes de renderização para os componentes TextInput e UploadImage

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Não foi preciso criar teste para o componente Button pois já estava feito
</details>

2024-09-05 22:35 UTC, juliaam requested changes
precisa tentar mais funcionamentos no geral, se quiser ajuda, me grita

2024-09-05 22:35 UTC, juliaam commented on src/components/TextInput/index.spec.js
dá pra verificar sobre os textos também, se o texto digitado está sendo exibido corretamente, se consegue pegar o valor certo, etc...

2024-09-06 11:58 UTC, DominMFD requested changes

2024-09-06 11:58 UTC, DominMFD commented on src/components/UploadImage/index.js
> +      <input class="container-upload-image__input" id="input-file" name="input-file" type="file" accept="image/*" data-select="upload-input" data-testid="upload-input">
Aqui em vez de ser data-testid pode ser um aria-label, é ate melhor para a acessibilidade

2024-09-06 11:58 UTC, DominMFD commented on src/components/UploadImage/index.spec.js
> +    const uploadInput = screen.getByTestId('upload-input');
ai aqui vc pega pela aria-label

2024-09-09 11:35 UTC, Frompaje requested changes

2024-09-09 11:35 UTC, Frompaje commented on src/components/TextInput/index.spec.js
> +};
muda os valores para inglês

2024-09-11 10:44 UTC, DominMFD requested changes

2024-09-11 10:44 UTC, DominMFD commented on src/components/TextInput/index.spec.js
> +    const textInput = screen.getByPlaceholderText('Write something');
Já que você ta usando as props aqui seria legal trocar o texto 'Write something' pra `propsMock.placeholder`

2024-09-11 10:44 UTC, DominMFD commented on src/components/TextInput/index.spec.js
> +    expect(element).toBeEnabled(false);
pq aqui precisa do false sendo que ali no primeiro não precisa? pode tirar o false

2024-09-11 10:44 UTC, DominMFD commented on src/components/UploadImage/index.spec.js
> +    expect(imagePreview).toBeInTheDocument();
aqui não vejo a necessidade disso tudo visto que é um componente só.

2024-09-11 16:53 UTC, Luiginicoletti approved these changes
Muito bom!!! 

Só deixei algumas dúvidas pessoais!

![well-done-ok-gif-by-funk](https://github.com/user-attachments/assets/b5ce6059-e711-4da6-b740-f32bac53aa3b)

2024-09-11 16:53 UTC, Luiginicoletti commented on src/components/TextInput/index.spec.js
> +    const textInput = screen.getByPlaceholderText('Write something');
Faz sentido!

2024-09-11 16:53 UTC, Luiginicoletti commented on src/components/TextInput/index.spec.js
> +import { render, screen, userEvent } from '@testing-library/vanilla';
```suggestion
import { render, screen, userEvent } from '@testing-library/react';
```

Aqui tem que ser vanilla mesmo?

2024-09-11 16:53 UTC, Luiginicoletti commented on src/components/TextInput/index.spec.js
> +import { render, screen, userEvent } from '@testing-library/vanilla';
import { render, screen, userEvent, waitFor } from '@testing-library/react';

2024-09-11 16:53 UTC, Luiginicoletti commented on src/components/UploadImage/index.spec.js
> +    const buttonIcon = screen.getByAltText('Botão com ícone');
Aqui não da pra padronizar os 3 com text?

2024-09-11 16:53 UTC, Luiginicoletti commented on src/components/UploadImage/index.spec.js
> +      expect(uploadInput.files.item(0)).toBe(file);
Aqui precisa testar duas vezes? não vale só o primeiro?

2024-09-11 16:58 UTC, DominMFD commented on src/components/TextInput/index.spec.js
> +import { render, screen, userEvent } from '@testing-library/vanilla';
Tem sim nico, no pet a gente não usa react, a gente usa vanillaJs

2024-09-17 14:04 UTC, juliaam requested changes
pq alterou tantas coisas do sliding nesse pr de testes?

2024-09-17 14:04 UTC, juliaam commented on src/components/UploadImage/index.spec.js
> +      expect(imagePreview).toHaveClass('hidden');
esse teste com class nao é mt bom, seria bom testar sem o uso do toHaveClass

2024-09-17 14:04 UTC, juliaam commented on src/layouts/index.scss
pq?

2024-09-17 14:04 UTC, juliaam commented on src/layouts/index.scss
isso nao deveria ser feito eu acho

2024-09-17 14:04 UTC, juliaam commented on src/layouts/pages/PetSize/index.js
vc acabou colocando a task de criar petsize nesse pr, deveria ser em outro

2024-09-19 19:23 UTC, DominMFD requested changes

2024-09-19 19:23 UTC, DominMFD commented on src/components/UploadImage/index.spec.js
> +      expect(imagePreview).toHaveClass('hidden');
é só falta isso mesmo, podemos dar uma olhada depois

2024-09-19 19:24 UTC, gustavogularte commented on src/components/UploadImage/index.spec.js
> +      expect(imagePreview).toHaveClass('hidden');
missão impossivel isso

2024-09-25 12:18 UTC, juliaam approved these changes

2024-09-25 13:14 UTC, DominMFD approved these changes

2024-09-25 13:15 UTC, merged