feat: namepet recovered from commit
devhatt/pet-dex-frontend pull request #307
Opened 2024-09-11 20:40 UTC by juliaam

Closes #305 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Recuperado componente perdido de página do nome do bichinho de um commit 

</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![image](https://github.com/user-attachments/assets/6f70aa26-c6db-4f66-bf6c-54f17d1ba4b6)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

2024-09-12 14:40 UTC, Luiginicoletti requested changes

2024-09-12 14:40 UTC, Luiginicoletti commented on src/layouts/pages/PetName/index.scss
> +    box-shadow: 0 -3px 8px 0 rgba(73, 77, 90, 0.12156862745098039);
0.12156862745098039.  ta certo isso?

2024-09-12 14:40 UTC, Luiginicoletti commented on src/layouts/pages/PetName/index.js
> +    const image = this.upload.getValue();
```suggestion
    const image = this.upload.getImage();
```

2024-09-12 14:40 UTC, Luiginicoletti commented on src/layouts/pages/PetName/index.js
> +  this.upload.listen('value:change', updateButtonVisibility);
```suggestion
  this.upload.listen('image:change', updateButtonVisibility);
```

2024-09-12 14:40 UTC, Luiginicoletti commented on src/layouts/pages/PetName/index.js
> +  this.button.listen('click', () => {
```suggestion
  this.button.on('click', () => {
```

se fizer sentido apenas.

2024-09-12 16:12 UTC, juliaam commented on src/layouts/pages/PetName/index.js
> +  this.button.listen('click', () => {
o método padrão do djogo.js para escutar emits do component é listen

2024-09-12 16:13 UTC, juliaam commented on src/layouts/pages/PetName/index.js
> +  this.upload.listen('value:change', updateButtonVisibility);
o emit do upload é value:change, está certo com value:change

2024-09-12 16:44 UTC, juliaam commented on src/layouts/pages/PetName/index.scss
> +    box-shadow: 0 -3px 8px 0 rgba(73, 77, 90, 0.12156862745098039);
esses estilos nem eram precisos, tirei

2024-09-17 14:02 UTC, PiluVitu requested changes

2024-09-17 14:08 UTC, PiluVitu approved these changes

2024-09-17 14:18 UTC, merged