Issue 20
devhatt/pet-dex-frontend pull request #33
Opened 2023-12-19 22:15 UTC by RafaelLimaC

Closes 
#20 

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>

![image](https://github.com/devhatt/pet-dex-frontend/assets/132157467/829946a7-f041-4c83-b833-748290ec8152)

  </summary>

</details>

2023-12-19 22:35 UTC, hxsggsz commented
ajusta o titulo pra uma breve informação do que seu pr ta fazendo e preenche o template de pull request, sem essas informações fica dificil revisar seu pr

2023-12-19 22:37 UTC, hxsggsz commented
outra coisa importante, é necessario que você linke a issue na mesma linha do closes, senao ele não vai fechar a issue quando seu pr for mergeado. e.g `Closes #20`

2023-12-19 22:51 UTC, hxsggsz requested changes

2023-12-19 22:51 UTC, hxsggsz commented on src/components/PetCard/index.js
> +const html = `
esse html não fica em um arquivo separado? ou isso foi mudado recentemente?

2023-12-19 22:51 UTC, hxsggsz commented on src/components/PetCard/index.js
> +        <img class="pet-container__image" data-select="pet-image" src="https://png.pngtree.com/png-clipart/20230506/original/pngtree-smiling-dogs-with-happy-expressions-png-image_9144389.png" alt="">
a foto precisa ser recebida de forma dinâmica igual o titulo do card

2023-12-19 22:51 UTC, hxsggsz commented on src/components/PetCard/index.js
> +    <div>
qual a utilidade dessas divs extras que não tem classe nem nenhum seletor?

2023-12-19 22:51 UTC, hxsggsz commented on src/components/PetCard/index.js
> +<div class="pet-container" data-select="pet-container" id="">
```suggestion
<div class="pet-container" data-select="pet-container">
```

2023-12-19 22:51 UTC, hxsggsz commented on src/components/PetCard/index.scss
> +@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&display=swap');
importaçao de font sempre no arquivo `base.scss` a nao ser que voce só va usar essa fonte nesse componente

2023-12-19 22:51 UTC, hxsggsz commented on src/components/PetCard/index.scss
> +$petCardFf: 'Montserrat', sans-serif;
cria um arquivo separado pra variaveis na pasta `styles` e importa ele aqui

2023-12-19 23:24 UTC, RafaelLimaC commented on src/components/PetCard/index.js
> +const html = `
parece que é aí mesmo, segui o exemplo do card que o alê fez

2023-12-20 13:09 UTC, Alecell requested changes

2023-12-20 13:09 UTC, Alecell commented on src/components/PetCard/index.scss
> +  height: 225px;
Não usar `width` e `height` fixas, nunca!

Nesse caso é preferivel que seu Card siga um aspect ratio ou seja totalmente moldavel pelo container, mas `width` e `height` fixas é pra ser usado **apenas** por elementos puramente visuais

2023-12-20 13:09 UTC, Alecell commented on src/components/PetCard/index.scss
> +@use '../../styles/var.scss';
O alias não funciona aqui? Se mandar um `~styles/base.scss`

2023-12-20 13:09 UTC, Alecell commented on src/components/PetCard/index.js
> +  },
É legal colocar esses parametros no contrutor!

2023-12-20 13:50 UTC, RafaelLimaC commented on src/home/main.js
> +// eslint-disable-next-line prettier/prettier
O eslint tava pedindo pra eu dar um enter nada a ver na linha de baixo, acho que era porque o link da imagem é mto grande, ai usei esse disable ai

2023-12-20 19:41 UTC, RafaelLimaC commented on src/home/main.js
Antes do commit eu devo apagar todo o conteudo do main.js?

2023-12-23 14:25 UTC, Alecell commented
Na prox no nome da sua issue segue o padrão do povo man! Basicamente precisa seguir nosso padrão de commit e dalle

2023-12-23 14:30 UTC, Alecell requested changes

2023-12-23 14:30 UTC, Alecell commented on src/components/PetCard/index.js
> +const html = `
Ta certinho, mudamos pq azedou o role

2023-12-23 14:30 UTC, Alecell commented on src/components/PetCard/index.js
> +</div>
Joga isso um bloco pra frente

2023-12-23 14:30 UTC, Alecell commented on src/components/PetCard/index.js
> +  }
```suggestion
  if (title) this.setTitle(title);
  if (imgSrc) this.setImgSrc(imgSrc);
  if (imgAlt) this.setImgAlt(imgAlt);
```

2023-12-23 14:30 UTC, Alecell commented on src/components/PetCard/index.js
> +  }
Ou vc pode colocar a verificação no método em si! Eu acho que colocar no método é mais maneiro em!!

2023-12-23 14:30 UTC, Alecell commented on src/components/PetCard/index.scss
> +  max-height: 225px;
os cards precisam fluir de acordo com a necessidade de onde são usados. Ou seja, não podem ter largura ou altura fixas, isso deve ser fluido

2023-12-23 14:30 UTC, Alecell commented on src/components/PetCard/index.scss
> +  box-shadow: 0 0 5px 0 #0c1a4b0d;
Essas propriedades uma vai sobrescrever a outra, precisa remover uma delas

2023-12-25 20:15 UTC, RafaelLimaC commented on src/components/PetCard/index.scss
> +  max-height: 225px;
Entendi, isso ai fica a cargo do lugar que ele vai ser usado? Tipo assim:

.container-onde-o-card-eh-usado > * {
  max-width: 20%;
}

Removi width/height, deixei só o aspect-ratio

2024-01-03 15:32 UTC, Alecell requested changes

2024-01-03 15:32 UTC, Alecell commented on src/components/PetCard/index.js
> +  <img class="pet-container__image" data-select="pet-image" src="" alt="">
Identação

2024-01-03 15:32 UTC, Alecell commented on src/styles/base.scss
pq o base foi apagado?

2024-01-03 20:27 UTC, RafaelLimaC commented on src/styles/base.scss
Eu tinha alterado ele só pra testar os cards e tal, no fim não essas alterações não precisavam estar no pr

2024-01-08 01:50 UTC, Alecell approved these changes

2024-01-08 02:09 UTC, hxsggsz approved these changes

2024-01-08 21:17 UTC, aalmeida00 requested changes
Voce precisa ajustar os conflitos da sua branch.

Aqui será necessário um rebase com o repositório remoto da devhatt, se precisar de ajuda me pinga no discord.

2024-01-08 21:17 UTC, aalmeida00 commented on src/components/PetCard/index.scss
> +}
eof

2024-01-11 21:39 UTC, aalmeida00 approved these changes

2024-01-15 01:44 UTC, Alecell requested changes

2024-01-15 01:44 UTC, Alecell commented on src/components/PetCard/index.scss
> +  box-shadow: 0 0 0.5rem 0 #0c1a4b0d;
usar rgba

2024-01-15 01:44 UTC, Alecell commented on src/styles/base.scss
> +/* stylelint-disable-next-line scss/load-no-partial-leading-underscore */
NOOOOO

2024-01-16 22:46 UTC, aalmeida00 approved these changes

2024-01-18 02:35 UTC, aalmeida00 approved these changes

2024-01-18 12:20 UTC, Alecell reviewed
Só preciso saber se aquela parte visual foi resolvida

2024-02-01 11:00 UTC, Alecell requested changes

2024-02-01 11:00 UTC, Alecell commented on src/components/TextInput/index.scss
> +        background-color: rgba(238, 114, 126, 0.4588235294117647);
Isso não pode ser essa dizima periódica. Trunka pra 0.458

2024-02-01 11:00 UTC, Alecell commented on src/styles/base.scss
> +@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@600;700&display=swap');
Não importar fontes pelo CSS, sempre o fazer pelo HTML

2024-02-01 11:00 UTC, Alecell commented on src/styles/var.scss
Acredito que a fonte não fique aqui, o arquivo de fontes inclusive ta sendo criado

2024-02-08 13:06 UTC, Alecell requested changes

2024-02-08 13:06 UTC, Alecell commented on src/components/TextInput/index.scss
Parece que foi adicionada varias propriedades duplicadas nesse arquivo, rever.

2024-02-08 13:06 UTC, Alecell commented on src/components/TextInput/index.scss
> +        background-color: rgba(238, 114, 126, 0.45);
Deveria ser 3 casas decimais, não 2.

2024-02-08 13:06 UTC, Alecell commented on src/components/TextInput/index.scss
> +      border-bottom: 2px solid rgb(191, 191, 191);
Pq esse border-bottom foi alterado?

2024-02-08 17:38 UTC, RafaelLimaC commented on src/components/TextInput/index.scss
> +      border-bottom: 2px solid rgb(191, 191, 191);
Arrumei agora, eu devo ter feito besteira na hora do rebase

2024-02-08 21:16 UTC, Alecell approved these changes

2024-02-08 21:37 UTC, merged