Adicionando arquivos de variaveis de cores
devhatt/pet-dex-frontend pull request #41
Opened 2023-12-26 18:04 UTC by GabrielBruno7

Closes #38 

<details open> 
  <summary>
    <b>Feature </b>
  </summary>

Adicionando arquivo de variáveis de cores 
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
 Criei o arquivo colors.scss
</details>

<br>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ x ] Issue linked
  - [ x ] Build working correctly

</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
 Arquivo criado baseado na paleta de cores não oficial, quando a oficial for criada irei refazer.
</details>

2023-12-26 18:08 UTC, Alecell requested changes

2023-12-26 18:08 UTC, Alecell commented on src/styles/colors.scss
Remover todos os comentário

2023-12-27 14:17 UTC, hxsggsz approved these changes

2024-01-02 03:10 UTC, aalmeida00 approved these changes

2024-01-02 18:37 UTC, Alecell requested changes

2024-01-02 18:37 UTC, Alecell commented on src/styles/colors.scss
> +$othersGray: #deecf5;
A nomeclatura ta fora do padrão. Fala com o Eliabe pra que ele de o nome certinho de cada cor.

Em geral é coisa tipo `$primary`, `$secondary`, `$error` e etc.

2024-01-02 19:52 UTC, GabrielBruno7 commented on src/styles/colors.scss
> +$othersGray: #deecf5;
Já foi solicitado, aguardando o Eliabe criar a padronização no figma.

2024-01-09 21:56 UTC, aalmeida00 commented
Temos alguma atualização aqui? @GabrielBruno7

2024-01-09 21:58 UTC, aalmeida00 commented
Fiz update da sua branch com a main, quando for commitar de novo no seu for vai ter que fazer um reset hard.
**Só fazer esse comando se AINDA nao tiver feito nenhuma modificação, se tiver feito modificação ou commitado, faça um rebase**

git fetch <repositorio remoto>
git reset --hard <repositorio remoto>/<suabranch>


Se ficar com dúvidas pode me pingar no discord.

2024-01-11 13:41 UTC, Alecell commented
Alguma atualização aqui @GabrielBruno7 ?

2024-01-19 12:07 UTC, closed without merging