feat(more-info): adding question card and optional observation input
devhatt/pet-dex-frontend pull request #43
Opened 2024-01-05 21:54 UTC by geisabitt

Closes 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Adicionar a pagina Conte-me mais sobre seu pet
</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
N/A

- **Cause**
N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

  - [ ] Issue linked
  - [ ] Build working correctly
  - [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Acredito que esteja complexo de mais e também não sei se está correto as nomenclaturas. estou renderizado as imformações apartir de um json, mas a lógica não está funcionando muito bem porque o card vacina está exibindo elementos dos outros cards
</details>

2024-01-06 16:20 UTC, aalmeida00 requested changes
Percebi que tem um arquivo html/css aqui, deveria?

2024-01-06 16:20 UTC, aalmeida00 commented on questoes.json
arquivo em portugues, trocar para questions.json

2024-01-06 16:20 UTC, aalmeida00 commented on src/assets/shield.svg
vale ver com o @Alecell se vamos usar os icons/assets assim como svg ou vamos usar outro caminho apra lidar com isso.

2024-01-06 16:20 UTC, aalmeida00 commented on src/components/card-pet/index.css
> +}
Isso me cheira a algum reset de css, não temos um normalize aqui no código?

2024-01-06 16:20 UTC, aalmeida00 commented on src/components/card-pet/index.css
Nós vamos usar css ou sass?

2024-01-06 16:20 UTC, aalmeida00 commented on src/components/card-pet/index.css
> +  background-color: #003459;
Tem que ver se essas cores vao fazer parte de variaveis para reutilizar e tals

2024-01-06 16:20 UTC, aalmeida00 commented on src/components/card-pet/index.css
> +  padding: 24px;
Evitamos ao máximo uso de PX, só pra casos muito especificos, borders, border-radius, etc.

2024-01-06 16:20 UTC, aalmeida00 commented on src/components/card-pet/index.html
> +</html>
eof

2024-01-06 20:58 UTC, geisabitt commented on src/components/card-pet/index.css
> +}
eu não estava coseguindo renderisar os dados na desculpe as esse indes.css dão deveria existir, fou falha minha em comitar esse arquivo tbm

2024-01-08 01:22 UTC, Alecell commented
O "Closes" deve seguir o ID da sua task, tipo " Closes #43 "

2024-01-08 01:35 UTC, Alecell requested changes

2024-01-08 01:35 UTC, Alecell commented on src/assets/dogs/Beagle.png
Acredito que idealmente essas imagens deveriam estar na pasta do componente em questão, não sei se é possivel, vale conversarmos sobre. Se não for possivel, colocar essas imagens atreladas a um path semantico com o componente, como essas imagens irão vir da API no futuro precisamos deixar claro que as imagens são do placeholder do componente pra podermos remover depois.

2024-01-08 01:35 UTC, Alecell commented on src/assets/shield.svg
Não vamos!

2024-01-08 01:35 UTC, Alecell commented on src/components/card-pet/index.css
é scss mesmo!

2024-01-08 01:35 UTC, Alecell commented on src/components/card-pet/index.css
> +  padding: 24px;
Pra essas coisas usar `rem`. Tem um artigo que escrevi sobre que pode ajudar!

2024-01-08 01:35 UTC, Alecell commented on src/components/card-pet/index.html
Não temos `.html` nos componentes!

No caso vc cria o elemento no seu JS e só exporta o JS e usa ele onde precisar

Outro detalhe, esse componente é derivado de uma página, então vamos move-lo para o bloco dessa página na estrutura de arquivos.

2024-01-08 01:35 UTC, Alecell commented on src/components/card-pet/index.scss
O arquivo a pesar de ser `.scss` esta escrito como `.css`, pra mantermos o padrão é interessante usar tanto o aninhamento quanto o `&` pra fazer a herança do nome da classe

2024-01-08 01:35 UTC, Alecell commented on src/components/card-pet/index.scss
> +input[type='radio']:checked + label .checkmark {
Nunca estilizar tags, sempre classes. Isso facilita manutenção do código a longo prazo.

Vale pra todos os arquivos de estilo

2024-01-08 01:35 UTC, Alecell commented on src/home/index.html
> +  </main>
Pq temos 2 mains?

2024-01-08 01:35 UTC, Alecell commented on src/components/card-pet/index.js
> +export default function CardPet() {
É interessante podermos definir as propriedades do componente no construtor dele e não apenas por getters e setters

Coloque como propriedades as propriedades que o componente pode receber!

2024-01-08 01:35 UTC, Alecell commented on src/styles/base.scss
> +  background: #003459;
Isso é má pratica!

Podemos colocar esse tipo de estilo no `main` de uma página ou mesmo de todas, mas nunca nesse arquivo, isso gera problemas caso tenhamos alguma exceção!

Mas porque precisamos desse bg?

2024-01-09 21:58 UTC, aalmeida00 commented
Alguma atualização aqui? @geisabitt 

Voce precisa ajustar os conflitos da sua branch.

Aqui será necessário um rebase com o repositório remoto da devhatt, se precisar de ajuda me pinga no discord.

2024-01-12 03:49 UTC, aalmeida00 requested changes

2024-01-12 03:49 UTC, aalmeida00 commented on src/components/more-info/index.js
> +      if (text === '' || null || undefined) {
Aqui tem redundancia não?

se voce fizer `if (!text)` tem o mesmo significado que esse detalhe

2024-01-12 03:49 UTC, aalmeida00 commented on src/components/more-info/index.js
> +      if (text === '' || null || undefined) {
aqui o mesmo detalhe da linha 45

2024-01-12 03:49 UTC, aalmeida00 commented on src/components/more-info/index.scss
> +    padding: 20px;
rem

2024-01-12 03:49 UTC, aalmeida00 commented on src/components/more-info/index.scss
> +    gap: 20px;
rem

2024-01-12 03:49 UTC, aalmeida00 commented on src/home/main.js
> +// }
Esse cara vai ficar comentado?

2024-01-12 04:27 UTC, geisabitt reviewed
Avaliar se os icones ficarão assim mesmo

2024-01-12 04:48 UTC, geisabitt commented
![1 0 - LP Inicial](https://github.com/devhatt/pet-dex-frontend/assets/115119838/28e8c41a-2b13-4204-9f10-46980f023c7d)

2024-01-12 19:20 UTC, geisabitt commented
/approve

2024-01-31 21:09 UTC, Alecell requested changes
Vi que tem alteração em vários arquivos de config como o dependabot e os workflows. Acredito que foi uma alteração acidental, mas precisamos resolver isso, não pode haver alteração lá a menos que seja necessário

2024-01-31 21:09 UTC, Alecell commented on src/components/more-info/index.js
> +        const divVaccines = document.createElement('div');
quando temos no js elementos que são tags, não dados de js, usamos o pattern de usar `$` na declaração do elemento como `$vaccines`

No caso tambem não é uma boa pratica chamar a variavel com o nome ta tag que ela tem, seria melhor um `$vaccinesContainer` doque um `$divVaccines`

2024-01-31 21:09 UTC, Alecell commented on src/components/more-info/index.scss
> +  max-width: 940px;
Não usar `px`, no caso use `rem`

2024-01-31 21:09 UTC, Alecell commented on src/components/more-info/index.scss
Seu arquivo CSS parece que não está seguindo nosso stylelint, haverão erros no build se não forem arrumados

2024-01-31 21:09 UTC, Alecell commented on src/components/more-info/index.scss
> +  min-width: 630px;
`px` é um crime x.x

2024-01-31 21:09 UTC, Alecell commented on src/components/more-info/index.scss
> +    max-width: 46%;
pq 46%? Esse número me parece meio mágico, algum motivo especial do porque precisa ser assim?

2024-01-31 21:09 UTC, Alecell commented on src/components/more-info/index.scss
> +  max-height: 130px;
não usar px

Na verdade pra limitar a altura vc precisa de um motivo excelente pra fazer isso, talvez precisemos falar sobre o porque esse `max-height` é necessário e estratégias pra não rpecisar dele

2024-01-31 21:09 UTC, Alecell commented on src/components/more-info/index.scss
> +  width: 6px;
esse é um bom caso on o px é aceitável

2024-01-31 21:09 UTC, Alecell commented on src/components/more-info/index.scss
> +  gap: 5px;
`gap` tambem deve ser feito em `rem`

2024-01-31 21:09 UTC, Alecell commented on src/components/more-info/index.scss
> +}
Pode apagar, mesmo que a task não esteja concluida vc não pode sujar seu componente com coisas que não são dele, só deixa essa observação no PR e gg

2024-01-31 21:09 UTC, Alecell commented on src/home/index.scss
> +
Não sei se isso está correto, talvez precisamos falar osbre

2024-01-31 21:09 UTC, Alecell commented on src/home/index.scss
> +}
EOF

2024-01-31 21:09 UTC, Alecell commented on src/home/main.js
Os comentários precisam ser descomentados pra que o componente e o use fique de exemplo pras outras pessoas no futuro. Vamos apagar quando houver mais componentes de exemplo, mas no momento isso precisa ser descomentado e mantido

2024-02-21 03:10 UTC, closed without merging

2024-02-21 03:11 UTC, Alecell commented
PR fechado decorrente de inatividade