Issue 26
devhatt/pet-dex-frontend pull request #50
Opened 2024-01-11 01:55 UTC by anthonymanoel

Closes #26

- **Description**
  Adicionando range-slider como um componente dinâmico para futuramente setar peso do animal.

2024-01-11 13:37 UTC, Alecell requested changes

2024-01-11 13:37 UTC, Alecell commented on src/components/PetRegist/Ellipse.svg:Zone.Identifier
Oque é isso?

2024-01-11 13:37 UTC, Alecell commented on src/components/PetRegist/Ellipse.svg
Porque temos duas imagens do "Ellipse"?

Por isso se chama Ellipse?

2024-01-11 13:37 UTC, Alecell commented on src/components/PetRegist/Bars.svg
Isso não pode ser uma imagem, tem q ser feito no HTML/SVG raw pra fazer animação

2024-01-11 13:37 UTC, Alecell commented on src/components/PetRegist/index.css
Isso aqui não existe, vc fez em `css`? A gente usa `scss` não `css`.

2024-01-11 13:37 UTC, Alecell commented on src/components/PetRegist/index.css
> +}
Vc não pode fazer isso num arquivo interno de `css`, alterar o `html` e usar `*` é muito errado, precisa ajustar

2024-01-11 13:37 UTC, Alecell commented on src/components/PetRegist/index.css
> +}/*# sourceMappingURL=index.css.map */
Isso é um sourcemap? Pq tem um sourcemap no seu componente?

2024-01-11 13:37 UTC, Alecell commented on src/components/PetRegist/index.scss
Precisamos falar sobre isso

2024-01-11 15:54 UTC, anthonymanoel commented on src/components/PetRegist/index.css
> +}/*# sourceMappingURL=index.css.map */
po esse sourcemap eu não adicionei ai não, que brisa é essa

2024-01-11 16:00 UTC, anthonymanoel commented on src/components/PetRegist/Ellipse.svg
Eu exportei como SVG do figma do petdex, e lá está com o nome de selection ellipse: 
![image](https://github.com/devhatt/pet-dex-frontend/assets/72582172/74ff2639-e37e-471b-b225-4c4429809f07)

acabei por colocar esse nome.

a despeito dos 2 arquivos, um é para desktop e outro para mobile, ao tentar estilizar ele no mobile, uma parte dele se ocultava caso eu desse um Width do tamanho necessário. Então a solução que achei foi duplicar o arquivo e mudar direto no código do SVG o tamanho.

2024-01-11 16:00 UTC, anthonymanoel commented on src/components/PetRegist/Bars.svg
é um svg, exportei direto do figma do petdex.

2024-01-11 16:01 UTC, anthonymanoel commented on src/components/PetRegist/index.scss
bah, blz

2024-01-11 16:51 UTC, anthonymanoel commented on src/components/PetRegist/index.css
> +}
blz

2024-01-11 16:52 UTC, anthonymanoel commented on src/components/PetRegist/index.css
eu fiz em sccs. 

foi uma extensão minha que criou esse .css, vou tirar ele de jogo, tinha esquecido.

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.js
> +    this.emit('weight');
o nome do evento muda pra `weight:change`

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.scss
> +  font-size: 10px;
Usar `rem`

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.scss
> +  height: 30vh;
Nop

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.scss
> +  margin: 5px;
Usar `rem`

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.scss
> +  line-height: 80px;
Usar sem unidade

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.scss
> +  width: 90vw;
No

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.scss
> +  padding-right: 85px;
usar `rem`

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.scss
> +  top: -75px;
Usar `%`, no max usar outra coisa, a menos que vc me justifique o porque precisa de `-75px` de `top`

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.scss
> +  z-index: -1;
What? Why?

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.scss
> +  margin-top: -45px;
Identação

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.scss
Ta usando em alguns momentos identação de 4 espaçoes, use apenas 2

2024-01-18 12:49 UTC, Alecell commented on src/components/PetRegist/index.scss
Ta usando em alguns momentos identação de 4 espaçoes, use apenas 2

2024-01-18 12:56 UTC, Alecell requested changes
Preciso que se atente mais na parte de estilos, principalmente em:
- Buscar soluções com melhor compatibilidade entre browsers
- Evitar repetição de propriedade
- Evitar "resolver um problema que vc mesmo causou", muito do seu CSS parece ser gambiarras que vc precisou fazer pq usou muita coisa que não deve ser usada ou alguma coisa que estragou a outra saca?
- Se atentar ao nosso padrão de unidades e como usamos https://www.linkedin.com/pulse/unidades-css-um-guia-completo-alexandre-gomes/

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +    width: 600px;
usar `%`, largura em `px` é um crime hediondo

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +    &::-webkit-slider-runnable-track {
Isso não é muito bem suportado, precisamos talvez conversar sobre o pq isso é necessario e quais estrategias podemos usar

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +    &::-webkit-slider-thumb {
Isso não é muito bem suportado, precisamos talvez conversar sobre o pq isso é necessario e quais estrategias podemos usar

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +      height: 100px;
Nunca never jamais

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +@media only screen and (max-width: 600px){
A gente ainda não tem as media-query padrão?

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +@media only screen and (max-width: 600px){
Unidade de media query tem que ser em `rem`

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +  }
Q?

Nunca use esse tipo de genericidade sem ser numa arquivo global de configuração, dentro do seu SCSS de um componente, pagina ou sessão isso **nunca** pode existir

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +  height: 70vh;
Não, isso não é bom

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +    width: 100vw;
Nop

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +    width: 200vw;
Nop

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +    z-index: -1;
Porqueeee

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +    margin-top: 15px;
identação

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
> +      width: 80vw;
Não

2024-01-18 12:56 UTC, Alecell commented on src/components/PetRegist/index.scss
Tive a impressão de que no fim desse arquivo vc duplicou alguns estilos, isso aconteceu de fato?

2024-01-23 17:12 UTC, anthonymanoel commented on src/components/PetRegist/index.scss
> +    z-index: -1;
p resolver a questão do bars-svg fica atrás na position absolute, mt errado?

2024-01-23 17:13 UTC, anthonymanoel commented on src/components/PetRegist/index.scss
> +    margin-top: 15px;
Ale, todas as partes de identação do Sass foram colocadas pelas extensões, eu deixo tudo mt próximo um do outro, com no máximo 1 espaço de linhas.

2024-01-23 17:15 UTC, anthonymanoel commented on src/components/PetRegist/index.js
> +/* eslint-disable prettier/prettier */
prettier e eslint estão dando conflito de identação, precisei desativar um para que não desse erro. Cheguei até a falar com o Pilu e Diogo sobre esse erro ai, e te mandei msg um dia no discord mostrando o erro, no fim ele era ocasionado por conta de conflito de identação

2024-01-23 17:16 UTC, anthonymanoel commented on src/components/PetRegist/index.js
Como ele vai fazer parte do cadastro de pets e ainda não existia nenhum arquivo, pensei em já deixar o nome para guiar o que esse componente faz parte.

2024-01-23 17:16 UTC, anthonymanoel commented on src/components/PetRegist/index.js
> +  weight() {
ok

2024-01-23 17:17 UTC, anthonymanoel commented on src/components/PetRegist/index.scss
> +  padding-right: 85px;
bah não tinha visto que eu coloquei em px

2024-01-23 17:18 UTC, anthonymanoel commented on src/components/PetRegist/index.scss
> +    width: 600px;
OK!

2024-01-23 17:18 UTC, anthonymanoel commented on src/components/PetRegist/index.scss
> +@media only screen and (max-width: 600px){
até o dia que eu subi isso não tinha não

2024-02-21 03:10 UTC, closed without merging