Arquivo SCSS de definições de fontes para o projeto criado.
devhatt/pet-dex-frontend pull request #51
Opened 2024-01-11 03:06 UTC by DominMFD

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criado o arquivo font.scss que irá conter todas as definições de fontes do projeto, utilizado mixins e funções reutilizáveis

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
O arquivo contem variáveis, mixins e funções para criar estilos facilmente aplicáveis e modulares, todos eles comentados explicando sua finalidade e com exemplos de como utilizar ao final do arquivo.
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
É meu primeiro pull request nesse estilo, qualquer feedback coisa estou disposto a ouvir, tanto do pull request quanto do arquivo da task, qualquer melhoria ou sugestão pode me falar, pretendo seguir no projeto e ser ativo no discord, tenho o objetivo de crescer.
</details>

2024-01-11 03:10 UTC, DominMFD commented
Por favor me enviei feedbacks do pull request, qualquer variável, mixins e funções para adicionar ou alterar estarei disposto a isso, tentei fazer mixins e funções para os componentes que mais se repetem, utilizei o figma para essa referência.

2024-01-11 13:24 UTC, Alecell requested changes

2024-01-11 13:24 UTC, Alecell commented on src/styles/fonts.scss
> +$_4xl: 3.75rem;   //60px
Nossas `font-size` derivam de 62.5% então a base é 10, não 16!

No caso, 30px por exemplo é 3rem!

2024-01-11 13:24 UTC, Alecell commented on src/styles/fonts.scss
> +}
Nossa ideia era que isso fossem `@mixin` de propriedade usados da ou assim:
`font-family: font('button')`
`font-weight: font-weight('button')`

Ou assim:
`font-weight: font-weight-button`

Vale trazer a discussão sobre isso pra sabermos a melhor forma!

2024-01-11 13:39 UTC, Alecell commented
Iae man! No template de PR, as partes que não se encaixam no seu PR vc pode apagar tipo o bugfix e o visual reference!

Na parte ali no inicio "Closes" deve seguir o id da sua issue, por exemplo "Closes #51"

2024-01-11 16:32 UTC, DominMFD commented on src/styles/fonts.scss
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
Ta bom, eu posso remover e importar no HTML?

2024-01-11 16:36 UTC, DominMFD commented on src/styles/fonts.scss
> +  } */
É que na task pede para falar como os desenvolvedores devem utilizar, ai pensei nisso, como posso fazer de uma forma diferente?

2024-01-11 16:38 UTC, DominMFD commented on src/styles/fonts.scss
> +$fontStyleunderline: underline;
Não, eu peguei as variações usadas no geral, mas seria interessante falar com o Designer, vou fazer isso.

2024-01-11 16:43 UTC, DominMFD commented on src/styles/fonts.scss
> +}
Adoraria participar da discussão sobre isso, posso trazê-la na próxima reunião se me permitir

2024-01-11 16:44 UTC, DominMFD commented
Muito obrigado pelo ensinamento!

2024-01-11 21:50 UTC, aalmeida00 commented on src/styles/fonts.scss
> +@import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap');
Sim pode

2024-01-11 21:50 UTC, aalmeida00 commented on src/styles/fonts.scss
> +  } */
Pode documentar no próprio PR

2024-01-12 02:40 UTC, DominMFD commented
Fiz a substituição dos mixins pelas variáveis como discutido na daily, qualquer alteração necessária estou a disposição, fiquei na duvida do nome das variáveis, se puder me dar um feedback sobre o nome delas.

2024-01-12 03:44 UTC, aalmeida00 requested changes

2024-01-12 03:44 UTC, aalmeida00 commented on src/styles/fonts.scss
> +
tem bastante espaço sobrando aqui.


E olhando o arquivo, parece que o seu stylelint não está ajustando os arquivos scss, talvez falte alguma configuração de setup aqui. @Alecell

2024-01-12 12:59 UTC, DominMFD commented
Removi os espaços em branco, irei dar uma olhada sobre as configurações

2024-01-13 17:07 UTC, DominMFD commented on src/styles/fonts.scss
> +$fontStyleunderline: underline;
Falei com o Designer e ele falou que são essas as variações mesmo @Alecell

2024-01-16 22:49 UTC, aalmeida00 approved these changes

2024-01-18 12:39 UTC, Alecell requested changes

2024-01-18 12:39 UTC, Alecell commented on src/home/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Poppin
São essas fontes que **precisamos**? Não podemos carregar na página mais fontes do que o necessário pois isso pesa em pageload

Preciso que me confirme se tudo isso é necessário

Não estou falando de quantas fontes, mas de todos os pesos, a gente precisa praticamente de todos os pesos das fontes que usamos?

2024-01-18 12:39 UTC, Alecell commented on src/styles/fonts.scss
> +$_4xl: 6.0rem;   //60px
Pode rancar o comentário

2024-01-18 12:39 UTC, Alecell commented on src/styles/fonts.scss
> +//font-size
Ranca

2024-01-18 12:39 UTC, Alecell commented on src/styles/fonts.scss
> +//font-family
Ranca

2024-01-18 12:39 UTC, Alecell commented on src/styles/fonts.scss
> +$_4xl: 6.0rem;   //60px
Essa nomeclatura foi conversada com o Eliabe ou com o Thiago? Só pra saber se vai ser consistente

2024-01-18 12:39 UTC, Alecell commented on src/styles/fonts.scss
> +//font-weight
Ranca

2024-01-18 12:39 UTC, Alecell commented on src/styles/fonts.scss
> +$fontStyleunderline: underline;
GOD

2024-01-18 12:39 UTC, Alecell commented on src/styles/fonts.scss
> +//font-style
Ranca

2024-01-18 12:39 UTC, Alecell commented on src/styles/fonts.scss
> +$fontWeightBlack: 900;
Esses nomes de variavel tão inconsistente com os outros nomes de variavel, colocar apenas `$light`, `$regular` e etc

2024-01-18 16:40 UTC, DominMFD commented on src/home/index.html
> +    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Poppin
Dando uma boa olhada no Protótipo do Figma só usamos os pesos 400, 500, 600 e 700.  Irei refazer o import e tirar o restante dos pesos.

2024-01-18 16:58 UTC, DominMFD commented on src/styles/fonts.scss
> +$_4xl: 6.0rem;   //60px
Estou esperando resposta do Eliabe sobre isso.

2024-01-18 17:01 UTC, DominMFD commented on src/styles/fonts.scss
> +$fontWeightBlack: 900;
uai, mas lá em cima você mandou um GOD, estou confuso agora

2024-01-22 18:21 UTC, DominMFD commented
O import das fontes agora estão corretas com as fontes e os pesos, foi tudo revisado com o Eliabe.

2024-01-22 18:41 UTC, Alecell commented on src/styles/fonts.scss
> +$fontWeightBlack: 900;
Foi por ter colocado os font-style possiveis na parada, não foi o toooodo todo 😀

2024-01-22 18:43 UTC, Alecell commented on src/styles/fonts.scss
> +$_4xl: 6.0rem;   //60px
Se precisar fala com o Thiago pra agilizar

2024-01-22 18:44 UTC, DominMFD commented on src/styles/fonts.scss
> +$fontWeightBlack: 900;
entendi

2024-01-29 21:51 UTC, Alecell approved these changes

2024-01-29 21:51 UTC, Alecell commented on src/styles/fonts.scss
> +$Underline: underline;
Minusculo

2024-02-02 21:46 UTC, Alecell approved these changes

2024-02-02 21:46 UTC, merged