fix: fix the logical to set placeholder, changed the name of the events
devhatt/pet-dex-frontend pull request #52
Opened 2024-01-11 16:29 UTC by MateusHenriquegringo

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-01-11 21:49 UTC, aalmeida00 approved these changes

2024-01-11 23:28 UTC, Alecell requested changes

2024-01-11 23:28 UTC, Alecell commented on src/components/TextInput/index.js
> +    this.emit('input:enabled');
Juntar em uma função só de `disable(boolean)`

2024-01-11 23:28 UTC, Alecell commented on src/components/TextInput/index.js
> +  'input:enabled',
Remover os "input" do nome dos eventos

2024-01-16 22:50 UTC, aalmeida00 approved these changes

2024-01-18 12:33 UTC, Alecell requested changes

2024-01-18 12:33 UTC, Alecell commented on src/components/TextInput/index.scss
> +    filter: opacity(0.55);
Identação

2024-01-18 12:33 UTC, Alecell commented on src/components/TextInput/index.scss
>      filter: opacity(0.85);
Trailing space

2024-01-20 04:06 UTC, aalmeida00 approved these changes

2024-01-31 21:14 UTC, Alecell requested changes

2024-01-31 21:14 UTC, Alecell commented on src/components/TextInput/index.scss
> +}
Foi removido o EOF, precisa colocar novamente

2024-02-01 18:17 UTC, Alecell approved these changes

2024-02-01 18:17 UTC, merged