Issue 39
devhatt/pet-dex-frontend pull request #56
Opened 2024-01-13 20:58 UTC by JonasGz

Closes #39 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação de arquivo breakpoints para adaptação da aplicação em diferentes telas.

</details>

<details> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![most commons desktops](https://github.com/devhatt/pet-dex-frontend/assets/13170219/8c5a285f-1abf-44e2-a0c9-3e2e01efe5a2)
![most commons mobiles](https://github.com/devhatt/pet-dex-frontend/assets/13170219/3d03ea68-7b0a-4a3b-841f-be92fc1e9a14)
![most commons tablets](https://github.com/devhatt/pet-dex-frontend/assets/13170219/bb11178d-1f00-4e16-95e3-825d8af37984)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [x] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>

**Pesquisa**

- **Smartwatchs**: até 319px (todos os smartwatches encontrados no mercado possuem um width de até 267px, como margem de segurança defini para 319px).
- **Mobile**: 320px até 430px (na pesquisa foi encontrado apenas 2 celulares com mais de 430px de width que preferi considerá-los como dispositivos médios, todos os outros celulares possuem um min-width: 320px e max-width: 430px).
- **Dispositivos médios**: 431px até 1023px (na pesquisa foi identificado essas medidas para os dispositivos médios(tablets/ipads).
- **Notebooks/desktops**: 1024px até 1920px (com o intuito de não possuírem diferentes media queries, achei prudente juntar os notebooks médios de 1024px com os desktops padrões maiores).
- **Grandes telas: 1921px ++** (telas maiores que 1920px podem exigir um layout diferente, tendo em vista existirem telas de 2560px).
- Os breakpoints foram separados com base dispositivos diferentes e telas que possam alterar significativamente o layout, necessitando de alterações.
- Os dados foram baseados nas telas mais utilizadas, conforme o gráfico presente no site **statcounter.com**, do período de 01 JAN 23 a 31 DEZ 23 e de todos os dispositivos existentes encontrados. O arquivo também foi elaborado com base na pesquisa realizada em sites de referência em artigos de desenvolvimento atualizados, conforme listagem abaixo.

</details>

2024-01-24 15:02 UTC, Alecell requested changes

2024-01-24 15:02 UTC, Alecell commented on src/styles/breakpoints.scss
> +}
EOF

2024-01-24 15:02 UTC, Alecell commented on src/styles/breakpoints.scss
> +@mixin fromLargest {
Não usar nomes, usar esse padrão `from[size]`, por exemplo `from1024`, `from720` e etc. Nomes são facilmente esquecidos, já algo com o numero é facilmente entendivel

2024-01-24 15:02 UTC, Alecell commented on src/styles/breakpoints.scss
> +  @media (max-width: #{$smartwatchsSizeMax}) {
Não precisa usar a interpolação do sass aqui, só a variavel ja é o suficiente

2024-01-24 15:02 UTC, Alecell commented on src/styles/breakpoints.scss
> +}
De uma linha de espaço entre cada bloco de mixin

2024-01-24 22:27 UTC, JonasGz commented on src/styles/breakpoints.scss
> +@mixin fromLargest {
Alterados, só fiquei na dúvida de nomear o primeiro breakpoint "fromSmartWatch", esse é o único que precisou estar com max-width, como eu nomeio nesse caso? pensei em fromMax319, pois o próximo iniciar em 320px...

2024-01-31 22:35 UTC, Alecell approved these changes
BALA!

2024-01-31 22:35 UTC, Alecell commented
Só precisa atualizar a branch

2024-02-08 11:53 UTC, Alecell approved these changes
TA BALA!!

2024-02-08 22:26 UTC, PiluVitu approved these changes

2024-02-09 19:05 UTC, closed without merging