Issue 17 - Menu e itens
devhatt/pet-dex-frontend pull request #61
Opened 2024-01-31 17:35 UTC by JonasGz

Closes #17 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação de componente sidemenu responsivo com nav e content, contendo as funções de abrir/fechar e active.

</details>

<details> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  - conflitos de responsividade com height definida de 100vh;

- **Cause**
  - A height definida em 100vh não considera as barras de navegação e outros itens que estiverem na screen do mobile do usuário.

- **Solution**
- Alteração de height da .home de 100vh para 100dvh.
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
`.home {
height: 100vh para 100dvh;
}
`
</details>

<details> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

![menu close](https://github.com/devhatt/pet-dex-frontend/assets/13170219/ec56e2b2-47c7-47e9-9dc4-9e53c47ceade)
![menu open](https://github.com/devhatt/pet-dex-frontend/assets/13170219/2f8fc743-2368-44f9-9b5e-b51184a9e4ee)
![active menu](https://github.com/devhatt/pet-dex-frontend/assets/13170219/e6be7a9e-8fc9-41f8-8a1b-5d9bc046400e)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ x ] Issue linked
- [ x ] Build working correctly
- [ x ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
- Foi necessário uma pequena alteração na ordem de montagem dos componentes na index.js da home, no sentido de organizar melhor, pois era necessário selecionar itens de outro componente que estava sendo montado depois, a alteração não modificou em nada na renderização do layout.
- As funções foram definidas na index.js da home, por ser necessário a interação entre componentes
</details>

2024-01-31 18:23 UTC, PiluVitu requested changes

2024-01-31 18:23 UTC, PiluVitu commented on .prettierrc
Porque teve essas mudanças ?

2024-01-31 18:24 UTC, PiluVitu commented on src/home/components/SideMenu/index.scss
> +    line-height: 2rem; /* 125% */
@Alecell Isso daqui ta certo ?

2024-02-01 18:33 UTC, Alecell commented on src/home/components/SideMenu/index.scss
> +    line-height: 2rem; /* 125% */
Ta não, line height deve ser sem unidade!

2024-02-02 23:43 UTC, JonasGz commented on src/home/components/SideMenu/index.scss
> +    line-height: 2rem; /* 125% */
removidos, não eram necessários.

2024-02-05 21:35 UTC, JonasGz commented
@Alecell lembrar de revisar

2024-02-07 22:00 UTC, PiluVitu commented on src/home/components/SideMenu/index.scss
> +  }
Porque esse none ?

2024-02-08 11:51 UTC, Alecell requested changes

2024-02-08 11:51 UTC, Alecell commented on package-lock.json
Usar `pnpm` pra instalar dependencias e remover o package-lock

2024-02-08 11:51 UTC, Alecell commented on src/components/TextInput/index.js
> +  'asset:changed',
Pensamos ontem, mudar o `changed` para o imperativo `change`

2024-02-08 11:51 UTC, Alecell commented on src/home/components/SideMenu/index.scss
> +    display: none;
Ele toggla o como o logo é exibido baseado no formato de visualização pra garantir uma centralização correta atravez dos formatos. Ta certinho

2024-02-08 11:51 UTC, Alecell commented on src/home/index.scss
> +  height: 100dvh;
Why `dvh`?

2024-02-08 11:51 UTC, Alecell commented on src/styles/fonts.scss
Esse arquivo veio de outro PR, ele não pode constar como adicionado por vc no seu PR, precisamos ajustar isso

2024-02-08 21:18 UTC, JonasGz commented on src/home/components/SideMenu/index.scss
> +  }
esses itens só são visíveis na side-menu na versão mobile, em resoluções superiores eles ficam no componente da navigation por isso os display:none.

2024-02-09 19:05 UTC, closed without merging