feat: add storybook to visualizate components
devhatt/pet-dex-frontend pull request #62
Opened 2024-01-31 23:26 UTC by diogocaronte

Closes #44 

- **Description**
  add storybook to visualizate components

![image](https://github.com/devhatt/pet-dex-frontend/assets/88992612/5da554e2-e069-475b-ab3d-497f009b1cf9)

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created

2024-02-01 00:11 UTC, aalmeida00 requested changes
cria readme explicando como criar um component storybook

2024-02-01 18:34 UTC, Alecell commented
> cria readme explicando como criar um component storybook

Ia ser bala memo

2024-02-15 21:47 UTC, Alecell approved these changes

2024-02-20 19:19 UTC, aalmeida00 approved these changes

2024-02-21 00:58 UTC, merged