Criação do componente SideMenu
devhatt/pet-dex-frontend pull request #76
Opened 2024-02-16 21:50 UTC by JonasGz

Closes #17 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação de componente sidemenu responsivo com navbar e content, contendo as funções de abrir/fechar e hover/active nos links

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
**Alteração da height da .home de "100vh" para "100dvh"**
**Justificativa:** "dvh" considera as barras de rolagem e barra de endereços da tela do usuário em dispositivos móveis, consequentemente tornando a página mais adaptável.

**FUNÇÕES DO MENU**
A página em seu estado original está com duas grids de 100vw com o componente SideMenu no lado esquerdo, consequentemente ficando visível na tela ao final do carregamento, tendo em vista o carregamento ser da esquerda pra direita, para burlar isso foi adicionado width: 200vw e transform: translateX(-100vw);

**ABRIR MENU:**
openMenu():  adiciona a classe .openMenu para alterar a width da .home para 100vw e o transform para translateX(0), consequentemente retornando ao estado inicial da página com a sidemenu visível, que o objetivo.

**FECHAR MENU:**
exitMenu(): remove a classe .openMenu e adiciona a classe exitMenu() alterando a width da .home ao estado inicial com width: 100vw e transform: translateX(-100vw).

**ACTIVE MENU ITENS:**
activeClassMenu(): ao clicar no item do menu adiciona um background, informando em que item a página está no momento, alterando ao clicar em outros links do menu.

**Obs:** Foi necessário a criação de duas classes, pois se animação transition fosse inserida diretamente na .home animaria no carregamento inicial da página, que não é o objetivo, pois a animação só deve ocorrer ao clicar nos itens de abrir e fechar menu.
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

**OPEN and EXIT MENU**
![open and exit](https://github.com/devhatt/pet-dex-frontend/assets/13170219/4d50017a-e593-427c-ae6c-126804a98298)

**ACTIVE MENU**
![active menu](https://github.com/devhatt/pet-dex-frontend/assets/13170219/5dddb7b1-a555-4bea-aa71-b2a799bfe03e)

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ x ] Issue linked
- [ x ] Build working correctly
- [ x ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-02-21 02:10 UTC, Alecell commented on src/home/index.js
> +  exitMenu($exitMenu, $home);
Gostei disso, mas precisamos falar sobre esse modo que usou os breaking points

2024-02-21 02:10 UTC, Alecell commented on src/home/index.scss
> +  overflow-x: hidden;
Precisa desse overflow?

2024-02-21 02:11 UTC, Alecell commented on src/home/index.scss
> +  }
Coloque os modificadores antes dos elementos filhos

2024-02-23 19:32 UTC, JonasGz commented on src/home/components/navigation/index.js
> +      <figure data-select="hamburgerMenu" class="navigation__icon-container navigation__icon-container--menu">
alterado

2024-02-23 19:32 UTC, JonasGz commented on src/home/index.js
> +  const $exitMenu = sideMenu.selected.get('exitMenu');
alterado

2024-02-23 21:28 UTC, JonasGz commented on src/home/index.scss
> +  }
alterado

2024-02-24 12:37 UTC, JonasGz commented on src/home/index.scss
> +  overflow-x: hidden;
sim, pois quando o menu ta aberto, msm com width setada em 100vw, a outra grid continua existindo e por isso abre habilita o scroll

2024-02-27 02:38 UTC, JonasGz commented on src/home/index.js
> +  const breakpointDesktop = 1024;
**busca incessante pelo li:** resolvida.
**breakpoint:** foi definido a criação de um módulo de breakpoint (issue já foi criada)

2024-02-27 02:38 UTC, JonasGz commented on src/home/index.js
> +  exitMenu($exitMenu, $home);
foi definido a criação de um módulo de breakpoint (issue já foi criada)

2024-02-27 13:38 UTC, Alecell commented on src/home/components/SideMenu/index.scss
> +    height: 5rem;
Coloca um comentário de  `TODO` em cima então pra ficar claro pro futuro!

2024-02-27 13:46 UTC, Alecell requested changes
Seu PR trouxe muitos arquivos que não sao do seu PR, precisa ajustar

2024-02-27 13:46 UTC, Alecell commented on .prettierrc
> +  "endOfLine": "auto",
Porque tivemos essa alteração?

2024-02-27 13:46 UTC, Alecell commented on .storybook/main.js
Parece que seu PR ta trazendo novamente as coisas do storybook que que foram mergeadas, precisa ver isso

2024-02-27 13:46 UTC, Alecell commented on src/home/components/SideMenu/index.scss
> +// @use '~styles/fonts.scss' as fonts;
Pq temos um comentário aqui?

2024-02-27 13:46 UTC, Alecell commented on src/home/components/SideMenu/index.scss
Tem bastante coisa comentada nesse arquivo

2024-02-27 13:46 UTC, Alecell commented on src/home/index.html
esse arquivo tambem não é do seu PR mas ta aqui...

2024-03-02 13:14 UTC, JonasGz commented on src/home/components/SideMenu/index.scss
> +    height: 5rem;
retirei pois realmente não precisava

2024-03-02 13:17 UTC, JonasGz commented on src/home/index.js
> +
movido para uma pasta "util" dentro da home.

2024-03-02 13:21 UTC, JonasGz commented on src/home/components/SideMenu/index.scss
> +// @use '~styles/fonts.scss' as fonts;
retirado

2024-03-04 23:07 UTC, JonasGz commented on .prettierrc
> +  "endOfLine": "auto",
branch tava desatualizada

2024-03-04 23:07 UTC, JonasGz commented on .storybook/main.js
branch tava desatualizada

2024-03-04 23:07 UTC, JonasGz commented on src/home/index.html
branch tava desatualizada

2024-03-06 00:21 UTC, Alecell reviewed
Não consegui rodar sua branch localmente, constantemente tomando erro no `fonts.scss`. Como vc ta conseguindo codar?

2024-03-06 00:21 UTC, Alecell commented on src/home/components/SideMenu/index.scss
> +@use '~styles/base.scss';
Acabei de pensar, o base.scss deveria ser importado aqui? Ele não deveria ser importado direto no `index.html` da página em questão?

2024-03-06 22:10 UTC, JonasGz commented
> Não consegui rodar sua branch localmente, constantemente tomando erro no `fonts.scss`. Como vc ta conseguindo codar?

eu simplesmente retirei tudo de fonts e quando finalizei os testes eu coloquei novamente pq sei q vão atualizar e resolver.

2024-03-06 22:30 UTC, JonasGz commented on src/home/components/SideMenu/index.scss
> +@use '~styles/base.scss';
Retirei. Pois na verdade ele já é importado no index.scss da página home, portanto não precisa ser incluído em nenhum outro componente.

2024-03-10 20:38 UTC, Alecell approved these changes
Brabo!

2024-03-10 20:39 UTC, merged