feat: create toggle component
devhatt/pet-dex-frontend pull request #77
Opened 2024-02-17 02:33 UTC by nathalia-84

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-02-21 01:17 UTC, Alecell requested changes
Precisa preencher o conteúdo do PR com a issue, descrição e etc

Precisa tambem adicionar o componente no storybook!

2024-02-21 01:17 UTC, Alecell commented on src/components/Toggle/index.scss
> +    min-height: 24px;
POG!!!!

2024-02-21 01:17 UTC, Alecell commented on src/components/Toggle/index.scss
> +    background-color: rgba(217, 223, 230, 1);
Usar a cor da nossa paleta de cores

2024-02-21 01:17 UTC, Alecell commented on src/components/Toggle/index.scss
> +      background-color: rgba(255, 255, 255, 1);
Usar a cor da nossa paleta, pegar do colors.scss

2024-02-21 01:17 UTC, Alecell commented on src/components/Toggle/index.js
> +export default function Toggle() {
Poderia ser interessante o componente poder ser instanciado com o seu valor inicial definido

2024-02-21 01:17 UTC, Alecell commented on src/components/Toggle/index.js
> +  },
Esses 2 eventos não estão muito bem nomeados, `isChecked` é em convensão usado com uma pergunta tipo `is it checked?`, a questão é que esse tipo de nomeclatura é em geral usado em variaveis e não em funções, inclusive, funções devem ser nomeadas de forma imperativa conotando uma ação

Por exemplo `isChecked` pode ser alterado por `check`, em pt traduzido poderia ser uma diferença entre `estaChecado` e `checar`, o `checar` é uma ação e esse é o padrão de nomeclatura que esperamos pra funções!

O `notChecked` tambem não está muito bom, no caso é em geral bem ruim usar palavras negatórias em funções e variaveis, no caso o problema é o `not`

Acredito que o melhor a fazer nesse caso desses eventos seria ter uma função só chamada `toggle`, vou colocar um exemplo de implementação

```suggestion
  toggle(checked) {
    if (checked) this.selected.get('toggle-label').classList.add('checked');
    if (!checked) this.selected.get('toggle-label').classList.remove('checked');
    
    this.emit('toggle', checked);
  } 
```

Me fala se tiver dúvida com esse método

2024-02-21 01:17 UTC, Alecell commented on src/components/Toggle/index.js
> +    }
No caso esse método altera para
```suggestion
    this.toggle(checked);
```

2024-02-21 01:17 UTC, Alecell commented on src/components/Toggle/index.scss
> +      background-color: rgba(27, 133, 243, 1);
Usar a cor da nossa paleta, pegar do colors.scss

2024-02-22 00:37 UTC, diogocaronte requested changes

2024-02-22 00:37 UTC, diogocaronte commented on src/components/Toggle/index.js
> +    <label for="toggle-input" class="toggle-container__label" data-select="toggle-label"></label>
O uso dos atributos "id" e do "for" vai dar problema.
Se criarmos duas instancias do toggle o id já não será único.
Temos um utilitário para resolver isso.

Importe o utilitário e crie um gerador de ids
```js
import { Component, createIDFactory } from 'pet-dex-utilities';
const generateID = createIDFactory("toggle");
```

Depois você utiliza ele dentro do componente
```js
const id = generateID();
this.selected.get('toggle-input').setAttribute('id', id);
this.selected.get('toggle-label').setAttribute('for', id);
```

2024-02-22 00:37 UTC, diogocaronte commented on src/components/Toggle/index.scss
> +    &.checked {
Da uma olhada a forma correta de criar modificadores com o BEM
https://getbem.com/naming/#modifier

2024-02-22 00:37 UTC, diogocaronte commented on src/components/Toggle/index.scss
> +    &.checked::after {
Da uma olhada a forma correta de criar modificadores com o BEM
https://getbem.com/naming/#modifier

2024-02-27 00:53 UTC, nathalia-84 commented on src/components/Toggle/index.js
> +export default function Toggle() {
Tentei implementar isso, mas não sei se ficou bom... :/

2024-02-27 00:55 UTC, nathalia-84 commented
> Precisa preencher o conteúdo do PR com a issue, descrição e etc
> 
> Precisa tambem adicionar o componente no storybook!

cmo faço para adicionar ao storybook?

2024-02-27 13:11 UTC, diogocaronte commented on src/components/Toggle/index.js
> +    <label for="toggle-input" class="toggle-container__label" data-select="toggle-label"></label>
Ficou faltando remover os ids da template string na variavel html

2024-02-27 13:26 UTC, diogocaronte requested changes

2024-02-27 13:26 UTC, diogocaronte commented on src/components/Toggle/index.js
> +    <label for="toggle-input" class="toggle-container__label" data-select="toggle-label"></label>
Está faltando remover os IDs na template string do html

2024-02-27 13:26 UTC, diogocaronte commented on src/components/Toggle/index.js
> +export default function Toggle(checked) {
Prefira receber um objeto com todas as props e tente sempre receber valores default

```suggestion
export default function Toggle({ checked = false } = {}) {
```

2024-02-27 13:26 UTC, diogocaronte commented on src/components/Toggle/index.js
> +    checked = !checked;
Evite esse tipo de abordagem pois o estado no js pode ficar desatualizado com o html.
Verifique se o event.target.value possui o estado que você precisa.

De qualquer forma toda a lógica do método de toggle tem que estar no método toggle, aqui você apenas pode lidar com toda a questão de obter e preparar o dado para enviar para o método.

Eu posso por exemplo chamar o toggle diretamente.

2024-02-27 13:28 UTC, diogocaronte commented
> > Precisa preencher o conteúdo do PR com a issue, descrição e etc
> > Precisa tambem adicionar o componente no storybook!
> 
> cmo faço para adicionar ao storybook?

Abra o projeto, e rode o "pnpm storybook".
Acesse o storybook no seu navegador lá terá uma pequena explicação.
Se ainda estiver com dúvidas você pode marcar uma call comigo.

2024-02-27 13:50 UTC, Alecell commented on src/components/Toggle/index.js
> +export default function Toggle() {
Vamos falar sobre na daily hoje!

2024-02-28 01:25 UTC, nathalia-84 commented on src/components/Toggle/index.js
> +export default function Toggle(checked) {
Esse tipo de objeto é novo para mim, poderia explicar melhor?

2024-02-28 01:27 UTC, nathalia-84 commented
> > > Precisa preencher o conteúdo do PR com a issue, descrição e etc
> > > Precisa tambem adicionar o componente no storybook!
> > 
> > 
> > cmo faço para adicionar ao storybook?
> 
> Abra o projeto, rode o "pnpm install" e rode o "pnpm storybook".
> 
> Acesse o storybook no seu navegador lá terá uma pequena explicação.
> 
> Se ainda estiver com dúvidas você pode marcar uma call comigo.

Consegui adicionar ao storybook, mas ainda tenho algumas dúvidas a respeito de como adicionar controls, vou tentar falar com você lá no discord sobre isso.

2024-02-28 13:06 UTC, diogocaronte commented
> > > > Precisa preencher o conteúdo do PR com a issue, descrição e etc
> > > > Precisa tambem adicionar o componente no storybook!
> > > 
> > > 
> > > cmo faço para adicionar ao storybook?
> > 
> > 
> > Abra o projeto, rode o "pnpm install" e rode o "pnpm storybook".
> > Acesse o storybook no seu navegador lá terá uma pequena explicação.
> > Se ainda estiver com dúvidas você pode marcar uma call comigo.
> 
> Consegui adicionar ao storybook, mas ainda tenho algumas dúvidas a respeito de como adicionar controls, vou tentar falar com você lá no discord sobre isso.

Pode me chamar quando ver eu em call no discord

2024-03-01 17:05 UTC, Alecell requested changes

2024-03-01 17:05 UTC, Alecell commented on src/components/Toggle/index.js
> +    this.emit('toggle');
Legal emitir junto o valor atual do check tambem

2024-03-01 19:25 UTC, diogocaronte commented on src/stories/Toggle.stories.js
@Alecell senti falta dos argTypes

2024-03-01 22:15 UTC, nathalia-84 commented on src/components/Toggle/index.scss
> +    min-height: 24px;
base 10

2024-03-09 16:27 UTC, diogocaronte requested changes

2024-03-09 16:27 UTC, diogocaronte commented on src/components/Toggle/index.js
> +  this.selected.get('toggle-input').checked = checked;
Isso precisa estar em um método de toggle, acho que você interpretou errado o meu review anterior

2024-03-09 16:27 UTC, diogocaronte commented on src/components/Toggle/index.js
> +  });
Não podemos depender apenas da UI para interagir com nosso componente.
Criar método para lidar com o toggle

2024-03-10 22:18 UTC, Alecell requested changes
Ta lindo! Só alguns ajustes!

Sem meme, sua animação ta me dando ansiedade, podemos deixar ela um pouco mais rapidinha? 😁

Seu componente também ta com um problema sério de arquitetura. Ele não está do tamanho que vemos visualmente:
![Gravando-2024-03-10-191547](https://github.com/devhatt/pet-dex-frontend/assets/13935760/9b10f82e-4705-45a3-bda5-cb74ecee1a2d)

Eu não vou falar qual era o problema, quero que vc descubra! Fica ai o desafio! 😁

2024-03-10 22:18 UTC, Alecell commented on src/components/Toggle/index.js
> +);
Aqui precisamos de um método chamado `setToggle` cujo recebe um booleano e altera o estado programaticamente do toggle.

Essa alteração provavelmente já vai ativar o emit do toggle, então **não precisa** emitir o evento!

(provavelmente o método que o diogo ta falando é esse que to pedindo)

2024-03-17 20:16 UTC, Alecell approved these changes
BOA!!

2024-03-18 03:22 UTC, diogocaronte approved these changes

2024-03-18 03:23 UTC, merged