Criação de componente para adição de pet
devhatt/pet-dex-frontend pull request #78
Opened 2024-02-17 04:04 UTC by JonasGz

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-02-21 00:52 UTC, Alecell requested changes

2024-02-21 00:52 UTC, Alecell commented on src/components/AvatarButton/index.js
EOF

2024-02-21 00:52 UTC, Alecell commented on src/components/AvatarButton/index.js
> +  <a href="#" class="avatarbutton-container" data-select="avatarbutton">
avatar-button, prefira usar kebab casing

2024-02-21 00:52 UTC, Alecell commented on src/styles/colors.scss
EOF

2024-02-24 13:25 UTC, JonasGz commented on src/components/AvatarButton/index.js
adicionado

2024-02-24 13:25 UTC, JonasGz commented on src/components/AvatarButton/index.js
> +  <a href="#" class="avatarbutton-container" data-select="avatarbutton">
alterado

2024-02-24 13:46 UTC, JonasGz commented on src/components/AvatarButton/index.scss
corrigido

2024-02-24 13:47 UTC, JonasGz commented on src/styles/colors.scss
corrigido, retirei a cor gray pq acabei n utilizando

2024-02-24 13:48 UTC, JonasGz commented on src/home/index.js
corrigido

2024-02-27 02:41 UTC, JonasGz commented on src/home/index.js
> +import Navigation from './components/navigation';
resolvido

2024-02-27 13:53 UTC, Alecell requested changes

2024-02-27 13:53 UTC, Alecell commented on src/components/AvatarButton/index.scss
> +    background: var(--Grey-Grey-900, #202326);
Pq ta usando variavel css e não a variavel sass?

2024-02-27 13:53 UTC, Alecell commented on src/components/AvatarButton/index.scss
> +      stroke: #202326;
pq ta usando cores mockadas e não as variaveis sass?

2024-02-27 13:53 UTC, Alecell commented on src/components/AvatarButton/index.scss
> +    padding: 18px;
Pq temos `padding`, `height` e `width` com `px`?

2024-02-27 13:53 UTC, Alecell commented on src/components/AvatarButton/index.scss
> +  width: fit-content;
Acho que isso não precisa ser `fit-content`

2024-02-27 13:53 UTC, Alecell commented on src/components/AvatarButton/index.scss
Sinto que o stylelint não rodou nesse arquivo

2024-02-29 23:33 UTC, JonasGz commented on src/components/AvatarButton/index.scss
> +    background: var(--Grey-Grey-900, #202326);
corrigido.

2024-02-29 23:34 UTC, JonasGz commented on src/components/AvatarButton/index.scss
> +    padding: 18px;
corrigido.

2024-02-29 23:35 UTC, JonasGz commented on src/components/AvatarButton/index.scss
> +  width: fit-content;
eu setei para que o efeito hover só funcione quando o mouse estiver exatamente no botão, mas amanhã no setor de dúvidas vou levantar essa questão

2024-02-29 23:36 UTC, JonasGz commented on src/components/AvatarButton/index.scss
> +      stroke: #202326;
corrigido.

2024-03-02 12:56 UTC, JonasGz commented on src/components/AvatarButton/index.scss
> +  width: fit-content;
corrigido com criação de uma div pai e display:flex

2024-03-06 00:24 UTC, Alecell approved these changes
Preciso que tenha storybook nesse componente.

2024-03-06 00:24 UTC, Alecell commented on src/components/AvatarButton/index.scss
Precisa configurar seu `stylelint` ele não está rodando nos arquivos

2024-03-06 00:25 UTC, Alecell requested changes
Aprovei sem querer, era pra ser request changes

2024-03-09 16:21 UTC, diogocaronte approved these changes
Precisa adicionar o storybook mas já estou deixando meu aprovado para o Ale poder mergear.

2024-03-14 02:22 UTC, JonasGz commented on src/components/AvatarButton/index.scss
corrigido.

2024-03-15 16:38 UTC, Alecell requested changes
Me pinga!

2024-03-15 16:38 UTC, Alecell commented on src/stories/AvatarButton.stories.js
> +// Aqui criamos um story, passando os parametros que será injetado pela configuração
Apagar o comentário

2024-03-15 16:38 UTC, Alecell commented on src/stories/AvatarButton.stories.js
> +  // Note que podemos receber argumentos
Apagar o comentário

2024-03-15 16:38 UTC, Alecell commented on src/stories/AvatarButton.stories.js
> +// Configuração dos stories
Apagar o comentário

2024-03-15 16:38 UTC, Alecell commented on src/components/AvatarButton/index.scss
Acho que podemos melhorar esse arquivo, vamos conversar!

2024-03-19 21:54 UTC, Alecell approved these changes

2024-03-19 21:54 UTC, merged