slider do pet-dex
devhatt/pet-dex-frontend pull request #79
Opened 2024-02-18 21:17 UTC by buuninbee

Closes

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

N/A

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  N/A

- **Cause**
  N/A

- **Solution**
N/A
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ ] Issue linked
- [ ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-02-18 21:27 UTC, buuninbee commented
![Screenshot from 2024-02-18 18-23-04](https://github.com/devhatt/pet-dex-frontend/assets/113143900/eab5a4c3-1f74-4b82-a1c4-fe9fb607a260)

tá retornando erro quando eu vou importar o arquivo fonts.scss, tá falando que tão usando uma variável que não foi declarada

2024-03-18 03:13 UTC, diogocaronte requested changes
O nome da pasta não está bom (está em português). A pasta de imagem não está no padrão das outras.

O componente está bem limitado e engessado, não consigo adicionar ou remover itens. Os nomes dos métodos não estão bons e não consigo reagir a alteração dos estados.

Não consigo obter o valor atual programaticamente.

Eu estou deixando o CSS com o @Alecell mas tem muita coisa errada, como os breakpoints não padronizados e a estilização por tag

2024-03-18 03:13 UTC, diogocaronte commented on src/components/SeletorDePorte/index.js
> +  },
Imagino que esse método não deva ser publico, ou talvez o nome esteja errado

Apenas nome de classes devem começar com letra maiúscula, sim eu sei que alguma linguagens se usa assim como boa pratica mas, no javascript não

2024-03-18 03:13 UTC, diogocaronte commented on src/components/SeletorDePorte/index.js
> +});
Imagino que esse método não deva ser publico, ou talvez o nome esteja errado

Apenas nome de classes devem começar com letra maiúscula, sim eu sei que alguma linguagens se usa assim como boa pratica mas, no javascript não

2024-03-18 03:13 UTC, diogocaronte commented on src/components/SeletorDePorte/index.js
> +Slider.prototype = Object.assign(Slider.prototype, Component.prototype, {
Nome do componente errado

2024-03-18 03:13 UTC, diogocaronte commented on src/home/index.js
> +import Navigation from './components/navigation';
Isso aqui ta estranho, você puxou a branch atualizada? O Navigation tem que ser maiusculo

2024-03-18 03:13 UTC, diogocaronte commented on src/components/SeletorDePorte/index.js
> +const events = ['click', 'touchstart'];
os eventos não foram usados

2024-03-18 03:13 UTC, diogocaronte commented on src/components/SeletorDePorte/index.js
> +          element.classList.add('active');
não foi usado o BEM https://getbem.com/naming/#modifier

2024-03-18 03:13 UTC, diogocaronte commented on src/components/SeletorDePorte/index.js
> +            children.classList.remove('active');
não foi usado o BEM https://getbem.com/naming/#modifier

2024-03-18 03:13 UTC, diogocaronte commented on src/components/SeletorDePorte/index.js
> +          element.classList.add('active');
não foi usado o BEM https://getbem.com/naming/#modifier

2024-03-19 14:58 UTC, Alecell requested changes
Preciso que preencha corretamente o template da PR, aquela primeira etapa que ta com uns N/A, essas coisas tem que estar preenchidas de acordo!

Faltou criar o storybook do componente para documentação, da uma olhada nos arquivos `.story` que temos no projeto, pra visualiza-los usa `pnpm storybook`!

2024-03-19 14:58 UTC, Alecell commented on src/components/SeletorDePorte/index.js
> +    });
Conseguimos diminuir bastante dessa lógica usando CSS ou usando um objeto de parametrização, podemos rever essa lógica juntos se precisar!

De qualquer forma essas funções não deveriam ser expostas, não baseado no que elas fazem.

2024-03-19 14:58 UTC, Alecell commented on src/components/SeletorDePorte/index.js
> +});
Conseguimos diminuir bastante dessa lógica usando CSS ou usando um objeto de parametrização, podemos rever essa lógica juntos se precisar!

De qualquer forma essas funções não deveriam ser expostas, não baseado no que elas fazem.

2024-03-19 14:58 UTC, Alecell commented on src/components/SeletorDePorte/index.scss
> +  p {
Não usar tag diretamente, sempre colocar classes nos elementos

2024-03-19 14:58 UTC, Alecell commented on src/components/SeletorDePorte/index.scss
Esse arquivo não esta usando o nosso stylelint config, baixe a extensão do vscode PetDex Extension Pack

Preciso que reveja seus estilos, aparentemente tem muito mais estilo por seletor do que realmente precisa.

Não use tag diretamente, sempre coloque uma classe e use o seletor da classe.

2024-03-19 14:58 UTC, Alecell commented on src/components/SeletorDePorte/index.scss
> +    &:first-child img {
Não usar tag diretamente

2024-03-19 14:58 UTC, Alecell commented on src/components/SeletorDePorte/index.scss
> +    &.active {
Aqui não deveria estar usando o `transform: scale()` que conversamos?

2024-03-19 14:58 UTC, Alecell commented on src/components/SeletorDePorte/index.scss
> +    }
Pq precisamos fazer essas alterações ao mesmo tempo que suamos o scale na animação?

2024-03-20 17:55 UTC, buuninbee commented
> O nome da pasta não está bom (está em português). A pasta de imagem não está no padrão das outras.
> 
> O componente está bem limitado e engessado, não consigo adicionar ou remover itens. Os nomes dos métodos não estão bons e não consigo reagir a alteração dos estados.
> 
> Não consigo obter o valor atual programaticamente.
> 
> Eu estou deixando o CSS com o @Alecell mas tem muita coisa errada, como os breakpoints não padronizados e a estilização por tag

O que exatamente não tá no padrão na pasta de imagem? o nome das img ?

2024-03-20 18:10 UTC, buuninbee commented on src/components/SeletorDePorte/index.js
> +export default function Slider(slide) {
entendi, mas o que está fora do padrão na pasta de imagens? o nome das img?

2024-03-24 14:47 UTC, diogocaronte commented on src/components/SeletorDePorte/index.js
> +export default function Slider(slide) {
> entendi, mas o que exatamente está fora do padrão na pasta de imagens? o nome das img?

estamos padronizando como "images"

2024-03-24 14:49 UTC, diogocaronte commented
> > O nome da pasta não está bom (está em português). A pasta de imagem não está no padrão das outras.
> > O componente está bem limitado e engessado, não consigo adicionar ou remover itens. Os nomes dos métodos não estão bons e não consigo reagir a alteração dos estados.
> > Não consigo obter o valor atual programaticamente.
> > Eu estou deixando o CSS com o @Alecell mas tem muita coisa errada, como os breakpoints não padronizados e a estilização por tag
> 
> O que exatamente não tá no padrão na pasta de imagem? o nome das img ?

Estamos padronizando como "images" e não "img"

2024-03-26 19:29 UTC, buuninbee commented on src/components/SeletorDePorte/index.js
> +  },
Pra resolver esse problema eu devo usar a técnica de escopo e de closures para a função retornar só o resultado, certo?

2024-03-26 19:29 UTC, buuninbee commented on src/components/SeletorDePorte/index.js
> +    });
Pra resolver esse problema eu devo usar a técnica de escopo e de closures para a função retornar só o resultado, certo?

2024-03-26 20:17 UTC, diogocaronte commented on src/components/SeletorDePorte/index.js
> +  },
Sim, você tem que aproveitar das closures.

Move essa função para fora do prototype e mesmo movendo ela para fora você vai conseguir acessar.

Voce vai precisar adicionar um novo parametro para fazer o papel do this

2024-04-09 19:33 UTC, PiluVitu commented on src/home/index.html
>  <!doctype html>
Porquê esse arquivo foi alterado ?

2024-04-09 19:55 UTC, diogocaronte requested changes

2024-04-09 19:55 UTC, diogocaronte commented on src/components/SizeSelector/index.js
> +export default function SizeSelector({ slide }) {
```suggestion
export default function SizeSelector({ slide } = {}) {
```

2024-04-09 19:55 UTC, diogocaronte commented on src/components/SizeSelector/index.js
>    const slideItems = this.selected.get(slide);
Essa seleção pelo data-select está muito estranha pra mim, o data-select não foi pensando pra isso
@Alecell

2024-04-09 19:55 UTC, diogocaronte commented on src/components/SizeSelector/index.js
> +  {},
```suggestion
```

2024-04-09 19:55 UTC, diogocaronte commented on src/home/index.html
> +</html>
Não entendi por que esse arquivo foi alterado
E aqui está sem o EOF

2024-04-09 20:41 UTC, Sherlockzen requested changes
E ae man, seria interessante um stories do componente ein, pra testar e etc

2024-06-19 16:11 UTC, Alecell commented
Task vai ser resolvida no PR #265

2024-06-19 16:11 UTC, closed without merging