feat: button update and deactivation and activation functionality
devhatt/pet-dex-frontend pull request #84
Opened 2024-02-23 22:33 UTC by Frompaje

Closes #65
<details open> 
  <summary>
    <b>Feature</b>
  </summary>
Foi atribuído hover ao botão, assim como funcionalidades de desabilitado e habilitado.
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

</details>

![buttonEnabledHover](https://github.com/devhatt/pet-dex-frontend/assets/117830579/c6cac18d-7ba3-41ec-b423-4d425e853be3)

![buttonDisabled](https://github.com/devhatt/pet-dex-frontend/assets/117830579/562d83a2-cb67-45a9-80d5-891af85a2550)

</details>

2024-02-23 23:23 UTC, aalmeida00 approved these changes

2024-02-24 19:45 UTC, aalmeida00 approved these changes

2024-02-24 19:45 UTC, aalmeida00 commented on .gitignore
> +yarn.lock
Na teoria, esses caras nao precisam estar no gitignore, afinal, eles não devem existir nos nossos pacotes, mas entendi o propósito.

2024-02-27 13:58 UTC, Alecell requested changes

2024-02-27 13:58 UTC, Alecell commented on .eslintrc.json
> +    "linebreak-style":"off"
Porque?

2024-02-28 16:51 UTC, Frompaje commented on .eslintrc.json
> +    "linebreak-style":"off"
Boa tarde, como uso o windows fica dando conflito, então me recomendaram desativar o linebreak-style.
O de object-curly-newline, só adicionei uma virgula.

2024-03-04 14:40 UTC, Alecell commented on .eslintrc.json
> +    "linebreak-style":"off"
Entendi, mas isso não pode acontecer. Não podemos remover uma regra de lint porque de problemas de ambiente, preciso que resolva esse problema de ambiente sem alterar regras de lint

2024-03-06 00:29 UTC, diogocaronte approved these changes

2024-03-06 00:34 UTC, Alecell approved these changes

2024-03-06 00:34 UTC, merged