Add Swiper utility function for touch swipe events
devhatt/pet-dex-frontend pull request #85
Opened 2024-02-25 21:18 UTC by JonySamarelli

Closes #29 

<details open> 
  <summary>
    <b>Add Swiper utility function for touch swipe events</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [x] Issue linked
- [x] Build working correctly
- [ ] Tests created
</details>

2024-02-26 02:58 UTC, diogocaronte requested changes
O path do arquivo não está bom
Talvez _src/utils/swiper.js_ já fique melhor
Lembrando que não estamos lidando com componentes/classes então não tem necessidade da letra maiúscula

2024-02-26 02:58 UTC, diogocaronte commented on src/utils/Swiper/Swiper.js
> +    const event = new Event('swipe-left');
Não íamos usar o CustomEvent? Por que optou pelo Event?

2024-02-26 02:58 UTC, diogocaronte commented on src/utils/Swiper/Swiper.js
> +    const event = new Event('swiper-right');
Não íamos usar o CustomEvent? Por que optou pelo Event?

2024-02-26 02:58 UTC, diogocaronte commented on src/utils/Swiper/Swiper.js
> +    const event = new Event('swipe-up');
Não íamos usar o CustomEvent? Por que optou pelo Event?

2024-02-26 02:58 UTC, diogocaronte commented on src/utils/Swiper/Swiper.js
> +    const event = new Event('swipe-down');
Não íamos usar o CustomEvent? Por que optou pelo Event?

2024-02-26 02:58 UTC, diogocaronte commented on src/utils/Swiper/Swiper.js
> +export default function Swiper() {
Não estamos lidando com classes então evite nomes com inicial maiuscula.
Como é um utilitário, acho que ficaria melhor algo como createSwiper ou configureSwipe

2024-02-26 02:58 UTC, diogocaronte commented on src/utils/Swiper/Swiper.js
> +    const yDiff = coordinates.yDown - coordinates.yUp;
Estou sendo meio chato mas, fique atento que como estamos lidando com a distancia entre dois pontos o correto seria B - A
```suggestion
    const xDiff = coordinates.xUp - coordinates.xDown;
    const yDiff = coordinates.yUp - coordinates.yDown;
```

2024-02-26 02:58 UTC, diogocaronte commented on src/utils/Swiper/Swiper.js
> +    const isDown = yDiff < 0;
Note que a lógica está invertida por causa que fez A - B

2024-02-26 02:58 UTC, diogocaronte commented on src/utils/Swiper/Swiper.js
> +      coordinates.yDown - coordinates.yUp !== 0;
Talvez devemos considerar um deadzone para evitar toques acidentais
```suggestion
    const deadzone = 10; // numero fictício 

    const deltaX = coordinates.xUp - coordinates.xDown;
    const deltaY = coordinates.yUp - coordinates.yDown;
    
    const toucheMoved = Math.abs(deltaX) > deadzone || Math.abs(deltaY) > deadzone;
```

2024-02-26 06:33 UTC, JonySamarelli commented on src/utils/Swiper/Swiper.js
> +    const event = new Event('swipe-left');
Na documentação o customEvent é usado para quando eu vou passar dados no meu evento o que não me pareceu o caso aqui.

https://stackoverflow.com/questions/29856721/new-eventbuild-vs-new-customeventbuild
https://developer.mozilla.org/en-US/docs/Web/Events/Creating_and_triggering_events

2024-02-26 13:22 UTC, diogocaronte approved these changes

2024-03-06 01:01 UTC, Alecell requested changes
Cara ta muito bom seu PR, de verdade, só alguns ajustes

2024-03-06 01:01 UTC, Alecell commented on src/utils/swiper.spec.js
> +
Pode apagar essas linhas de espaçamento entre os listeners, eles são semanticamente a mesma coisa então é tudo bem deixar eles no mesmo bloco

2024-03-06 01:02 UTC, JonySamarelli commented on src/utils/swiper.js
> +    }
o .target não tem set, só get, daí fui por essa abordagem

2024-03-06 01:13 UTC, JonySamarelli commented on src/utils/swiper.js
> +export default function initializeSwiper() {
adicionar essa regra ao lint: ""import/prefer-default-export": "off""? sem ela o lint acusa erro no arquivo

2024-03-06 01:17 UTC, JonySamarelli commented on src/utils/swiper.js
> +    }
![image](https://github.com/devhatt/pet-dex-frontend/assets/74078324/1a63a763-1fc1-4927-b1c4-a8776c08f201)

2024-03-06 13:21 UTC, Alecell commented on src/utils/swiper.js
> +export default function initializeSwiper() {
Boa, manda essa pra nois!

2024-03-06 13:22 UTC, Alecell commented on src/utils/swiper.js
> +    }
Acho que a melhor coisa é tentar dar um surpass nisso, de alguma forma, o modo como ta é bem anti pattern. Seu componente nunca deve conhecer nada de teste. Podemos falar sobre isso

2024-03-08 22:02 UTC, JonySamarelli commented on src/utils/swiper.js
> +    }
![image](https://github.com/devhatt/pet-dex-frontend/assets/74078324/a4f8dcdf-1003-4af1-952f-11e36b73ae7c)

Desse jeito fica melhor?

2024-03-10 20:52 UTC, Alecell approved these changes
Com o meu commit seu PR ta aprovado!

Me fala oque achou pra saber se posso ou não mergear!

2024-03-10 20:52 UTC, Alecell commented on src/utils/swiper.js
> +    }
Fiz um commit no seu PR com a solução!

Mas essa sua proposta ficaria no proprio `swiper.js` né? Se sim, isso ainda não pode nunca acontecer, nunca um teste seu deve interferir na escrita do seu componente e nunca vc deve fazer algo no seu componente porque da camada de teste, a menos que seja algo tipo "mudei algo no componente e o teste não passa", mas quando forem casos tecnicos tipo esse a gente **sempre** vai resolver do lado do teste pq é como eu falei, nunca a implementação de uma funcionalidade deve adicionar qualquer coisa a mais pra poder testar.

Existem exceções como casos de arquitetura e de facilidade de teste, mas no caso a gente tem um desfluxo que altera o conteúdo no cenário de teste e isso nunca deve acontecer pois estamos basicamente sujando nosso teste.

2024-03-10 22:20 UTC, Alecell approved these changes

2024-03-10 22:24 UTC, JonySamarelli reviewed
Fechou

2024-03-10 22:59 UTC, diogocaronte approved these changes

2024-03-10 22:59 UTC, diogocaronte commented on src/utils/swiper.js
> +export function initializeSwiper() {
```suggestion
export function initializeSwiper({ deadZone = 50 } = {}) {
```

2024-03-10 22:59 UTC, diogocaronte commented on src/utils/swiper.js
> +    const deadZone = 50;
```suggestion
```

2024-03-10 22:59 UTC, diogocaronte commented on src/utils/swiper.js
> +  window.addEventListener('touchend', handleTouchEnd, false);
```suggestion
  window.addEventListener('touchstart', handleTouchStart, false);
  window.addEventListener('touchend', handleTouchEnd, false);
  
  return function destroy() {
      window.removeEventListener('touchstart', handleTouchStart);
      window.removeEventListener('touchend', handleTouchEnd);
  }
```

2024-03-10 23:22 UTC, PiluVitu approved these changes

2024-03-10 23:22 UTC, merged