feat: input dinamic range slider
devhatt/pet-dex-frontend pull request #88
Opened 2024-02-28 20:11 UTC by RafaelLimaC

Closes #26 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

Criação do componente de range dinâmico. Com animação de movimento ao arrastar o botão.

</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
Funcionalidade do componente: quando o usuário clica no botão e arrasta o componente calcula a direção do mouse ou touch para dispositivos móveis e move o background na direção respectiva para dar a impressão de movimento para o usuário.
</details>

<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>
![image](https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExbzYybnZkZGlrbHBiY2dwbnFpOTA0b3VvZnJ6dHU1enZrZThjeXo5NSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/jo9IUvP0bqpt54ogUC/giphy.gif)
</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
N/A
</details>

2024-03-01 00:27 UTC, diogocaronte requested changes
Estamos lidando com um componente de slider mas ele está muito engessado.

Não consigo mudar o mínimo.
Não consigo mudar o máximo.
Não consigo mudar a unidade.

O componente está sugerindo um slider genérico mas ele está sendo especifico para peso. Não tenho nem a opção de remover o titulo.

2024-03-01 00:27 UTC, diogocaronte commented on src/stories/RangeSlider.stories.js
> +    unit: { control: 'text', default: 'kg' },
Se estamos lidando com unidades, que tal definir as unidades disponíveis?

2024-03-01 00:27 UTC, diogocaronte commented on src/components/RangeSlider/index.js
> +  const handleMouseMove = (event) => {
O nome da a entender que estou lidando com o evento de mouse mas, tenho lógica de toque também.

2024-03-01 00:27 UTC, diogocaronte commented on src/components/RangeSlider/index.js
> +  const stepSize = 0.05;
Oque é esse stepsize?
Por que ele é fixo?

2024-03-01 00:34 UTC, hxsggsz approved these changes
sem nenhuma observação a mais além as do djogo

2024-03-01 00:46 UTC, RafaelLimaC commented on src/components/RangeSlider/index.js
> +      <span class="range-slider__info" data-select="range-slider-unit">kg</span>
pra iniciar com algum valor e unidade, se n só vai aparecer quando a pessoa arrastar pela primeira vez

2024-03-01 00:48 UTC, RafaelLimaC commented on src/components/RangeSlider/index.js
> +  const handleMouseMove = (event) => {
na issue pedia só de change e fim da interação

"Este componente deve apresentar uma animação suave e permitir a configuração de valores mínimos e máximos, além de expor eventos para mudanças em tempo real e ao finalizar a interação."

2024-03-01 00:48 UTC, RafaelLimaC commented on src/components/RangeSlider/index.js
> +const events = ['change', 'interactionEnd'];
na issue pedia só de change e fim da interação

"Este componente deve apresentar uma animação suave e permitir a configuração de valores mínimos e máximos, além de expor eventos para mudanças em tempo real e ao finalizar a interação."

2024-03-01 00:49 UTC, RafaelLimaC commented on src/components/RangeSlider/index.js
> +    startX = mouseX;
como assim cancelar o slide? arrastar e dar um esc por ex?

2024-03-01 00:52 UTC, RafaelLimaC commented on src/components/RangeSlider/index.js
> +  const stepSize = 0.05;
ele define a velocidade q os valores vão aumentando/diminuindo conforme a pessoa arrasta o mouse, se quiser que ela arraste menos o mouse é só aumentar o stepSize, tentei deixar numa velocidade que não fique muito dificil parar em um valor específico

2024-03-01 01:03 UTC, RafaelLimaC commented on src/components/RangeSlider/index.js
> +      <span class="range-slider__info" data-select="range-slider-unit">kg</span>
![local onde é usado](https://github.com/devhatt/pet-dex-frontend/assets/132157467/d21394b7-ce08-478c-b41b-b27347bf6d2d)

aqui é onde o componente é usado, ele por padrão vem checked kg, pensei que ficava melhor iniciar ele com algum valor ao invés de 0.

2024-03-01 01:04 UTC, RafaelLimaC commented on src/components/RangeSlider/index.js
> +      <span class="range-slider__info" data-select="range-slider-unit">kg</span>
e o maximo mínimo são definidos quando o componente é chamado, eu fiz o storybook dele. o kg eu coloquei ai pensando em facilitar o trabalho da proxima pessoa q vai implementar o radio button

2024-03-01 01:32 UTC, RafaelLimaC commented on src/components/RangeSlider/index.js
> +  let currentValue = Math.min(Math.max(10, minimum), maximum);
>> colocar um getter no currentvalue

2024-03-01 01:46 UTC, RafaelLimaC commented on src/components/RangeSlider/index.js
> +      <span class="range-slider__info" data-select="range-slider-unit">kg</span>
>> get e sett do min max unit step e initial value

2024-03-01 01:47 UTC, RafaelLimaC commented on src/components/RangeSlider/index.js
> +const events = ['change', 'interactionEnd'];
>> evento de start e expor currentvalue

2024-03-02 04:50 UTC, hxsggsz approved these changes

2024-03-02 05:05 UTC, aalmeida00 approved these changes

2024-03-02 16:45 UTC, diogocaronte approved these changes

2024-03-02 16:52 UTC, merged