feat: breakpoints js and scss media variables exported
devhatt/pet-dex-frontend pull request #89
Opened 2024-03-01 02:03 UTC by juliaam

fix #87

Closes #87 

<details open> 
  <summary>
    <b>Feature</b>
  </summary>

<p> Criação dos breakpoints para uso no javascript </p>

</details>

<details open> 
  <summary>
    <b>Bugfix</b>
  </summary>

- **Description**
  <p> É retornado um objeto que informa sobre  os tamanho das telas sendo reconhecidos através do window.matchMedia() e do uso das variáveis originais dos #74 anteriormente implementados </p>

- **Cause**
  <p> Não havia módulos de breakpoints para uso nos arquivos js. </p>

- **Solution**
  <p>  Criação do módulo que permite retornar através do objeto os valores do tamanho da tela atual
</details>

<details> 
  <summary>
    <b>Changelog</b>
  </summary>
N/A
</details>

<details open> 
  <summary>
    <b>Visual evidences : 
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/38a2cae9-0176-4f59-be72-425600026ba8)
![image](https://github.com/devhatt/pet-dex-frontend/assets/35346206/032017df-57ce-4994-9ccb-1450d0e8c2e2)

:
</b>
  </summary>

</details>

<details open> 
  <summary>
    <b>Checklist</b>
  </summary>

- [ x ] Issue linked
- [ x ] Build working correctly
- [ ] Tests created
</details>

<details> 
  <summary>
    <b>Additional info: </b>
  </summary>

Forma de uso:
`import breakpointJs from '../utils/breakpoints';
const { from320, from360 } = breakpointJs()

if(.from320 && !from360 ) {
 do this
}
`
</details>

2024-03-07 21:45 UTC, hxsggsz approved these changes

2024-03-07 21:48 UTC, diogocaronte requested changes

2024-03-07 21:48 UTC, diogocaronte commented on src/utils/breakpoints/breakpoints.js
> +export function listenCallBack(breakpoint, callback) {
Callback está escrito errado

Mas de qualquer forma tenta deixar "listen" ou "listenBreakpoint" pois "listenCallback" está errado

2024-03-07 21:48 UTC, diogocaronte commented on src/utils/breakpoints/breakpoints.js
> +export function unlistenCallback(breakpoint, callback) {
Tenta deixar "unlisten" ou "unlistenBreakpoint" pois "unlistenCallback" está errado

2024-03-08 14:16 UTC, PiluVitu requested changes

2024-03-08 14:16 UTC, PiluVitu commented on src/utils/breakpoints/breakpoints.js
> +});
Essa mesma estrutura se repete muitas vezes, não teria como fazer algo tipo um [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) no obj, para conseguir deixar um pouco mais dinâmico ?

2024-03-08 20:42 UTC, juliaam commented on src/utils/breakpoints/breakpoints.js
> +export function listenCallBack(breakpoint, callback) {
alterado para listenBreakpoint

2024-03-08 20:42 UTC, juliaam commented on src/utils/breakpoints/breakpoints.js
> +export function unlistenCallback(breakpoint, callback) {
alterado para unlistenBreakpoint

2024-03-08 20:43 UTC, juliaam commented on src/utils/breakpoints/breakpoints.js
> +  const callbacks = events.get('from320');
corrigido para from360

2024-03-08 21:05 UTC, juliaam commented on src/utils/breakpoints/breakpoints.js
> +});
feito um forEach 

Object.keys(obj).forEach((key) => {
  obj[key].addEventListener('change', (e) => {
    const callbacks = events.get(key);
    callbacks.forEach((callback) => callback(e.matches));
  });
});

2024-03-09 17:07 UTC, PiluVitu approved these changes

2024-03-09 17:07 UTC, merged