feat: Add RadioButton e Checkbox
devhatt/pet-dex-frontend pull request #90
Opened 2024-03-01 18:40 UTC by jeressy

_Closes #25_ 
<details open>
  <summary>
     <b> Feature </b>
  </summary>
Adiciona os componentes RadioButton e Checkbox. 
</details>
<details open> 
  <summary>
    <b>Visual evidences :framed_picture:</b>
  </summary>

- Checkbox: 

![Checkbox](https://github.com/devhatt/pet-dex-frontend/assets/100847406/8c7de3fb-9579-417f-be7f-e0f79e770e74)

- Radio Button: 

![radio_btn](https://github.com/devhatt/pet-dex-frontend/assets/100847406/237e49ae-4719-4b10-b023-146dad50a211)

</details>

<details> 
  <summary>
    <b>Additional info</b>
  </summary>
Ambos componentes foram documentados no storybook;
Checkbox possui suporte para ter opções desativadas, conforme na imagem acima. 
</details>

2024-03-01 19:53 UTC, diogocaronte requested changes
Estou sentindo falta de um component para checkbox group e radio group.
@Alecell acha que isso foge do escopo da task?

2024-03-01 19:53 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +    },
Sempre que mudamos um estado do componente, precisamos notificar a alteração.
```suggestion
    setChecked(isChecked = false) {
        const $checkbox = this.selected.get('checkbox');
        $checkbox.checked = isChecked;
         // seria legal se você emitir o valor antigo e o novo
        this.emit("change", isChecked);
    },
```

2024-03-01 19:53 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +    });
Na maior parte dos casos a gente sempre vai preparar os dados no listener e enviar para um método do componente. Pois quem lida com a lógica é o método

```suggestion
    $checkbox.addEventListener('change', (e) => {
        const isChecked = e.target.checked;
        this.setChecked(isChecked);
    });
```

2024-03-01 19:53 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +    },
Sempre que mudamos um estado do componente, precisamos notificar a alteração.
```suggestion
    setText(text = '') {
        const $checkboxText = this.selected.get('checkbox-text');
        $checkboxText.textContent = text;
        // seria legal se você emitir o valor antigo e o novo
        this.emit("text:change", text); // lembre de registrar o evento
    }, 
```

2024-03-01 19:53 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +    },
Sempre que mudamos um estado do componente, precisamos notificar a alteração.
```suggestion
    setDisabled(isDisabled = false) {
        const $checkbox = this.selected.get('checkbox');
        $checkbox.disabled = isDisabled;
        // seria legal se você emitir dois eventos diferentes um para disable e outro para enable
        // mas pode manter apenas um evento com o valor antigo e o novo
        this.emit("disable", isDisabled); // lembre de registrar o evento
    },
```

2024-03-01 19:53 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +    }
Sempre que mudamos um estado do componente, precisamos notificar a alteração.
```suggestion
    setValue(value = '') {
        const $checkbox = this.selected.get('checkbox');
        $checkbox.value = value;
        // seria legal ter o valor antigo e o novo
        this.emit("value:change", value); // não esquecer de registrar o evento
    }
```

2024-03-01 19:53 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +    const updatedHtml = html.replace('value=""', `value="${value}"`);
Isso aqui não está legal, o value vai vir do banco de dados e isso pode ter problema de XSS https://pt.wikipedia.org/wiki/Cross-site_scripting

Mude isso para uma chamada do setter do value

2024-03-01 19:53 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +export default function RadioButton({ isChecked = false, text = '', value = '' }) {
```suggestion
export default function RadioButton({ isChecked = false, text = '', value = '' } = {}) {
```

2024-03-01 19:53 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +export default function Checkbox({ isChecked = false, text = '', isDisabled = false, value = '' }) {
```suggestion
export default function Checkbox({ isChecked = false, text = '', isDisabled = false, value = '' } = {}) {
```

2024-03-01 19:53 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +    <input data-select="radio" type="radio" name="radio-group" value="">
O name precisa ser editavel (ter um getter e setter)

2024-03-01 19:53 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +    });
```suggestion
    $radioButton.addEventListener('change', (e) => {
        const isChecked = e.target.checked;
        this.setChecked(isChecked);
    });
```

2024-03-01 19:53 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +    },
emitir o evento

2024-03-01 19:53 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +    },
emitir o evento

2024-03-01 19:53 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +    }
emitir o evento

2024-03-01 19:53 UTC, diogocaronte commented on src/stories/Checkbox.stories.js
> +  };
```suggestion
  export const Disabled = {
    args: {
        ...Default.args,
        isDisabled: true
    },
  };
```

2024-03-01 19:53 UTC, diogocaronte commented on src/stories/Checkbox.stories.js
> +  };
EOF

2024-03-01 19:53 UTC, diogocaronte commented on src/stories/RadioButton.stories.js
> +  };
EOF

2024-03-09 16:08 UTC, diogocaronte requested changes

2024-03-09 16:08 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +    const $radioButtonText = this.selected.get('radioButtonText');
Usar kebab-case
```suggestion
    const $radioButton = this.selected.get('radio-button');
    const $radioButtonText = this.selected.get('radio-button-text');
```

2024-03-09 16:08 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +        return this.selected.get('radioButton').checked;
```suggestion
        return this.selected.get('radio-button').checked;
```

2024-03-09 16:08 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +        const $radioButton = this.selected.get('radioButton');
```suggestion
        const $radioButton = this.selected.get('radio-button');
```

2024-03-09 16:08 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +const events = ['change'];
```suggestion
const events = ['change', 'value:change', 'text:change', 'name:change'];
```

2024-03-09 16:08 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +        const $radioButtonText = this.selected.get('radioButtonText');
```suggestion
        const $radioButtonText = this.selected.get('radio-button-text');
```

2024-03-09 16:08 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +        const $radioButton = this.selected.get('radioButton');
```suggestion
        const $radioButton = this.selected.get('radio-button');
```

2024-03-09 16:08 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +        const $radioButton = this.selected.get('radioButton');
```suggestion
        const $radioButton = this.selected.get('radio-button');
```

2024-03-09 16:08 UTC, diogocaronte commented on src/components/RadioButton/index.js
> +        const $radioButton = this.selected.get('radioButton');
```suggestion
        const $radioButton = this.selected.get('radio-button');
```

2024-03-09 16:08 UTC, diogocaronte commented on src/components/Checkbox/index.js
> +    },
Imagino que aqui precise de uma validação para evitar mudar o valor caso ele esteja desabilitado

2024-03-10 21:59 UTC, Alecell requested changes
Seu componente está muito bonito, de verdade! Aqui no storybook ta lindão, só precisamos fazer alguns ajustes!

Aparentemente seu PR ta usando 4 espaços de indentação, o projeto usa apenas 2, precisa fazer esse ajuste.

Outra coisa é que seus arquivos scss estão com alguns problemas nas unidades, por exemplo `width`, `height`, `padding`, `margin` e _fontes_. Todos devem usar outras unidades diferentes de `px`. [Nesse artigo eu explico melhor essa questão das unidades](https://www.linkedin.com/pulse/unidades-css-um-guia-completo-alexandre-gomes/)

Os seus SCSS e JS tambem parecem que não estão lintados, vc ta usando o nosso extension pack? Nele ja tem todas as extensões que vc vai precisar! [PetdexExtensionPack](https://marketplace.visualstudio.com/items?itemName=DevHat.petdex-extension-pack)

Seu componente não deve ter uma margin padrão nele, essa margin será definida por quem precisar usar seu componente e não pelo seu componente em si! Assim damos liberdade a quem usa o componente de espaçar ele da fome que precisar
![image](https://github.com/devhatt/pet-dex-frontend/assets/13935760/7c35dc3d-f8d5-4bc1-a18a-74125674ee66)

Seu PR veio com vários arquivos de imagem e uma alteração no main que não era pra fazer parte desse PR, precisamos ajustar isso!

São alterações simples a pesar de ser bastante! Na questão do rebase interativo, chame alguem pra te ajudar pra garantir que não vai perder nada!

No mais seu PR ta muito bom, a maior parte das observações são sobre padrão e não sobre coisas categoricamente erradas! Ta muito dahora, parabens!

2024-03-10 21:59 UTC, Alecell commented on src/components/Checkbox/index.scss
> +@import '../../styles/colors.scss';
usar o import alias `@import '~styles/colors.scss';`

2024-03-10 21:59 UTC, Alecell commented on src/components/Checkbox/index.scss
Precisa instalar o package do petdex no vscode, seu SCSS não ta lintado conforme nossas regras de stylelint

2024-03-10 21:59 UTC, Alecell commented on src/components/Checkbox/index.scss
> +    input[type="checkbox"]:disabled {
Não usar tags diretamente como seletor de elementos, isso torna a manutenção do seu CSS a longo prazo mais complicada

2024-03-10 21:59 UTC, Alecell commented on src/components/Checkbox/index.scss
> +    input[type="checkbox"] {
Não usar tags diretamente como seletor de elementos, isso torna a manutenção do seu CSS a longo prazo mais complicada

2024-03-10 21:59 UTC, Alecell commented on src/components/Checkbox/index.scss
> +    margin: 10px;
Usar `rem` para `margin`

2024-03-10 21:59 UTC, Alecell commented on src/components/Checkbox/index.scss
> +        height: 22px;
Não usar `px` para `width` nem `height`. No caso poderia ser `rem` provavelmente ou `%`, `width` e `height` varia de caso para caso

Essas questões de unidades eu explico aqui nesse artigo: https://www.linkedin.com/pulse/unidades-css-um-guia-completo-alexandre-gomes/

2024-03-10 21:59 UTC, Alecell commented on src/components/Checkbox/index.scss
> +        border: 2px solid #ACACB5;
As cores devem vir do arquivo de cores padrões da aplicação, caso a cor que vc precisa não estiver lá pode adicionar ela vc mesma no arquivo!

2024-03-10 21:59 UTC, Alecell commented on src/components/Checkbox/index.scss
> +        margin: 8px;
Mesma coisa que citei sobre a unidade da margin

2024-03-10 21:59 UTC, Alecell commented on src/components/Checkbox/index.scss
> +        letter-spacing: 0px;
Tudo que for derivado de fonte como `font-size`, `line-height`, `letter-spacing` e outras coisas que estilizam fonte devem usar `rem` tambem

2024-03-10 21:59 UTC, Alecell commented on src/components/RadioButton/index.js
A identação toda desse arquivo ta suando 4 espaços, o padrão do projeto é 2 espaços!

2024-03-10 21:59 UTC, Alecell commented on src/components/RadioButton/index.js
> +    setChecked(isChecked = false) {
```suggestion
    setCheck(isChecked = false) {
```

2024-03-10 21:59 UTC, Alecell commented on src/components/RadioButton/index.scss
> +    padding: 10px 80px 10px 10px;
Não mencionei antes mas `padding` tambem deve ser feito usando `rem`

2024-03-10 21:59 UTC, Alecell commented on src/home/index.html
Prece que vc ta trazendo commits que não são do seu PR nesse PR, a alteração desse arquivo por exemplo não faz parte do seu PR e não deveria estar aqui.

Pra resolver isso usamos rebase interativo, mas devo dizer que é bem complicadinho. Cola com a gente esse semana pra podermos resolver isso! Pq é um problema bem complicado de resolver e se resolver errado vc ainda pode perder tudo que vc fez x.x

2024-03-10 21:59 UTC, Alecell commented on vite.config.js
Esse arquivo tambem não faz parte desse PR! Mesmo problema dos outros mencionados!

2024-03-28 13:55 UTC, closed without merging